### ISSUE TITLE
Progress column not updating

### ISSUE THREAD

**Issue by actricom** [BiglySoftware/BiglyBT#1091]
Hi

I've just updated to 2.0.0.0 and that has stopped the "Progress" column bar from working in the "My Torrents - Simple List" view. It just stays empty of colour from 0-100% although the percentage counter number does count up properly. The "Completion" column does work, but I prefer to use the "Progress" one as it combines more info. It all worked fine in the previous 3 versions.

Java 1.8.0_211 (64 bit)
  Oracle Corporation
c:\program files\java\jre1.8.0_211

SWT v4922, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.0.0.0/4 az3

**Comment by TheScottMan** [comment]
same here

**Comment by parg** [comment]
I'll take a look, thanks

**Comment by parg** [comment]
Very odd - for me it updates just fine whatever options I enable for it (show speed/show ETA). Can you check the debug_1.log and debug_2.log files in the logs folder within the BiglyBT config dir (%APPDATA%\BiglyBT) to see if there are any UI related messages?

**Comment by TheScottMan** [comment]
there are other "interface" problems as well... the "download" text next to
searched torrent is white and not easily seen

[02/06/19 15:29] Log File Opened for BiglyBT 2.0.0.0
[15:30:04] [stderr] Warning - No client apps or router console configured -
we are just a router
[15:31:09] [stderr] Unsupported or unrecognized format for
http://bitsnoop.com/favicon.ico at /Library/Application
Support/BiglyBT/cache/1944502201.ico
[15:31:11] [stderr] Unsupported or unrecognized format for
0x16;http://bitsnoop.com/favicon.ico at /Library/Application
Support/BiglyBT/cache/1944502201.ico
[15:31:39] [stderr] DEBUG::Sun Jun 02 15:31:39 MUT
2019::com.biglybt.core.networkmanager.impl.tcp.ProxyLoginHandler::readConfig
::88:
[15:31:39] [stderr]   java.lang.NumberFormatException: For input string:
"3129, 8080, 81"
    at 
java.lang.NumberFormatException.forInputString(NumberFormatException.java:65
)
    at java.lang.Integer.parseInt(Integer.java:580)
    at java.lang.Integer.parseInt(Integer.java:615)
    at 
com.biglybt.core.networkmanager.impl.tcp.ProxyLoginHandler.readConfig(ProxyL
oginHandler.java:86)
    at 
com.biglybt.core.networkmanager.impl.tcp.ProxyLoginHandler.<clinit>(ProxyLog
inHandler.java:69)
    at 
com.biglybt.core.networkmanager.impl.tcp.TCPTransportImpl.connectOutbound(TC
PTransportImpl.java:220)
    at 
com.biglybt.core.networkmanager.impl.tcp.ProtocolEndpointTCP.connectOutbound
(ProtocolEndpointTCP.java:139)
    at 
com.biglybt.core.networkmanager.ConnectionEndpoint.connectOutbound(Connectio
nEndpoint.java:157)
    at 
com.biglybt.core.networkmanager.impl.NetworkConnectionImpl.connect(NetworkCo
nnectionImpl.java:157)
    at 
com.biglybt.core.peer.impl.transport.PEPeerTransportProtocol.<init>(PEPeerTr
ansportProtocol.java:776)
    at 
com.biglybt.core.peer.impl.PEPeerTransportFactory.createTransport(PEPeerTran
sportFactory.java:63)
    at 
com.biglybt.core.peer.impl.control.PEPeerControlImpl.makeNewOutgoingConnecti
on(PEPeerControlImpl.java:1497)
    at 
com.biglybt.core.peer.impl.control.PEPeerControlImpl.doConnectionChecks(PEPe
erControlImpl.java:5001)
    at 
com.biglybt.core.peer.impl.control.PEPeerControlImpl.schedule(PEPeerControlI
mpl.java:832)
    at 
com.biglybt.core.peermanager.control.impl.PeerControlSchedulerPrioritised$in
stanceWrapper.schedule(PeerControlSchedulerPrioritised.java:306)
    at 
com.biglybt.core.peermanager.control.impl.PeerControlSchedulerPrioritised.sc
hedule(PeerControlSchedulerPrioritised.java:125)
    at 
com.biglybt.core.peermanager.control.impl.PeerControlSchedulerImpl$1.run(Pee
rControlSchedulerImpl.java:147)
    at com.biglybt.core.util.AEThread2$threadWrapper.run(AEThread2.java:304)
[15:31:39] [stderr]
[15:32:08] [stderr] DEBUG::Sun Jun 02 15:32:08 MUT
2019::com.biglybt.core.networkmanager.impl.tcp.ProxyLoginHandler::readConfig
::88:
[15:32:08] [stderr]   java.lang.NumberFormatException: For input string:
"3129, 8080, 81"
    at 
java.lang.NumberFormatException.forInputString(NumberFormatException.java:65
)
    at java.lang.Integer.parseInt(Integer.java:580)
    at java.lang.Integer.parseInt(Integer.java:615)
    at 
com.biglybt.core.networkmanager.impl.tcp.ProxyLoginHandler.readConfig(ProxyL
oginHandler.java:86)
    at 
com.biglybt.core.networkmanager.impl.tcp.ProxyLoginHandler$1.configurationSa
ved(ProxyLoginHandler.java:65)
    at 
com.biglybt.core.config.impl.ConfigurationManager.save(ConfigurationManager.
java:295)
    at 
com.biglybt.core.config.impl.ConfigurationManager.save(ConfigurationManager.
java:314)
    at 
com.biglybt.core.config.COConfigurationManager.save(COConfigurationManager.j
ava:526)
    at 
com.biglybt.core.config.impl.ConfigurationManager$1.runSupport(Configuration
Manager.java:69)
    at com.biglybt.core.util.AERunnable.run(AERunnable.java:36)
    at 
com.biglybt.core.util.FrequencyLimitedDispatcher$2.runSupport(FrequencyLimit
edDispatcher.java:134)
    at com.biglybt.core.util.AERunnable.run(AERunnable.java:36)
    at com.biglybt.core.util.DelayedEvent$1.perform(DelayedEvent.java:48)
    at com.biglybt.core.util.TimerEvent.runSupport(TimerEvent.java:133)
    at com.biglybt.core.util.AERunnable.run(AERunnable.java:36)
    at com.biglybt.core.util.ThreadPool.runIt(ThreadPool.java:328)
    at 
com.biglybt.core.util.ThreadPool$threadPoolWorker.run(ThreadPool.java:720)
    at com.biglybt.core.util.AEThread2$threadWrapper.run(AEThread2.java:304)
[15:32:08] [stderr]
[15:32:27] [stderr] DEBUG::Sun Jun 02 15:32:27 MUT
2019::com.biglybt.core.networkmanager.impl.tcp.ProxyLoginHandler::readConfig
::88:
[15:32:27] [stderr]   java.lang.NumberFormatException: For input string:
"3129, 8080, 81"
    at 
java.lang.NumberFormatException.forInputString(NumberFormatException.java:65
)
    at java.lang.Integer.parseInt(Integer.java:580)
    at java.lang.Integer.parseInt(Integer.java:615)
    at 
com.biglybt.core.networkmanager.impl.tcp.ProxyLoginHandler.readConfig(ProxyL
oginHandler.java:86)
    at 
com.biglybt.core.networkmanager.impl.tcp.ProxyLoginHandler$1.configurationSa
ved(ProxyLoginHandler.java:65)
    at 
com.biglybt.core.config.impl.ConfigurationManager.save(ConfigurationManager.
java:295)
    at 
com.biglybt.core.config.impl.ConfigurationManager.save(ConfigurationManager.
java:314)
    at 
com.biglybt.core.config.COConfigurationManager.save(COConfigurationManager.j
ava:526)
    at 
com.biglybt.ui.swt.Utils$ShellMetricsResizeListener.saveMetrics(Utils.java:2
105)
    at 
com.biglybt.ui.swt.Utils$ShellMetricsResizeListener.handleEvent(Utils.java:2
117)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4297)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1516)
    at org.eclipse.swt.widgets.Widget.release(Widget.java:1353)
    at org.eclipse.swt.widgets.Control.release(Control.java:2963)
    at org.eclipse.swt.widgets.Widget.dispose(Widget.java:694)
    at 
com.biglybt.ui.swt.progress.ProgressWindow.destroy(ProgressWindow.java:577)
    at 
com.biglybt.ui.swt.progress.ProgressWindow$3$1.run(ProgressWindow.java:180)
    at com.biglybt.ui.swt.Utils$13.runSupport(Utils.java:1188)
    at com.biglybt.core.util.AERunnable.run(AERunnable.java:36)
    at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
    at 
org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
    at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4073)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3740)
    at 
com.biglybt.ui.swt.progress.ProgressWindow.<init>(ProgressWindow.java:192)
    at 
com.biglybt.ui.swt.progress.ProgressWindow$1.operationCreated(ProgressWindow
.java:71)
    at com.biglybt.core.impl.CoreImpl.createOperation(CoreImpl.java:3041)
    at 
com.biglybt.ui.swt.debug.UIDebugGenerator$3.coreRunning(UIDebugGenerator.jav
a:317)
    at 
com.biglybt.ui.swt.shells.CoreWaiterSWT$1.coreRunning(CoreWaiterSWT.java:56)
    at 
com.biglybt.core.impl.CoreImpl.addCoreRunningListener(CoreImpl.java:3116)
    at 
com.biglybt.core.CoreFactory.addCoreRunningListener(CoreFactory.java:96)
    at 
com.biglybt.ui.swt.shells.CoreWaiterSWT.waitForCore(CoreWaiterSWT.java:52)
    at 
com.biglybt.ui.swt.debug.UIDebugGenerator.generate(UIDebugGenerator.java:312
)
    at 
com.biglybt.ui.swt.debug.UIDebugGenerator.generate(UIDebugGenerator.java:73)
    at 
com.biglybt.ui.swt.mainwindow.MenuFactory$75.handleEvent(MenuFactory.java:24
37)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4297)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
    at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4121)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3738)
    at com.biglybt.ui.swt.mainwindow.SWTThread.<init>(SWTThread.java:323)
    at 
com.biglybt.ui.swt.mainwindow.SWTThread.createInstance(SWTThread.java:60)
    at com.biglybt.ui.swt.Initializer.<init>(Initializer.java:179)
    at com.biglybt.ui.swt.UI.takeMainThread(UI.java:110)
    at com.biglybt.ui.Main.main(Main.java:239)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at 
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62
)
    at 
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl
.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:85)
    at com.install4j.runtime.launcher.MacLauncher.main(MacLauncher.java:53)
[15:32:27] [stderr]
[15:32:41] [stderr] DEBUG::Sun Jun 02 15:32:41 MUT
2019::com.biglybt.core.util.ThreadPool::checkWarning::357:
[15:32:41] [stderr]   Thread pool 'Simple Timer' is full
(busy=Device:gc,Device:gc,Device:gc,Device:gc)
[15:32:41] [stderr]     ThreadPool::run::239, ThreadPool::run::206,
Timer::runSupport::231, AERunnable::run::36, Thread::run::748
[15:34:17] [stderr] DEBUG::Sun Jun 02 15:34:17 MUT
2019::com.biglybt.core.networkmanager.impl.tcp.TCPTransportHelper::setScatte
ringMode::636:
[15:34:17] [stderr]   java.net.SocketException: Invalid argument
    at sun.nio.ch.Net.setIntOption0(Native Method)
    at sun.nio.ch.Net.setSocketOption(Net.java:334)
    at sun.nio.ch.SocketChannelImpl.setOption(SocketChannelImpl.java:190)
    at sun.nio.ch.SocketAdaptor.setBooleanOption(SocketAdaptor.java:271)
    at sun.nio.ch.SocketAdaptor.setTcpNoDelay(SocketAdaptor.java:306)
    at 
com.biglybt.core.networkmanager.impl.tcp.TCPTransportHelper.setScatteringMod
e(TCPTransportHelper.java:633)
    at 
com.biglybt.core.networkmanager.impl.ProtocolDecoderPHE.<init>(ProtocolDecod
erPHE.java:372)
    at 
com.biglybt.core.networkmanager.impl.ProtocolDecoderInitial.decodePHE(Protoc
olDecoderInitial.java:254)
    at 
com.biglybt.core.networkmanager.impl.ProtocolDecoderInitial.<init>(ProtocolD
ecoderInitial.java:84)
    at 
com.biglybt.core.networkmanager.impl.TransportCryptoManager.manageCrypto(Tra
nsportCryptoManager.java:45)
    at 
com.biglybt.core.networkmanager.impl.tcp.TCPTransportImpl.handleCrypto(TCPTr
ansportImpl.java:429)
    at 
com.biglybt.core.networkmanager.impl.tcp.TCPTransportImpl$1.connectSuccess(T
CPTransportImpl.java:391)
    at 
com.biglybt.core.networkmanager.impl.tcp.TCPConnectionManager.finishConnect(
TCPConnectionManager.java:587)
    at 
com.biglybt.core.networkmanager.impl.tcp.TCPConnectionManager$8.selectSucces
s(TCPConnectionManager.java:468)
    at 
com.biglybt.core.networkmanager.VirtualChannelSelector.selectSuccess(Virtual
ChannelSelector.java:170)
    at 
com.biglybt.core.networkmanager.impl.tcp.VirtualChannelSelectorImpl.select(V
irtualChannelSelectorImpl.java:938)
    at 
com.biglybt.core.networkmanager.VirtualChannelSelector.select(VirtualChannel
Selector.java:143)
    at 
com.biglybt.core.networkmanager.impl.tcp.TCPConnectionManager.runSelect(TCPC
onnectionManager.java:677)
    at 
com.biglybt.core.networkmanager.impl.tcp.TCPConnectionManager$7.run(TCPConne
ctionManager.java:281)
    at com.biglybt.core.util.AEThread2$threadWrapper.run(AEThread2.java:304)
[15:34:17] [stderr]
[15:35:03] [stderr] DEBUG::Sun Jun 02 15:35:03 MUT
2019::com.biglybt.core.networkmanager.impl.tcp.ProxyLoginHandler::readConfig
::88:
[15:35:03] [stderr]   java.lang.NumberFormatException: For input string:
"3129, 8080, 81"
    at 
java.lang.NumberFormatException.forInputString(NumberFormatException.java:65
)
    at java.lang.Integer.parseInt(Integer.java:580)
    at java.lang.Integer.parseInt(Integer.java:615)
    at 
com.biglybt.core.networkmanager.impl.tcp.ProxyLoginHandler.readConfig(ProxyL
oginHandler.java:86)
    at 
com.biglybt.core.networkmanager.impl.tcp.ProxyLoginHandler$1.configurationSa
ved(ProxyLoginHandler.java:65)
    at 
com.biglybt.core.config.impl.ConfigurationManager.save(ConfigurationManager.
java:295)
    at 
com.biglybt.core.config.impl.ConfigurationManager.save(ConfigurationManager.
java:314)
    at 
com.biglybt.core.config.COConfigurationManager.save(COConfigurationManager.j
ava:526)
    at 
org.parg.azureus.plugins.networks.i2p.I2PHelperPlugin.writePluginInfo(I2PHel
perPlugin.java:2343)
    at 
org.parg.azureus.plugins.networks.i2p.I2PHelperPlugin.checkTunnelQuantities(
I2PHelperPlugin.java:2124)
    at 
org.parg.azureus.plugins.networks.i2p.I2PHelperPlugin.access$24(I2PHelperPlu
gin.java:2016)
    at 
org.parg.azureus.plugins.networks.i2p.I2PHelperPlugin$12.perform(I2PHelperPl
ugin.java:1476)
    at 
com.biglybt.core.util.TimerEventPeriodic.perform(TimerEventPeriodic.java:104
)
    at com.biglybt.core.util.TimerEvent.runSupport(TimerEvent.java:133)
    at com.biglybt.core.util.AERunnable.run(AERunnable.java:36)
    at com.biglybt.core.util.ThreadPool.runIt(ThreadPool.java:328)
    at 
com.biglybt.core.util.ThreadPool$threadPoolWorker.run(ThreadPool.java:720)
    at com.biglybt.core.util.AEThread2$threadWrapper.run(AEThread2.java:304)
[15:35:03] [stderr]
[15:36:03] [stderr] DEBUG::Sun Jun 02 15:36:03 MUT
2019::com.biglybt.core.networkmanager.impl.tcp.ProxyLoginHandler::readConfig
::88:
[15:36:03] [stderr]   java.lang.NumberFormatException: For input string:
"3129, 8080, 81"
    at 
java.lang.NumberFormatException.forInputString(NumberFormatException.java:65
)
    at java.lang.Integer.parseInt(Integer.java:580)
    at java.lang.Integer.parseInt(Integer.java:615)
    at 
com.biglybt.core.networkmanager.impl.tcp.ProxyLoginHandler.readConfig(ProxyL
oginHandler.java:86)
    at 
com.biglybt.core.networkmanager.impl.tcp.ProxyLoginHandler$1.configurationSa
ved(ProxyLoginHandler.java:65)
    at 
com.biglybt.core.config.impl.ConfigurationManager.save(ConfigurationManager.
java:295)
    at 
com.biglybt.core.config.impl.ConfigurationManager.save(ConfigurationManager.
java:314)
    at 
com.biglybt.core.config.COConfigurationManager.save(COConfigurationManager.j
ava:526)
    at 
org.parg.azureus.plugins.networks.i2p.I2PHelperPlugin.writePluginInfo(I2PHel
perPlugin.java:2343)
    at 
org.parg.azureus.plugins.networks.i2p.I2PHelperPlugin.checkTunnelQuantities(
I2PHelperPlugin.java:2124)
    at 
org.parg.azureus.plugins.networks.i2p.I2PHelperPlugin.access$24(I2PHelperPlu
gin.java:2016)
    at 
org.parg.azureus.plugins.networks.i2p.I2PHelperPlugin$12.perform(I2PHelperPl
ugin.java:1476)
    at 
com.biglybt.core.util.TimerEventPeriodic.perform(TimerEventPeriodic.java:104
)
    at com.biglybt.core.util.TimerEvent.runSupport(TimerEvent.java:133)
    at com.biglybt.core.util.AERunnable.run(AERunnable.java:36)
    at com.biglybt.core.util.ThreadPool.runIt(ThreadPool.java:328)
    at 
com.biglybt.core.util.ThreadPool$threadPoolWorker.run(ThreadPool.java:720)
    at com.biglybt.core.util.AEThread2$threadWrapper.run(AEThread2.java:304)
[15:36:03] [stderr]

**Comment by parg** [comment]
Not that it is related to your issue but you have configured your proxy wrongly under Tools->Options->Connection->Proxy - only a single port number is supported but you have "3129, 8080, 81". Not sure how you managed to enter that.

Any chance of a screenshot of the hard-to-read text so I know exactly what you're talking about?

**Comment by TheScottMan** [comment]
here's the screenshot showing the white text...


and here's the progress bar not updating with color...


regarding the weird proxy settings... all tick boxes in the proxy settings
are off so I guess I'm not using proxy anyway?

Thanks for checking into all this... for now I will attempt to downgrade the
installation and see what happens

**Comment by parg** [comment]
Hmm, screenshot never made it through!

**Comment by TheScottMan** [comment]
sending again as attachments...

**Comment by parg** [comment]
Think you'll need to go to https://github.com/BiglySoftware/BiglyBT/issues/1091 and drag+drop to attach as files

**Comment by TheScottMan** [comment]
here's the screenshot showing the white text...
￼
![image](https://user-images.githubusercontent.com/28532701/58763776-7e1a6080-8570-11e9-9df2-c3d736328480.png)


and here's the progress bar not updating with color...
￼
![image](https://user-images.githubusercontent.com/28532701/58763773-73f86200-8570-11e9-97ac-c54888188d10.png)

**Comment by TheScottMan** [comment]
btw I downgraded to previous version and everything back to normal.... some weird change in the update?

**Comment by actricom** [comment]
I can't see anything about UI in the logs, but there's lots about Java. Until last week, I only had 32-bit Java installed, but then added the 64-bit version too - I don't know if that has anything to do with it?

[debug_1.log](https://github.com/BiglySoftware/BiglyBT/files/3245056/debug_1.log)
[debug_2.log](https://github.com/BiglySoftware/BiglyBT/files/3245057/debug_2.log)
![NoProgress](https://user-images.githubusercontent.com/36631004/58765559-237f0580-856c-11e9-8427-fc8dd936ed7c.png)

**Comment by parg** [comment]
Java version shouldn't make any difference. Does the progress bar go green when 100% complete?

**Comment by TuxPaper** [comment]
Can you check/fiddle with your Color Scheme colors?  The bug might be with the Progress Bar color setting.  There's a Reset Color button that may be enabled, and pressing it might get the color back.  Otherwise, changing the color to something and back again might trigger happiness.

![image](https://user-images.githubusercontent.com/725353/58766100-b188cb00-852f-11e9-9d0e-901543c8df6a.png)

**Comment by actricom** [comment]
> Java version shouldn't make any difference. Does the progress bar go green when 100% complete?

No, the bar never fills even at 100%.

**Comment by actricom** [comment]
> Can you check/fiddle with your Color Scheme colors?  The bug might be with the Progress Bar color setting.  There's a Reset Color button that may be enabled, and pressing it might get the color back.  Otherwise, changing the color to something and back again might trigger happiness.

I've tried changing the color and pressing the reset and neither has cured it.

**Comment by TuxPaper** [comment]
I've been able to reproduce the color issue by unchecking "Start UI before Core Initialization" in Options->Interface->Start

**Comment by TuxPaper** [comment]
Next beta should have the color fixed.  Thanks for working with us while we tried to figure out what I did wrong :)

**Comment by actricom** [comment]
> I've been able to reproduce the color issue by unchecking "Start UI before Core Initialization" in Options->Interface->Start

Thanks guys. I can confirm that my "Start UI before Core Initialization" is also unticked. I don't know what that does, but it sounds like something you wouldn't really want to do?

**Comment by parg** [comment]
B03 with the fix is now available, see the Help menu -> Join Beta Program to obtain beta releases.
