### ISSUE TITLE
EOF Exception

### ISSUE THREAD

**Issue by gh338** [BiglySoftware/BiglyBT#1155]
Getting this exception for about a year now in the i2p java router

PM ERROR [Reader 62056] ent.ClientMessageEventListener: Error occurred
     java.io.EOFException: EOF reading 4 byte value
     at net.i2p.data.DataHelper.readLong(DataHelper.java:665)
     at net.i2p.data.i2cp.I2CPMessageHandler.readMessage(I2CPMessageHandler.java:43)
     at net.i2p.data.i2cp.I2CPMessageReader$I2CPMessageReaderRunner.run2(I2CPMessageReader.java:182)
     at net.i2p.data.i2cp.I2CPMessageReader$I2CPMessageReaderRunner.run(I2CPMessageReader.java:164)
     at java.base/java.lang.Thread.run(Thread.java:834)
     at net.i2p.util.I2PThread.run(I2PThread.java:103)

**Comment by parg** [comment]
You'd need to report that to the I2P project...  https://i2pforum.net/
