### ISSUE TITLE
BiglyBT fails to start with 'C:\Users\[user]\.swt\lib\win32\x86_64\swt-win32-4922r17.dll: Can't find dependent libraries'

### ISSUE THREAD

**Issue by rekabis** [BiglySoftware/BiglyBT#1185]
* Windows 10 pro 1903
* BiglyBT v2.0

Exactly what it says on the tin. _About_ the same time as I upgraded Windows 10 to 1903, BiglyBT suddenly ceased to function correctly. When I try to launch it, I can see it appear in the Details tab of the Task Manager for a few short seconds, and then it crashes.

The debug1.log file is as follows:

```
[2019-08-01, 10:38 p.m.] Log File Opened for BiglyBT 2.0.0.0
[22:38:03] [stderr] DEBUG::Thu Aug 01 22:38:03 PDT 2019::com.biglybt.core.config.COConfigurationManager::addAndFireParameterListener::605:
[22:38:03] [stderr]   Failed to update 'preferIPv6Address'
[22:38:03] [stderr]     ConfigurationChecker::setSystemProperties::103, ConfigurationManager::initialise::177, ConfigurationManager::getInstance::110, COConfigurationManager::initialise::265, CoreImpl::<init>::256, CoreImpl::create::170, CoreFactory::create::43, Main::main::192, NativeMethodAccessorImpl::invoke0::-2, NativeMethodAccessorImpl::invoke::62, DelegatingMethodAccessorImpl::invoke::43, Method::invoke::567, MainExecutor$1::run::37, Thread::run::835
[22:38:03] [stderr] java.lang.IllegalArgumentException: Can not set static final int field java.net.InetAddress.preferIPv6Address to (boolean)true
[22:38:03] [stderr] 	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
[22:38:03] [stderr] 	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:175)
[22:38:03] [stderr] 	at java.base/jdk.internal.reflect.UnsafeQualifiedStaticIntegerFieldAccessorImpl.setBoolean(UnsafeQualifiedStaticIntegerFieldAccessorImpl.java:104)
[22:38:03] [stderr] 	at java.base/java.lang.reflect.Field.setBoolean(Field.java:816)
[22:38:03] [stderr] 	at com.biglybt.core.config.impl.ConfigurationChecker$1.parameterChanged(ConfigurationChecker.java:137)
[22:38:03] [stderr] 	at com.biglybt.core.config.COConfigurationManager.addAndFireParameterListener(COConfigurationManager.java:605)
[22:38:03] [stderr] 	at com.biglybt.core.config.impl.ConfigurationChecker.setSystemProperties(ConfigurationChecker.java:103)
[22:38:03] [stderr] 	at com.biglybt.core.config.impl.ConfigurationManager.initialise(ConfigurationManager.java:177)
[22:38:03] [stderr] 	at com.biglybt.core.config.impl.ConfigurationManager.getInstance(ConfigurationManager.java:110)
[22:38:03] [stderr] 	at com.biglybt.core.config.COConfigurationManager.initialise(COConfigurationManager.java:265)
[22:38:03] [stderr] 	at com.biglybt.core.impl.CoreImpl.<init>(CoreImpl.java:256)
[22:38:03] [stderr] 	at com.biglybt.core.impl.CoreImpl.create(CoreImpl.java:170)
[22:38:03] [stderr] 	at com.biglybt.core.CoreFactory.create(CoreFactory.java:43)
[22:38:03] [stderr] 	at com.biglybt.ui.Main.main(Main.java:192)
[22:38:03] [stderr] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:38:03] [stderr] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[22:38:03] [stderr] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:38:03] [stderr] 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[22:38:03] [stderr] 	at com.biglybt.launcher.MainExecutor$1.run(MainExecutor.java:37)
[22:38:03] [stderr] 	at java.base/java.lang.Thread.run(Thread.java:835)
[22:38:03] java.lang.IllegalArgumentException: Can not set static final int field java.net.InetAddress.preferIPv6Address to (boolean)true
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:175)
	at java.base/jdk.internal.reflect.UnsafeQualifiedStaticIntegerFieldAccessorImpl.setBoolean(UnsafeQualifiedStaticIntegerFieldAccessorImpl.java:104)
	at java.base/java.lang.reflect.Field.setBoolean(Field.java:816)
	at com.biglybt.core.config.impl.ConfigurationChecker$1.parameterChanged(ConfigurationChecker.java:137)
	at com.biglybt.core.config.COConfigurationManager.addAndFireParameterListener(COConfigurationManager.java:605)
	at com.biglybt.core.config.impl.ConfigurationChecker.setSystemProperties(ConfigurationChecker.java:103)
	at com.biglybt.core.config.impl.ConfigurationManager.initialise(ConfigurationManager.java:177)
	at com.biglybt.core.config.impl.ConfigurationManager.getInstance(ConfigurationManager.java:110)
	at com.biglybt.core.config.COConfigurationManager.initialise(COConfigurationManager.java:265)
	at com.biglybt.core.impl.CoreImpl.<init>(CoreImpl.java:256)
	at com.biglybt.core.impl.CoreImpl.create(CoreImpl.java:170)
	at com.biglybt.core.CoreFactory.create(CoreFactory.java:43)
	at com.biglybt.ui.Main.main(Main.java:192)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at com.biglybt.launcher.MainExecutor$1.run(MainExecutor.java:37)
	at java.base/java.lang.Thread.run(Thread.java:835)

[22:38:04] [stderr] Invoking main failed
[22:38:04] [stderr] java.lang.reflect.InvocationTargetException
[22:38:04] [stderr] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:38:04] [stderr] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[22:38:04] [stderr] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:38:04] [stderr] 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[22:38:04] [stderr] 	at com.biglybt.launcher.MainExecutor$1.run(MainExecutor.java:37)
[22:38:04] [stderr] 	at java.base/java.lang.Thread.run(Thread.java:835)
[22:38:04] [stderr] Caused by: java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
	no swt-win32-4922r17 in java.library.path: [C:\Program Files\BiglyBT\.\., C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler, C:\Program Files\Microsoft MPI\Bin\, C:\Program Files (x86)\Common Files\Oracle\Java\javapath, C:\WINDOWS\system32, C:\WINDOWS, C:\WINDOWS\System32\Wbem, C:\WINDOWS\System32\WindowsPowerShell\v1.0\, C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR, C:\WINDOWS\system32, C:\WINDOWS, C:\WINDOWS\System32\Wbem, C:\WINDOWS\System32\WindowsPowerShell\v1.0\, C:\WINDOWS\System32\OpenSSH\, C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\, C:\Program Files\Microsoft SQL Server\100\Tools\Binn\, C:\Program Files\Microsoft SQL Server\100\DTS\Binn\, C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\VSShell\Common7\IDE\, C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\IDE\PrivateAssemblies\, C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\, C:\Program Files\Microsoft SQL Server\110\DTS\Binn\, C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\, C:\Program Files\Microsoft SQL Server\110\Tools\Binn\, C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\, C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE\PrivateAssemblies\, C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\, C:\Program Files\Microsoft SQL Server\120\DTS\Binn\, C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\, C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\, C:\Program Files\Microsoft SQL Server\120\Tools\Binn\, C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\, C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\, C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\, C:\Program Files\Microsoft SQL Server\130\Tools\Binn\, C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\, C:\Program Files\Microsoft SQL Server\130\DTS\Binn\, C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\, C:\Program Files\dotnet\, C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\, C:\Program Files\Git\cmd, C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\, C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common, C:\Program Files\Microsoft\Web Platform Installer\, C:\Users\RenÃ© KÃ¥bis\AppData\Local\Microsoft\WindowsApps, ., c:\program files\java\jdk-12.0.1\bin]
	no swt-win32 in java.library.path: [C:\Program Files\BiglyBT\.\., C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler, C:\Program Files\Microsoft MPI\Bin\, C:\Program Files (x86)\Common Files\Oracle\Java\javapath, C:\WINDOWS\system32, C:\WINDOWS, C:\WINDOWS\System32\Wbem, C:\WINDOWS\System32\WindowsPowerShell\v1.0\, C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR, C:\WINDOWS\system32, C:\WINDOWS, C:\WINDOWS\System32\Wbem, C:\WINDOWS\System32\WindowsPowerShell\v1.0\, C:\WINDOWS\System32\OpenSSH\, C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\, C:\Program Files\Microsoft SQL Server\100\Tools\Binn\, C:\Program Files\Microsoft SQL Server\100\DTS\Binn\, C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\VSShell\Common7\IDE\, C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\IDE\PrivateAssemblies\, C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\, C:\Program Files\Microsoft SQL Server\110\DTS\Binn\, C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\, C:\Program Files\Microsoft SQL Server\110\Tools\Binn\, C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\, C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE\PrivateAssemblies\, C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\, C:\Program Files\Microsoft SQL Server\120\DTS\Binn\, C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\, C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\, C:\Program Files\Microsoft SQL Server\120\Tools\Binn\, C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\, C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\, C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\, C:\Program Files\Microsoft SQL Server\130\Tools\Binn\, C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\, C:\Program Files\Microsoft SQL Server\130\DTS\Binn\, C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\, C:\Program Files\dotnet\, C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\, C:\Program Files\Git\cmd, C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\, C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common, C:\Program Files\Microsoft\Web Platform Installer\, C:\Users\[user]\AppData\Local\Microsoft\WindowsApps, ., c:\program files\java\jdk-12.0.1\bin]
	C:\Users\[user]\.swt\lib\win32\x86_64\swt-win32-4922r17.dll: Can't find dependent libraries
	Can't load library: C:\Users\[user]\.swt\lib\win32\x86_64\swt-win32.dll
[22:38:04] [stderr] 
[22:38:04] [stderr] 	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:330)
[22:38:04] [stderr] 	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:242)
[22:38:04] [stderr] 	at org.eclipse.swt.internal.C.<clinit>(C.java:19)
[22:38:04] [stderr] 	at org.eclipse.swt.widgets.Display.<clinit>(Display.java:142)
[22:38:04] [stderr] 	at com.biglybt.ui.swt.mainwindow.SWTThread.<init>(SWTThread.java:81)
[22:38:04] [stderr] 	at com.biglybt.ui.swt.mainwindow.SWTThread.createInstance(SWTThread.java:60)
[22:38:04] [stderr] 	at com.biglybt.ui.swt.Initializer.<init>(Initializer.java:179)
[22:38:04] [stderr] 	at com.biglybt.ui.swt.UI.takeMainThread(UI.java:110)
[22:38:04] [stderr] 	at com.biglybt.ui.Main.main(Main.java:239)
[22:38:04] [stderr] 	... 6 more
```

**Comment by parg** [comment]
Hi,
Can you try installing BiglyBT again? Don't uninstall the previous version, just grab a new installer from https://www.biglybt.com/ and install it.
Thanks

**Comment by parg** [comment]
If that doesn't work then please download this file

[swt.zip](https://github.com/BiglySoftware/BiglyBT/files/3460259/swt.zip)

unzip it to get the 'swt.jar' and then replace the swt.jar in your BiglyBT installation folder with this updated one.

**Comment by parg** [comment]
(changed the title as the IPv6 one is a distraction from your real issue)

**Comment by rekabis** [comment]
Unfortunately, neither option worked.

I had tried a re-installation of the latest downloadable prior to creating this thread (apologies for not mentioning it), and I just tried out your swt.jar file, to no effect. BiglyBT still launches, then crashes within 3-5 seconds without providing any visual indication.

The log switched from debug_1.log to debug_2.log. It was functionally identical to yesterday's log entry, except that it was longer by this content:

```
[22:42:40] [stderr] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[22:42:40] [stderr] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:42:40] [stderr] 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[22:42:40] [stderr] 	at com.biglybt.launcher.MainExecutor$1.run(MainExecutor.java:37)
[22:42:40] [stderr] 	at java.base/java.lang.Thread.run(Thread.java:835)
[22:42:40] [stderr] Caused by: java.lang.UnsatisfiedLinkError: org.eclipse.swt.internal.C.PTR_sizeof()I
[22:42:40] [stderr] 	at org.eclipse.swt.internal.C.PTR_sizeof(Native Method)
[22:42:40] [stderr] 	at org.eclipse.swt.internal.C.<clinit>(C.java:22)
[22:42:40] [stderr] 	at org.eclipse.swt.widgets.Display.<clinit>(Display.java:143)
[22:42:40] [stderr] 	at com.biglybt.ui.swt.mainwindow.SWTThread.<init>(SWTThread.java:81)
[22:42:40] [stderr] 	at com.biglybt.ui.swt.mainwindow.SWTThread.createInstance(SWTThread.java:60)
[22:42:40] [stderr] 	at com.biglybt.ui.swt.Initializer.<init>(Initializer.java:179)
[22:42:40] [stderr] 	at com.biglybt.ui.swt.UI.takeMainThread(UI.java:110)
[22:42:40] [stderr] 	at com.biglybt.ui.Main.main(Main.java:239)
[22:42:40] [stderr] 	... 6 more
```
As in, aside from the timestamps, take yesterday's content and tack this onto the end of it.

**Comment by parg** [comment]
There's https://www-01.ibm.com/support/docview.wss?uid=ibm10874514

**Comment by rekabis** [comment]
Good catch, but nope; I don’t run _any_ Citrix product on my home machine.

**Comment by rekabis** [comment]
Suggestions? I am still unable to run BiglyBT.

**Comment by parg** [comment]
You could try installing the DLL dependency viewer from

https://github.com/lucasg/Dependencies/releases

Then find the swt.jar in the BiglyBT installation folder and extract the 4 DLLS in it to a local folder. You can then launch the dependencies GUI (DependenciesGui.exe) and drag the DLL with the missing dependency error onto it to see if anything shows up

**Comment by rekabis** [comment]
The only thing that shows up with any sort of an error using this dependency viewer is `jawt.dll`, and that is in swt-awt-win32.4926r21.dll

**Comment by parg** [comment]
I have a couple Win 10 that have upgraded to 1903 and I don't see the problem :( There must be something about your environment that differs from mine but I can't think what it can be. Once Win 10 is pretty basic, only used for testing, so I can't have installed that much other stuff that might have possibly brought in the missing dependency :(

**Comment by rekabis** [comment]
Uninstalled all versions of Java, reinstalled JDK 8, first 64-bit then 32-bit, same errors in both cases.

**Comment by rekabis** [comment]
Also uninstalled then reinstalled BiglyBT, no change.

**Comment by parg** [comment]
Can you create a user on your computer with just ASCII  characters in the username and see if that user has issues with BiglyBT?

**Comment by TuxPaper** [comment]
You can also try extracting the `.dll` files from the swt.jar into the same directory as the swt.jar.  It might pick it up (I haven't tested it in a while).  If you copy swt.jar to swt.jar.zip, you can use explorer to get to the files (or just use a zip tool)

**Comment by rekabis** [comment]
@parg Okay, WTF? I unlocked the Admin account, slapped a password onto it, logged into it, and BiglyBT worked just fine. Switch back to my account, and it fails to run. And this is _after_ copying over the `.swt` directory’s contents.

I have examined my environment variables, directory permisions on `.swt`, and nothing seems to be materially different.

> with just ASCII characters in the username

Are we really talking about a UTF-8 support issue in 2019?

**Comment by parg** [comment]
aha! Well we (i.e. our code) did have issues with non-ASCII back in the 1800s but we pretty much fixed that. It can't be a general unicode issue, must be something specific to your user.

Does your username have punctuation in it? For example, semicolon, exclamation mark, question mark, forward slash? I know those can confuse code that it trying to decode jar file URIs (e.g. https://stackoverflow.com/questions/8014099/how-do-i-convert-a-jarfile-uri-to-the-path-of-jar-file)

Also, when you say you copied the .swt contents, did you place those 4 swt DLLs into C:\Program Files\BiglyBT (or the equivalent)? You *might* also have to remove those .dlls from C:\Program Files\BiglyBT\swt.jar as well.

**Comment by rekabis** [comment]
The only thing unusual in my username path is an é and an å, and both of those have been there for the last 15  years of Windows installations, including innumerable Azureus/Vuze installations and the last few BiglyBT installations. So I am unsure as to how it could be suddenly affecting this current install.

**Comment by rekabis** [comment]
Okay, putting the 4 DLLs into the BiglyBT program dir is what did it, but _only_ when I removed those same 4 DLLs from the swt.jar as well. So technically: this is what got me up and running.

Also, my normal username path has a space between the first and last names. Although I highly doubt that this is what buggers things up. Aside from the é and å in the username, this is a completely normal name.

**Comment by parg** [comment]
heh, got there in the end! I suppose it is something to do with the SWT library attempting to extract those DLLs into a temporary folder and load them from there (and failing to do so) as opposed to assuming they're already on the library path when not in the .jar. 

I'll try creating a user name with your chars and a space on a VM and see if it fails.

**Comment by parg** [comment]
Created a user called 

éFé åFå

works fine :(

**Comment by rekabis** [comment]
FYI, similar problem again with a fresh installation of Windows 10 21H2 and the _very latest_ version of BiglyBT v2.9.0.0 64-bit downloaded from the website.

This time, the log file had something a wee different:

````
[1/21/22 11:30 PM] Log File Opened for BiglyBT 2.9.0.0
[23:30:25] [stderr] Launch failed
[23:30:25] [stderr] java.lang.reflect.InvocationTargetException
[23:30:25] [stderr] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:30:25] [stderr] 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[23:30:25] [stderr] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[23:30:25] [stderr] 	at java.lang.reflect.Method.invoke(Unknown Source)
[23:30:25] [stderr] 	at com.biglybt.launcher.Launcher$1.run(Launcher.java:48)
[23:30:25] [stderr] 	at java.lang.Thread.run(Unknown Source)
[23:30:25] [stderr] Caused by: java.lang.UnsatisfiedLinkError: org.eclipse.swt.internal.win32.OS.CreateActCtx(Lorg/eclipse/swt/internal/win32/ACTCTX;)J
[23:30:25] [stderr] 	at org.eclipse.swt.internal.win32.OS.CreateActCtx(Native Method)
[23:30:25] [stderr] 	at org.eclipse.swt.internal.win32.OS.<clinit>(OS.java:54)
[23:30:25] [stderr] 	at org.eclipse.swt.widgets.Display.<clinit>(Display.java:146)
[23:30:25] [stderr] 	at com.biglybt.ui.swt.mainwindow.SWTThread.<init>(SWTThread.java:81)
[23:30:25] [stderr] 	at com.biglybt.ui.swt.mainwindow.SWTThread.createInstance(SWTThread.java:58)
[23:30:25] [stderr] 	at com.biglybt.ui.swt.Initializer.<init>(Initializer.java:181)
[23:30:25] [stderr] 	at com.biglybt.ui.swt.UI.takeMainThread(UI.java:136)
[23:30:25] [stderr] 	at com.biglybt.ui.Main.main(Main.java:247)
[23:30:25] [stderr] 	... 6 more
[23:30:25] [stderr] Exception in thread "BiglyBT" java.lang.SecurityException: VM exit operation prohibited
[23:30:25] [stderr] 	at com.biglybt.core.security.impl.SESecurityManagerImpl$ClientSecurityManager.checkExit(SESecurityManagerImpl.java:1881)
[23:30:25] [stderr] 	at java.lang.Runtime.exit(Unknown Source)
[23:30:25] [stderr] 	at java.lang.System.exit(Unknown Source)
[23:30:25] [stderr] 	at com.biglybt.launcher.Launcher$1.run(Launcher.java:56)
[23:30:25] [stderr] 	at java.lang.Thread.run(Unknown Source)
````

But it ended up having the same resolution: extract the four swt dll files from the `swt.jar` file in the root of the BiglyBT install directory.

Note to anyone else: you need to launch 7zip as an admin first, then navigate to that folder. Unfortunately, 7zip does not have "open in 7zip as an admin" in Windows Explorer's right-click menu.

**Comment by parg** [comment]
darn it, why can't these bug solve themselves!

**Comment by rekabis** [comment]
FYI, this problem still exists in 2024, on a totally clean install of Windows 11 23H2 build 22631.3447, and _WITHOUT_ a user profile path that includes anything from the UTF-8 character set.

As in, my user profile name is simply “development”.

Here is the log error, for reference:

```
[2024-04-18 14:06] Log File Opened for BiglyBT 3.5.0.0
[14:06:53] [stderr] Launch failed
[14:06:53] [stderr] java.lang.reflect.InvocationTargetException
[14:06:53] [stderr] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
[14:06:53] [stderr] 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[14:06:53] [stderr] 	at com.biglybt.launcher.Launcher$1.run(Launcher.java:48)
[14:06:53] [stderr] 	at java.base/java.lang.Thread.run(Thread.java:1583)
[14:06:53] [stderr] Caused by: java.lang.UnsatisfiedLinkError: 'long org.eclipse.swt.internal.win32.OS.CreateActCtx(org.eclipse.swt.internal.win32.ACTCTX)'
[14:06:53] [stderr] 	at org.eclipse.swt.internal.win32.OS.CreateActCtx(Native Method)
[14:06:53] [stderr] 	at org.eclipse.swt.internal.win32.OS.<clinit>(OS.java:54)
[14:06:53] [stderr] 	at org.eclipse.swt.widgets.Display.<clinit>(Display.java:146)
[14:06:53] [stderr] 	at com.biglybt.ui.swt.mainwindow.SWTThread.<init>(SWTThread.java:85)
[14:06:53] [stderr] 	at com.biglybt.ui.swt.mainwindow.SWTThread.createInstance(SWTThread.java:58)
[14:06:53] [stderr] 	at com.biglybt.ui.swt.Initializer.<init>(Initializer.java:183)
[14:06:53] [stderr] 	at com.biglybt.ui.swt.UI.takeMainThread(UI.java:162)
[14:06:53] [stderr] 	at com.biglybt.ui.Main.main(Main.java:247)
[14:06:53] [stderr] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[14:06:53] [stderr] 	... 3 more
```

I will be trying out the swt.jar trick later today.
