### ISSUE TITLE
Error (message from previous close of biglyBT)

### ISSUE THREAD

**Issue by newgithubuser2019** [BiglySoftware/BiglyBT#1237]
An unhandled error occurred in the gui further errors may be reported. After clicking "view details":

java.lang.NullPointerException
	at org.eclipse.swt.widgets.Display.filterMessage(Display.java:1207)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3544)
	at com.biglybt.ui.swt.mainwindow.SWTThread.<init>(SWTThread.java:286)
	at com.biglybt.ui.swt.mainwindow.SWTThread.createInstance(SWTThread.java:56)
	at com.biglybt.ui.swt.Initializer.<init>(Initializer.java:179)
	at com.biglybt.ui.swt.UI.takeMainThread(UI.java:136)
	at com.biglybt.ui.Main.main(Main.java:239)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.biglybt.launcher.Launcher$1.run(Launcher.java:48)
	at java.lang.Thread.run(Unknown Source)
_________________________________________________________________________________________________
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4922, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.0.0.1_B38/4 az3

**Comment by parg** [comment]
SWT graphics library internal error that one - get them sometimes on closdown but not much we can do about them :(
