### ISSUE TITLE
Bigly client can not start on ubuntu 19.10 x64 with kde 5.17

### ISSUE THREAD

**Issue by ghost** [BiglySoftware/BiglyBT#1322]
$ ./biglybt
Starting BiglyBT...
Suitable java version found [java = openjdk 1.8.0_232-ea]
Using swt/swt-x86_64.jar v4.924
Loading BiglyBT:
changeLocale: *Default Language* != English (United States). Searching without country..
changeLocale: Searching for language English in *any* country..
changeLocale: no message properties for Locale 'English (United States)' (en_US), using 'English (default)'
UIFunctions/ImageLoad took 0ms
new shell took 51ms
new shell setup took 25ms
```
skin init took 50ms
MainMenu init took 25ms
pre skin widgets init took 25ms
skin widgets (1/2) init took 50ms
skin widgets (2/2) init took 51ms
pre SWTInstance init took 0ms
Init Core Columns took 50ms
SWTInstance init took 0ms
DEBUG::Thu Oct 31 18:08:24 CST 2019::com.biglybt.core.util.DebugLight::printStackTrace::35:
  java.lang.IllegalArgumentException: Argument not valid
        at org.eclipse.swt.SWT.error(SWT.java:4680)
        at org.eclipse.swt.SWT.error(SWT.java:4614)
        at org.eclipse.swt.SWT.error(SWT.java:4585)
        at org.eclipse.swt.graphics.FontData.setHeight(FontData.java:343)
        at com.biglybt.ui.swt.utils.FontUtils.setFontDataHeight(FontUtils.java:94)
        at com.biglybt.ui.swt.utils.FontUtils.ensureFontFitsHeight(FontUtils.java:299)
        at com.biglybt.ui.swt.utils.FontUtils.access$0(FontUtils.java:287)
        at com.biglybt.ui.swt.utils.FontUtils$2.handleEvent(FontUtils.java:262)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
        at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5783)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1411)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1437)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1416)
        at org.eclipse.swt.widgets.Control.setBounds(Control.java:1266)
        at org.eclipse.swt.widgets.Control.setBounds(Control.java:1006)
        at org.eclipse.swt.layout.FormLayout.layout(FormLayout.java:364)
        at org.eclipse.swt.layout.FormLayout.layout(FormLayout.java:292)
        at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1799)
        at org.eclipse.swt.widgets.Composite.setBounds(Composite.java:1587)
        at org.eclipse.swt.widgets.Control.setBounds(Control.java:1006)
        at org.eclipse.swt.layout.FormLayout.layout(FormLayout.java:364)
        at org.eclipse.swt.layout.FormLayout.layout(FormLayout.java:292)
        at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1799)
        at org.eclipse.swt.widgets.Composite.setBounds(Composite.java:1587)
        at org.eclipse.swt.widgets.Control.setBounds(Control.java:1006)
        at org.eclipse.swt.layout.FormLayout.layout(FormLayout.java:364)
        at org.eclipse.swt.layout.FormLayout.layout(FormLayout.java:292)
        at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1799)
        at org.eclipse.swt.widgets.Composite.setBounds(Composite.java:1587)
        at org.eclipse.swt.widgets.Control.setBounds(Control.java:1006)
        at org.eclipse.swt.layout.FormLayout.layout(FormLayout.java:364)
        at org.eclipse.swt.layout.FormLayout.layout(FormLayout.java:292)
        at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1799)
        at org.eclipse.swt.widgets.Composite.setBounds(Composite.java:1587)
        at org.eclipse.swt.widgets.Control.setBounds(Control.java:1006)
        at org.eclipse.swt.layout.FormLayout.layout(FormLayout.java:364)
        at org.eclipse.swt.layout.FormLayout.layout(FormLayout.java:292)
        at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1799)
        at org.eclipse.swt.widgets.Composite.setBounds(Composite.java:1587)
        at org.eclipse.swt.widgets.Control.setBounds(Control.java:1006)
        at org.eclipse.swt.layout.FormLayout.layout(FormLayout.java:364)
        at org.eclipse.swt.layout.FormLayout.layout(FormLayout.java:292)
        at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1799)
        at org.eclipse.swt.widgets.Composite.setBounds(Composite.java:1587)
        at org.eclipse.swt.widgets.Control.setBounds(Control.java:1006)
        at org.eclipse.swt.layout.FormLayout.layout(FormLayout.java:364)
        at org.eclipse.swt.layout.FormLayout.layout(FormLayout.java:292)
        at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1799)
        at org.eclipse.swt.widgets.Composite.setBounds(Composite.java:1587)
        at org.eclipse.swt.widgets.Control.setBounds(Control.java:1006)
        at org.eclipse.swt.layout.FormLayout.layout(FormLayout.java:364)
        at org.eclipse.swt.layout.FormLayout.layout(FormLayout.java:292)
        at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1799)
        at org.eclipse.swt.widgets.Composite.layout(Composite.java:1108)
        at com.biglybt.ui.swt.skin.SWTSkinObjectBasic$5.runSupport(SWTSkinObjectBasic.java:553)
        at com.biglybt.core.util.AERunnable.run(AERunnable.java:36)
        at com.biglybt.ui.swt.Utils.execSWTThread(Utils.java:916)
        at com.biglybt.ui.swt.Utils.execSWTThread(Utils.java:1082)
        at com.biglybt.ui.swt.skin.SWTSkinObjectBasic.setVisible(SWTSkinObjectBasic.java:521)
        at com.biglybt.ui.swt.skin.SWTSkinUtils.setVisibility(SWTSkinUtils.java:229)
        at com.biglybt.ui.swt.skin.SWTSkinUtils.setVisibility(SWTSkinUtils.java:166)
        at com.biglybt.ui.swt.shells.main.MainWindowImpl.setVisible(MainWindowImpl.java:2321)
        at com.biglybt.ui.swt.shells.main.MainWindowImpl.createWindow(MainWindowImpl.java:762)
        at com.biglybt.ui.swt.shells.main.MainWindowImpl.access$2(MainWindowImpl.java:462)
        at com.biglybt.ui.swt.shells.main.MainWindowImpl$2.runWithDisplay(MainWindowImpl.java:233)
        at com.biglybt.ui.swt.utils.SWTRunnable.run(SWTRunnable.java:37)
        at com.biglybt.ui.swt.Utils.execSWTThread(Utils.java:916)
        at com.biglybt.ui.swt.Utils.execSWTThread(Utils.java:1082)
        at com.biglybt.ui.swt.shells.main.MainWindowImpl.<init>(MainWindowImpl.java:228)
        at com.biglybt.ui.swt.shells.main.MainWindowFactory.createAsync(MainWindowFactory.java:62)
        at com.biglybt.ui.swt.Initializer.runInSWTThread(Initializer.java:277)
        at com.biglybt.ui.swt.mainwindow.SWTThread.<init>(SWTThread.java:272)
        at com.biglybt.ui.swt.mainwindow.SWTThread.createInstance(SWTThread.java:56)
        at com.biglybt.ui.swt.Initializer.<init>(Initializer.java:179)
        at com.biglybt.ui.swt.UI.takeMainThread(UI.java:136)
        at com.biglybt.ui.Main.main(Main.java:239)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.biglybt.launcher.Launcher$1.run(Launcher.java:48)
        at java.lang.Thread.run(Thread.java:748)

[alert] Alert:3:Error Initialize MainWindow
DEBUG::Thu Oct 31 18:08:24 CST 2019::com.biglybt.ui.swt.shells.main.MainWindowImpl$2::runWithDisplay::235:
  java.lang.IllegalArgumentException: Argument not valid
        at org.eclipse.swt.SWT.error(SWT.java:4680)
        at org.eclipse.swt.SWT.error(SWT.java:4614)
        at org.eclipse.swt.SWT.error(SWT.java:4585)
        at org.eclipse.swt.graphics.FontData.setHeight(FontData.java:343)
        at com.biglybt.ui.swt.utils.FontUtils.setFontDataHeight(FontUtils.java:94)
        at com.biglybt.ui.swt.utils.FontUtils.ensureFontFitsHeight(FontUtils.java:299)
        at com.biglybt.ui.swt.utils.FontUtils.access$0(FontUtils.java:287)
        at com.biglybt.ui.swt.utils.FontUtils$2.handleEvent(FontUtils.java:262)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
        at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5783)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1411)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1437)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1416)
        at org.eclipse.swt.widgets.Control.setBounds(Control.java:1266)
        at org.eclipse.swt.widgets.Control.setBounds(Control.java:1006)
        at org.eclipse.swt.layout.FormLayout.layout(FormLayout.java:364)
        at org.eclipse.swt.layout.FormLayout.layout(FormLayout.java:292)
        at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1799)
        at org.eclipse.swt.widgets.Composite.setBounds(Composite.java:1587)
        at org.eclipse.swt.widgets.Control.setBounds(Control.java:1006)
        at org.eclipse.swt.layout.FormLayout.layout(FormLayout.java:364)
        at org.eclipse.swt.layout.FormLayout.layout(FormLayout.java:292)
        at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1799)
        at org.eclipse.swt.widgets.Composite.setBounds(Composite.java:1587)
        at org.eclipse.swt.widgets.Control.setBounds(Control.java:1006)
        at org.eclipse.swt.layout.FormLayout.layout(FormLayout.java:364)
        at org.eclipse.swt.layout.FormLayout.layout(FormLayout.java:292)
        at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1799)
        at org.eclipse.swt.widgets.Composite.setBounds(Composite.java:1587)
        at org.eclipse.swt.widgets.Control.setBounds(Control.java:1006)
        at org.eclipse.swt.layout.FormLayout.layout(FormLayout.java:364)
        at org.eclipse.swt.layout.FormLayout.layout(FormLayout.java:292)
        at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1799)
        at org.eclipse.swt.widgets.Composite.setBounds(Composite.java:1587)
        at org.eclipse.swt.widgets.Control.setBounds(Control.java:1006)
        at org.eclipse.swt.layout.FormLayout.layout(FormLayout.java:364)
        at org.eclipse.swt.layout.FormLayout.layout(FormLayout.java:292)
        at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1799)
        at org.eclipse.swt.widgets.Composite.setBounds(Composite.java:1587)
        at org.eclipse.swt.widgets.Control.setBounds(Control.java:1006)
        at org.eclipse.swt.layout.FormLayout.layout(FormLayout.java:364)
        at org.eclipse.swt.layout.FormLayout.layout(FormLayout.java:292)
        at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1799)
        at org.eclipse.swt.widgets.Composite.setBounds(Composite.java:1587)
        at org.eclipse.swt.widgets.Control.setBounds(Control.java:1006)
        at org.eclipse.swt.layout.FormLayout.layout(FormLayout.java:364)
        at org.eclipse.swt.layout.FormLayout.layout(FormLayout.java:292)
        at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1799)
        at org.eclipse.swt.widgets.Composite.setBounds(Composite.java:1587)
        at org.eclipse.swt.widgets.Control.setBounds(Control.java:1006)
        at org.eclipse.swt.layout.FormLayout.layout(FormLayout.java:364)
        at org.eclipse.swt.layout.FormLayout.layout(FormLayout.java:292)
        at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1799)
        at org.eclipse.swt.widgets.Composite.setBounds(Composite.java:1587)
        at org.eclipse.swt.widgets.Control.setBounds(Control.java:1006)
        at org.eclipse.swt.layout.FormLayout.layout(FormLayout.java:364)
        at org.eclipse.swt.layout.FormLayout.layout(FormLayout.java:292)
        at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1799)
        at org.eclipse.swt.widgets.Composite.layout(Composite.java:1108)
        at com.biglybt.ui.swt.shells.main.MainWindowImpl.createWindow(MainWindowImpl.java:769)
        at com.biglybt.ui.swt.shells.main.MainWindowImpl.access$2(MainWindowImpl.java:462)
        at com.biglybt.ui.swt.shells.main.MainWindowImpl$2.runWithDisplay(MainWindowImpl.java:233)
        at com.biglybt.ui.swt.utils.SWTRunnable.run(SWTRunnable.java:37)
        at com.biglybt.ui.swt.Utils.execSWTThread(Utils.java:916)
        at com.biglybt.ui.swt.Utils.execSWTThread(Utils.java:1082)
        at com.biglybt.ui.swt.shells.main.MainWindowImpl.<init>(MainWindowImpl.java:228)
        at com.biglybt.ui.swt.shells.main.MainWindowFactory.createAsync(MainWindowFactory.java:62)
        at com.biglybt.ui.swt.Initializer.runInSWTThread(Initializer.java:277)
        at com.biglybt.ui.swt.mainwindow.SWTThread.<init>(SWTThread.java:272)
        at com.biglybt.ui.swt.mainwindow.SWTThread.createInstance(SWTThread.java:56)
        at com.biglybt.ui.swt.Initializer.<init>(Initializer.java:179)
        at com.biglybt.ui.swt.UI.takeMainThread(UI.java:136)
        at com.biglybt.ui.Main.main(Main.java:239)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.biglybt.launcher.Launcher$1.run(Launcher.java:48)
        at java.lang.Thread.run(Thread.java:748)


(BiglyBT:11423): Gtk-CRITICAL **: 18:08:24.647: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(BiglyBT:11423): Gtk-CRITICAL **: 18:08:24.648: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(BiglyBT:11423): Gtk-CRITICAL **: 18:08:24.652: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
Locale Initializing took 0ms

(BiglyBT:11423): Gtk-CRITICAL **: 18:08:24.941: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(BiglyBT:11423): Gtk-CRITICAL **: 18:08:24.942: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
Core Initializing took 293ms
DEBUG::Thu Oct 31 18:08:25 CST 2019::com.biglybt.core.proxy.impl.AEPluginProxyHandler::installTor::704:
  Tor Helper install declined (either user reply or auto-remembered)
    AEPluginProxyHandler::checkPluginInstallation::571, AEPluginProxyHandler::getPluginServerProxy::498, AEProxyFactory::getPluginServerProxy::173, WebPlugin$16::runSupport::1483, AsyncDispatcher$1::run::161, AEThread2$threadWrapper::run::317
```

* OS and version Ubuntu 19.10 x64
* BiglyBT Version Number: latest released
* For *nix: Desktop Environment : KDE 5.17

**Comment by o0nd7ots** [comment]
This is likely outtaded. @parg can you close this please?
