### ISSUE TITLE
Torrents not seeding but queued

### ISSUE THREAD

**Issue by whiteloader** [BiglySoftware/BiglyBT#1328]
I have trouble seeding a lot of files and it driving me nuts. About 1 hour after starting to seed my torrents (~120] go automatically in "Queued" Mode and it's not clear why. I tried lots of different settings but I can't fix it. The only workaround I found is putting them in "Forced Seeding" mode.

In the example of this screenshot I put two torrents back in "normal seeding" and after about an hour later they go into queue mode. If I have all of them in normal seeding mode about half of them stay active after some time and the they all keep re-allocation and queuing, consuming a lot of ressources

![image](https://user-images.githubusercontent.com/57460132/68334141-42b12e80-00da-11ea-81f4-982d74a81721.png)

I also made a screensot of the (what I believe) most important settings. Maybe I am just to stupid to understand why it happens.

Please see my settings here: https://imgur.com/a/jwtY56y

Here is a section of the log when it happens:

```
20:41:29.842 3 stderr  DEBUG::Wed Nov 06 20:41:29 CET 2019::com.biglybt.core.util.DebugLight::printStackTrace::35:
20:41:29.844 3 stderr    org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4595)
	at org.eclipse.swt.SWT.error(SWT.java:4510)
	at org.eclipse.swt.SWT.error(SWT.java:4481)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:451)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:350)
	at org.eclipse.swt.widgets.Table.getItems(Table.java:2626)
	at com.biglybt.plugin.net.buddy.swt.BuddyPluginViewBetaChat.timerTick(BuddyPluginViewBetaChat.java:4322)
	at com.biglybt.plugin.net.buddy.swt.BuddyPluginViewBetaChat.lambda$1(BuddyPluginViewBetaChat.java:542)
	at com.biglybt.ui.swt.Utils$13.runSupport(Utils.java:1062)
	at com.biglybt.core.util.AERunnable.run(AERunnable.java:36)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3920)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3551)
	at com.biglybt.ui.swt.mainwindow.SWTThread.<init>(SWTThread.java:286)
	at com.biglybt.ui.swt.mainwindow.SWTThread.createInstance(SWTThread.java:56)
	at com.biglybt.ui.swt.Initializer.<init>(Initializer.java:179)
	at com.biglybt.ui.swt.UI.takeMainThread(UI.java:136)
	at com.biglybt.ui.Main.main(Main.java:239)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.biglybt.launcher.Launcher$1.run(Launcher.java:48)
	at java.lang.Thread.run(Unknown Source)
20:41:29.845 3 stderr  
20:41:29.925 3 stderr  DEBUG::Wed Nov 06 20:41:29 CET 2019::com.biglybt.core.util.DebugLight::printStackTrace::35:
20:41:29.926 3 stderr    org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4595)
	at org.eclipse.swt.SWT.error(SWT.java:4510)
	at org.eclipse.swt.SWT.error(SWT.java:4481)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:451)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:350)
	at org.eclipse.swt.widgets.Table.getItems(Table.java:2626)
	at com.biglybt.plugin.net.buddy.swt.BuddyPluginViewBetaChat.timerTick(BuddyPluginViewBetaChat.java:4322)
	at com.biglybt.plugin.net.buddy.swt.BuddyPluginViewBetaChat.lambda$1(BuddyPluginViewBetaChat.java:542)
	at com.biglybt.ui.swt.Utils$13.runSupport(Utils.java:1062)
	at com.biglybt.core.util.AERunnable.run(AERunnable.java:36)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3920)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3551)
	at com.biglybt.ui.swt.mainwindow.SWTThread.<init>(SWTThread.java:286)
	at com.biglybt.ui.swt.mainwindow.SWTThread.createInstance(SWTThread.java:56)
	at com.biglybt.ui.swt.Initializer.<init>(Initializer.java:179)
	at com.biglybt.ui.swt.UI.takeMainThread(UI.java:136)
	at com.biglybt.ui.Main.main(Main.java:239)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.biglybt.launcher.Launcher$1.run(Launcher.java:48)
	at java.lang.Thread.run(Unknown Source)
20:41:29.927 3 stderr  
20:41:30.776 0 core    Starting non-daemon task: Stopping 'Linux-Distro1'
20:41:30.777 0 tracker TRTrackerClient: exported 5 cached peers . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .Torrent: 'Linux-Distro1'
20:41:30.777 0 tracker Forcing tracker announce now via TRTrackerBTAnnouncerImpl::stop::639, TRTrackerAnnouncerMuxer::stop::1221, DownloadManagerImpl::informStopped::3868 Torrent: 'Linux-Distro1'
20:41:30.778 0 tracker Tracker Announcer is sending a stopped Request . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .Torrent: 'Linux-Distro1'
20:41:30.779 0 tracker Tracker Announcer is Requesting: https://linux.tracker:443/tracker.php/000dfkfdklasjglksdfgjklsdfgdfgh0410f/announce?info_hash=reducted&peer_id=reducted&supportcrypto=1&port=6881&azudp=6881&uploaded=0&downloaded=0&left=0&corrupt=0&event=stopped&numwant=0&azq=1&no_peer_id=1&compact=1&key=KGzcXT1v&azver=3 Torrent: 'Linux-Distro1'
20:41:30.779 0 disk    Saving state for download 'Linux-Distro1' . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . Torrent: 'Linux-Distro1'
20:41:30.796 0 core    Completed non-daemon task: Stopping 'Linux-Distro1'
20:41:30.812 0 core    Starting non-daemon task: Stopping 'Linux-Distro2'
20:41:30.813 0 tracker TRTrackerClient: exported 0 cached peers . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .Torrent: 'Linux-Distro2'
20:41:30.813 0 tracker Forcing tracker announce now via TRTrackerBTAnnouncerImpl::stop::639, TRTrackerAnnouncerMuxer::stop::1221, DownloadManagerImpl::informStopped::3868 Torrent: 'Linux-Distro2'
20:41:30.814 0 tracker Tracker Announcer is sending a stopped Request . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .Torrent: 'Linux-Distro2'
20:41:30.814 0 tracker Tracker Announcer is Requesting: https://tracker.linux.org/000dfksgj498034534645gfhdfgh0410f/announce?info_hash=reducted&peer_id=reducted&supportcrypto=1&port=6881&azudp=6881&uploaded=0&downloaded=0&left=0&corrupt=0&event=stopped&numwant=0&azq=1&no_peer_id=1&compact=1&key=YlilPDRr&azver=3 Torrent: 'Linux-Distro2'
20:41:30.814 0 disk    Saving state for download 'Linux-Distro2' . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . Torrent: 'Linux-Distro2'
20:41:30.833 0 core    Completed non-daemon task: Stopping 'Linux-Distro2'
20:41:30.979 0 UIv3    Media server plugin not operational
20:41:30.980 0 UIv3    Media server plugin not operational
20:41:30.982 0 UIv3    Media server plugin not operational
20:41:30.983 0 UIv3    Media server plugin not operational
20:41:30.984 0 UIv3    Media server plugin not operational
20:41:30.985 0 UIv3    Media server plugin not operational
20:41:31.011 3 stderr  DEBUG::Wed Nov 06 20:41:31 CET 2019::com.biglybt.core.util.DebugLight::printStackTrace::35:
20:41:31.012 3 stderr    org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4595)
	at org.eclipse.swt.SWT.error(SWT.java:4510)
	at org.eclipse.swt.SWT.error(SWT.java:4481)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:451)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:350)
	at org.eclipse.swt.widgets.Table.getItems(Table.java:2626)
	at com.biglybt.plugin.net.buddy.swt.BuddyPluginViewBetaChat.timerTick(BuddyPluginViewBetaChat.java:4322)
	at com.biglybt.plugin.net.buddy.swt.BuddyPluginViewBetaChat.lambda$1(BuddyPluginViewBetaChat.java:542)
	at com.biglybt.ui.swt.Utils$13.runSupport(Utils.java:1062)
	at com.biglybt.core.util.AERunnable.run(AERunnable.java:36)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3920)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3551)
	at com.biglybt.ui.swt.mainwindow.SWTThread.<init>(SWTThread.java:286)
	at com.biglybt.ui.swt.mainwindow.SWTThread.createInstance(SWTThread.java:56)
	at com.biglybt.ui.swt.Initializer.<init>(Initializer.java:179)
	at com.biglybt.ui.swt.UI.takeMainThread(UI.java:136)
	at com.biglybt.ui.Main.main(Main.java:239)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.biglybt.launcher.Launcher$1.run(Launcher.java:48)
	at java.lang.Thread.run(Unknown Source)
20:41:31.013 3 stderr  
```

I appreciate your help!

* OS and version: Windows 10 1903
* BiglyBT Version Number: 2.1.0.0
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4922, win32, zoom=100, dpi=120
Windows 10 v10.0, amd64 (64 bit)
B2.1.0.0/4 az3

**Comment by parg** [comment]
The 'queue rules' (Tools->Options->Queue) are there to schedule seeding (and downloading). Under 'ignore rules' there is an option to 'ignore seeds with 0 peers'. There is no point in spending local resources having a torrent seeding when there are no peers (in this context a peer means 'non-seed') around for you to send data to. So BiglyBT will queue such torrents and rotate through them periodically to check that there really are no peers.

**Comment by whiteloader** [comment]
I agree that makes sense in most cases. However many private linux trackers also count how long you seed (even without any peers) and award bonus point based on that.

Therefore I would like BitlyBT to continue seeding. I have the box you mentioned unchecked, but it's still stopping seeding. Is there any other setting preventing it?

Please see my settings here: https://imgur.com/a/jwtY56y

**Comment by parg** [comment]
Look under the 'Queue->Seeding->Ignore Rules' for the zero-peers thing, the one you have ticked there is to do with downloads that considered 'stalled' (i.e. getting nowhere)

If you want a download to actively seed forever, regardless of other criteria, then your best option (as you have found) is to 'force start' them. 

Otherwise in general share-ratios are used to determine when a seed moves from 'first priority' (i.e. will be scheduled to see before any other non-first-priority seeds) to 'non-first-priority'. 

Even first priority seeds will not be seeded if there are more of them than your 'max active torrents' (minus any downloads).

You can set a high share ratio for torrents associated with a particular tracker if you want. One way to do this is to go to the 'All Trackers' view (see the View menu), right-click on the tracker you're interested in and select 'Add Downloads To Tag' - enter a good name for the Tag. Then right-click on the Tag in the sidebar and set a 'minimum share ratio'

Now all torrents from that tracker (current and future) will have that share ratio as their minimum and they won't stop seeding (subject to comments above) until that ratio is met.
