### ISSUE TITLE
may want to optimize large torrents with lots of files/pieces

### ISSUE THREAD

**Issue by SUCM** [BiglySoftware/BiglyBT#1436]
accidentally clicked on the Piece Map tab of a 200G torrent with lots of files of various sizes ranging from GB to Bytes (total ~800000 pieces) and Bigly hung there for a few minutes. same issue when first loading/opening the torrents in Bigly. was wondering if it's possible to make this type of operations non-blocking, so I can continue work on other torrents while Bigly work on these giant torrents

the good thing is that Bigly doesn't crash for these type of torrents like qBittorrent and a couple other BT clients

* OS and version Win 10
* BiglyBT Version Number 2.2.0.2

**Comment by parg** [comment]
If you send the torrent over to paul@biglybt.com I can test it - obviously don't need to download the torrent but creating such a test torrent is a bit of a pain...

**Comment by parg** [comment]
I'll limit the number of pieces in the piece map to 32k - the UI can't handle many more pieces anyway for internal reasons

**Comment by parg** [comment]
Oh, and if you find any other UI issues (apart from the initial loading/opening torrent thing unless you think that is explicitly UI related) then please say.

**Comment by SUCM** [comment]
I typically get hit by loading/opening torrent the most since I don't wonder around on other views unless there are issues. I was doing it since 2.2.x is a new updated version

the other thing I started noticing since 2.1.x is that I see more torrents with only 1 or 2 seeds reported by trackers or DHT, but Bigly never connects to them despite them being there for more than 24 hours (or whenever I checked over time). don't know if they are blocking Bigly/me or what, but I'm able to connect to them when using uTorrent 2.x. they aren't Xunlei or any other bad clients according to uTorrent

did you mean the fix you are working on will resolve the blocking torrent loading/opening on huge torrents?

**Comment by parg** [comment]
I've only fiddled with slow UI issues in the piece-map view(s) so far. 

Exactly when do you get the UI hang when loading/opening a huge torrent? 

I don't have the free space to fully allocate a 200GB torrent so only have tested with a few files selected for download - in this case I didn't see much of an issue.

**Comment by SUCM** [comment]
I don't have disk space for large torrent at the moment, so I can't try to reproduce it. those instances could have been some super long paths, lots of files selected for download, allocating those files (without write to 0 though)...etc or a combination of those and some other factors

**Comment by ghub-mc-biglybt** [comment]
> I'll limit the number of pieces in the piece map to 32k - the UI can't handle many more pieces anyway for internal reasons

@parg  Hi there. The limit on pieces causes a hard error. Any chance it could be wrapped into a friendly message? 

```
java.lang.ArrayIndexOutOfBoundsException: Index 45445 out of bounds for length 32768
	at com.biglybt.ui.swt.views.piece.PieceInfoView.refreshInfoCanvasSupport(PieceInfoView.java:874)
	at com.biglybt.ui.swt.views.piece.PieceInfoView.refreshInfoCanvas(PieceInfoView.java:763)
	at com.biglybt.ui.swt.views.piece.PieceInfoView$4.mouseExit(PieceInfoView.java:454)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:208)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5685)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1423)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4953)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4446)
	at com.biglybt.ui.swt.mainwindow.SWTThread.<init>(SWTThread.java:400)
	at com.biglybt.ui.swt.mainwindow.SWTThread.createInstance(SWTThread.java:58)
	at com.biglybt.ui.swt.Initializer.<init>(Initializer.java:180)
	at com.biglybt.ui.swt.UI.takeMainThread(UI.java:136)
	at com.biglybt.ui.Main.main(Main.java:239)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.biglybt.launcher.Launcher$1.run(Launcher.java:48)
	at java.base/java.lang.Thread.run(Thread.java:834)
```



P.S. This is on Debian Linux running version 2.4.0.1_B10. Please let me know if you need any other details.

**Comment by ghub-mc-biglybt** [comment]
https://github.com/BiglySoftware/BiglyBT/blob/1a5d913cc4770ca14954b6b9c69cecce8a98330e/uis/src/com/biglybt/ui/swt/views/piece/PieceInfoView.java#L872

I don't have a system set up to compile and test changes at this time, but from looking at the code changing the line above to the one below doesn't look like it would cause issues with later code.

`					for (int j = 1; j < peerRequestedPieces.length && j < numPieces; j++) {`

**Comment by parg** [comment]
Thanks, fixed next beta!

**Comment by ghub-mc-biglybt** [comment]
Loads now. Thanks so much!
![image](https://user-images.githubusercontent.com/66757958/85325632-8e5df000-b491-11ea-830a-4d223a402bcc.png)
