### ISSUE TITLE
[Feature Request] display total reported download and upload to each tracker

### ISSUE THREAD

**Issue by SUCM** [BiglySoftware/BiglyBT#1478]
would like to see what's the total upload and download bytes/size reported to each tracker in
1. all tracker view. where the new total upload and download columns sum/aggregate total from all torrents reported to a tracker
2. each torrent's tracker view for download and upload sizes reported to each tracker for that torrent

sometime I also wish I can see similar stats on per client level to see what BT clients leeches the most from me and sends me the most data, to determine if I should really add clients like xl to the ban list

**Comment by SUCM** [comment]
hopefully this new total reported download and upload to each tracker can stay persistent even if there is currently no torrent using the tracker. maybe let user pin the interested trackers static in all tracker view or if you actually want to implement this in a new viewable tab separated from the all tracker view

**Comment by parg** [comment]
What about Tools->Client Stats?

**Comment by SUCM** [comment]
Tools->Client Stats has similar problem as All Trackers. only shows client stats for current running Torrents during current run of Bigly, no lifetime/persistent data over everything so all stats are reset/gone after restarted Bigly

**Comment by TuxPaper** [comment]
fwiw, Tools->Client Stats shows you a full month's stats, but only if it's in the sidebar at all times.

Previous months client stats are stored in the BiglyBT config dir as ClientStats_YYYY_MM.dat, however, there's no way to show these stats in BiglyBT (ie. no developer has been interested in writing a view to show previous months)

**Comment by SUCM** [comment]
I'm not sure what does Tools->Client Stats display

I had left it in the sidebar under Plugins & Extras for couple hours, but its display content doesn't change at all despite 2GB of data has been transferred with various clients

**Comment by SUCM** [comment]
I had unintentionally made this ticket off topic from the main feature request quite a bit, so just wanted to mention that the original request is to show the life time total reported download and upload size to each tracker aggregated from all torrent since the beginning or whenever this feature is added/activated

the client stats is just some thought wanting to figure out a good way to populate the client ban list properly

**Comment by parg** [comment]
2203_B25 has session stats per-torrent and in AllTrackers (reported sent/reported received - you need to enable the columns in table column setup)

**Comment by SUCM** [comment]
using 2203_B25,

I see all tracker has 1 number per column while per torrent has an additional number in tracker per column, but number in brackets are the same as the number outside of the bracket. should I expect them to be different?

there seems to be some issue with this beta. for torrents (also the popular ones with hundreds of seeds and peer) download and upload happens in burst. it runs for few seconds, then dropped to 0 for minutes, then runs for few seconds again. However, I'm connected to seeds and peers all the time. when I was at 2002 released version, download and upload works fine and runs continuously. downgrade using the jar on github release also doesn't show that interesting download/upload behaviour

when I tried to download core_BiglyBT2.2.0.2.jar, I can't connect to any of the seeds despite more than 10 were reported by sources. I'm connected to more than 50 peers but they are all stuck at 0% themselves. privacy is set at pub/pri mix. it's also weird that torrent for core_BiglyBT2.2.0.2.jar is 64MB in size while regular jars for various version are around 18MB only

also getting some errors
```
org.eclipse.swt.SWTException: Data does not have correct format for type
	at org.eclipse.swt.dnd.DND.error(DND.java:290)
	at org.eclipse.swt.dnd.DND.error(DND.java:241)
	at org.eclipse.swt.dnd.TextTransfer.javaToNative(TextTransfer.java:71)
	at org.eclipse.swt.dnd.DragSource.GetData(DragSource.java:479)
	at org.eclipse.swt.dnd.DragSource.access$500(DragSource.java:106)
	at org.eclipse.swt.dnd.DragSource$2.method3(DragSource.java:266)
	at org.eclipse.swt.internal.ole.win32.COMObject.callback3(COMObject.java:95)
	at org.eclipse.swt.internal.ole.win32.COM.VtblCall(Native Method)
	at org.eclipse.swt.internal.ole.win32.IDataObject.GetData(IDataObject.java:30)
	at org.eclipse.swt.dnd.Transfer.getData(Transfer.java:47)
	at org.eclipse.swt.dnd.TextTransfer.nativeToJava(TextTransfer.java:132)
	at org.eclipse.swt.dnd.DropTarget.Drop(DropTarget.java:454)
	at org.eclipse.swt.dnd.DropTarget.Drop_64(DropTarget.java:401)
	at org.eclipse.swt.dnd.DropTarget$1.method6(DropTarget.java:265)
	at org.eclipse.swt.internal.ole.win32.COMObject.callback6(COMObject.java:122)
	at org.eclipse.swt.internal.ole.win32.COM.DoDragDrop(Native Method)
	at org.eclipse.swt.dnd.DragSource.drag(DragSource.java:370)
	at org.eclipse.swt.dnd.DragSource.lambda$new$0(DragSource.java:175)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4132)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3945)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3548)
	at com.biglybt.ui.swt.mainwindow.SWTThread.<init>(SWTThread.java:363)
	at com.biglybt.ui.swt.mainwindow.SWTThread.createInstance(SWTThread.java:58)
	at com.biglybt.ui.swt.Initializer.<init>(Initializer.java:179)
	at com.biglybt.ui.swt.UI.takeMainThread(UI.java:136)
	at com.biglybt.ui.Main.main(Main.java:239)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.biglybt.launcher.Launcher$1.run(Launcher.java:48)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
