### ISSUE TITLE
Jackett no longer working with 2.3.0.0 update

### ISSUE THREAD

**Issue by ReinerS10** [BiglySoftware/BiglyBT#1547]
On March 5, 2020, BiglyBT auto-updated to 2.3.0.0. Since then I have unable to search anything via Jackett nor pull any new torrents from any of the listed trackers within Jackett. I have sent in my logs to Jackett and they said that it is most likely a Captcha issue with Cloudflare and my IP address. I have reported the issue with my VPN and after review and testing numerous server IP addresses shows that it is not an issue with or without the VPN. This leads me back to BiglyBT. I have reverted back to 2.2.0.0 and upgraded to the beta version to see if this fixed the problem. It did not. I can still access all the torrent sites if I manually initiate within the Jackett Web UI so it is not a Jackett or IP issue. Somehow Jackett is no longer working with BiglyBT or vice versa. Regular subscriptions in BiglyBT (outside of Jackett) continue to work. 

Any ideas or 

suggestions are much appreciated. BiglyBT logs are attached.
[Subscriptions_1.log](https://github.com/BiglySoftware/BiglyBT/files/4367067/Subscriptions_1.log)

BiglyBT Error (example #1): In this case,, it is not even updating
Last successful update: 3/8/20 9:20 AM
Last new result found: 3/5/20 11:13 AM
Next scan due: 3/8/20 11:20 AM

BiglyBT Error (example #2): In most cases it is failing to load the page.
Failed to load page, http://127.0.0.1:9117/api/v2.0/indexers/all/results?apikey=9vopnhwtfgup56brcwqkdrx65kncvzwy&Query=********+******&_=1548156611274&azsrc=subscription: I/O Exception while downloading 'http://127.0.0.1:9117/api/v2.0/indexers/all/results', Read timed out

Jackett Error (example): Jackett says this is a Captcha error with Cloudflare but was never in issue in months past.

Jackett.Common.IndexerException: Exception (cpasbien): Clearance failed after 30 attempt(s).
 ---> CloudflareSolverRe.Exceptions.CloudflareClearanceException: Clearance failed after 30 attempt(s).
   at CloudflareSolverRe.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Jackett.Common.Utils.Clients.HttpWebClient2NetCore.Run(WebRequest webRequest) in d:\a\1\s\src\Jackett.Common\Utils\Clients\HttpWebClient2NetCore.cs:line 237
   at Jackett.Common.Utils.Clients.WebClient.GetString(WebRequest request) in d:\a\1\s\src\Jackett.Common\Utils\Clients\WebClient.cs:line 164
   at Jackett.Common.Indexers.BaseWebIndexer.RequestStringWithCookies(String url, String cookieOverride, String referer, Dictionary`2 headers) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 442
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\CardigannIndexer.cs:line 1321
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 345
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 345
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in d:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 807
   at Jackett.Server.Controllers.ResultsController.Results(ApiSearch requestt) in d:\a\1\s\src\Jackett.Server\Controllers\ResultsController.cs:line 224
 

* OS and version: Win 10 Home
* BiglyBT Version Number: 2.3.0.0
* For *nix: Desktop Environment

**Comment by ReinerS10** [comment]
I just resolved the issue!

Solution:
RSS Feeds, Subscription, Trackers, Torrents not updating. 
When there are a lot of subscriptions trying to update at the same time you will receive a timeout or retrying, etc. error (can be confused with other issues like IP address blocked). 
Solution for BiglyBT (and probably Vuze): Tools -> Options -> Search -- Timeout for search templates and feeds [*increase seconds*] 

also 

For each subscription change the Update Period in Seconds so that no two subscriptions are trying to update and the same time.

**Comment by parg** [comment]
Thanks for figuring it out!
