### ISSUE TITLE
NPE while checking/allocating

### ISSUE THREAD

**Issue by ftfckr** [BiglySoftware/BiglyBT#1581]
```
[19:02:22] [alert] Alert:3:Disk write error: NullPointerException
[19:02:22] [stderr] DEBUG::Mon Apr 06 19:02:22 BST 2020::com.biglybt.core.disk.impl.access.impl.DMWriterImpl::writeBlock::586:
[19:02:22] [stderr]   java.lang.NullPointerException
	at com.biglybt.core.disk.impl.access.impl.DMWriterImpl.writeBlock(DMWriterImpl.java:444)
	at com.biglybt.core.disk.impl.DiskManagerImpl.enqueueWriteRequest(DiskManagerImpl.java:2387)
	at com.biglybt.core.disk.impl.resume.RDResumeHandler$4.readCompleted(RDResumeHandler.java:697)
	at com.biglybt.core.disk.impl.access.impl.DMReaderImpl$2.readCompleted(DMReaderImpl.java:272)
	at com.biglybt.core.disk.impl.access.impl.DMReaderImpl$3.readCompleted(DMReaderImpl.java:410)
	at com.biglybt.core.disk.impl.access.impl.DMReaderImpl$requestDispatcher.dispatch(DMReaderImpl.java:558)
	at com.biglybt.core.disk.impl.access.impl.DMReaderImpl$requestDispatcher.requestComplete(DMReaderImpl.java:691)
	at com.biglybt.core.diskmanager.access.impl.DiskAccessRequestImpl.runRequest(DiskAccessRequestImpl.java:104)
	at com.biglybt.core.diskmanager.access.impl.DiskAccessControllerInstance$requestDispatcher$1.run(DiskAccessControllerInstance.java:701)
	at com.biglybt.core.util.AEThread2$threadWrapper.run(AEThread2.java:317)
```

System info:
```
Java 1.8.0_242 (64 bit)
  AdoptOpenJDK
c:\program files\adoptopenjdk\jre-8.0.242.08-hotspot

SWT v4930r7, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.3.0.1_B19/4 az3
```

Getting this mainly on larger torrents. Disk check and memory diags all show clear, nothing in Windows event logs to indicate hardware failure, and notably no system namespaces in the stack trace.

Other symptoms showing up:
* Previously completed torrents will "un-complete" and end up back on the download queue.
* A check will interrupt with no visible exception in the console and all pieces from where it was to the end of the torrent will show up in the log as "file is missing, failing check" - completion status will look like this:
![image](https://user-images.githubusercontent.com/54716748/78610428-b8255480-785c-11ea-9feb-2edca098be48.png)
* If multiple torrents are being queued up behind the one throwing the NPE, they will enter state "Downloading" but the status indicator doesn't light up, no data is transferred, and no re-checks are done with "Periodically re-check incomplete pieces" enabled

I have a debug zip, but it contains decidedly non-Linuxy info so let me know how you want me to send that.

**Comment by o0nd7ots** [comment]
@parg can we close this?

**Comment by parg** [comment]
Closing as nothing's going to happen here, re-open if so desired.
