### ISSUE TITLE
B21 update download error

### ISSUE THREAD

**Issue by ferdnyc** [BiglySoftware/BiglyBT#1597]
BiglyBT offered me the _B21 beta update released earlier today, but every time I click "Install" I get this error message in the Updater window, which results in a "Failed" update attempt. Restarting BiglyBT did not clear it up.

<blockquote>
<p>Downloading: [http://version.biglybt.com/biglybt-files/core/BiglyBT2301-B21-signed.jar.torrent?i2p=1: torrent,http://version.biglybt.com/biglybt-files/core/BiglyBT2301-B21-signed.jar.torrent?i2p=1]</p>
<p>Downloading: core_BiglyBT2301-B21-signed.jar</p>
<p>Downloading: [http://version.biglybt.com/biglybt-files/core/BiglyBT2301-B21-signed.jar.torrent?i2p=1: torrent,http://version.biglybt.com/biglybt-files/core/BiglyBT2301-B21-signed.jar.torrent?i2p=1]</p>
<p>Downloading: http://version.biglybt.com/biglybt-files/core/BiglyBT2301-B21-signed.jar.torrent</p>
<p>[http://version.biglybt.com/biglybt-files/core/BiglyBT2301-B21-signed.jar.torrent?i2p=1: torrent,http://version.biglybt.com/biglybt-files/core/BiglyBT2301-B21-signed.jar.torrent?i2p=1] : com.biglybt.pif.utils.resourcedownloader.ResourceDownloaderException: http://version.biglybt.com/biglybt-files/core/BiglyBT2301-B21-signed.jar.torrent?i2p=1: No plugin proxy available</p>
</blockquote>

#### System block
```
Java 1.8.0_242 (64 bit)
  Oracle Corporation
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.fc31.x86_64/jre

SWT v4930r7, gtk/3.24.13, zoom=100, dpi=96
Linux v5.5.15-200.fc31.x86_64, amd64 (64 bit)
B2.3.0.1_B20/4 az3
```

**Comment by parg** [comment]
Do you have 'update anonymously' enabled? Seems to be failing to download the update .torrent and the only error logged there indicates an issue with the Tor Helper plugin (although this is used as a backup if direct download fails regardless of 'update anonymously' so not sure.

**Comment by ferdnyc** [comment]
@parg 

Nope, nothing special there.

![image](https://user-images.githubusercontent.com/538020/79133019-56dc1480-7d79-11ea-94d1-e7730fb22444.png)

I also don't use Tor, so that it would be failing would make sense. (I may actually have the Tor plugin disabled completely, in fact.) If it's automatically used as a fallback then I guess that explains why it would show up at all.

**Comment by ferdnyc** [comment]
Oh! Haha.

Stupid ImageMagick _filled_ my machine's `/tmp`, so it can't save the torrent file for the new version:
```sh
$ df /tmp
Filesystem     1K-blocks    Used Available Use% Mounted on
tmpfs            2912280 2912280         0 100% /tmp
```
```
[11:31:02.898] {stderr} DEBUG::Mon Apr 13 11:31:02 EDT 2020::com.biglybt.core.torrent.impl.TOTorrentImpl::serialiseToBEncodedFile::285:
[11:31:02.899] {stderr}   java.io.IOException: No space left on device
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(FileOutputStream.java:326)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at java.io.FilterOutputStream.close(FilterOutputStream.java:158)
	at com.biglybt.core.torrent.impl.TOTorrentImpl.serialiseToBEncodedFile(TOTorrentImpl.java:281)
	at com.biglybt.pifimpl.local.utils.resourcedownloader.ResourceDownloaderTorrentImpl.downloadTorrent(ResourceDownloaderTorrentImpl.java:322)
	at com.biglybt.pifimpl.local.utils.resourcedownloader.ResourceDownloaderTorrentImpl.asyncDownload(ResourceDownloaderTorrentImpl.java:286)
	at com.biglybt.pifimpl.local.utils.resourcedownloader.ResourceDownloaderAlternateImpl.asyncDownload(ResourceDownloaderAlternateImpl.java:270)
	at com.biglybt.ui.swt.update.UpdateWindow.nextUpdate(UpdateWindow.java:589)
	at com.biglybt.ui.swt.update.UpdateWindow.update(UpdateWindow.java:582)
	at com.biglybt.ui.swt.update.UpdateWindow.access$0(UpdateWindow.java:550)
	at com.biglybt.ui.swt.update.UpdateWindow$5.handleEvent(UpdateWindow.java:286)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5676)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1423)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4935)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4429)
	at com.biglybt.ui.swt.mainwindow.SWTThread.<init>(SWTThread.java:367)
	at com.biglybt.ui.swt.mainwindow.SWTThread.createInstance(SWTThread.java:58)
	at com.biglybt.ui.swt.Initializer.<init>(Initializer.java:180)
	at com.biglybt.ui.swt.UI.takeMainThread(UI.java:136)
	at com.biglybt.ui.Main.main(Main.java:239)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.biglybt.launcher.Launcher$1.run(Launcher.java:48)
	at java.lang.Thread.run(Thread.java:748)
[11:31:02.899] {stderr} 
```

**Comment by ferdnyc** [comment]
(I closed this because, clearly a local problem... but in thinking about it a bit more, it _would_ be cool if the updater surfaced the actual error condition there, instead of it being buried in the console logs.)

**Comment by parg** [comment]
true that
