### ISSUE TITLE
Backup Failed Error During Auto-Backups

### ISSUE THREAD

**Issue by NaPurHab** [BiglySoftware/BiglyBT#1633]
This doesn't happen every time, But I see it a few times a week.  Which is odd, as I have it set to backup every 12 hours, retaining 14 copies.  Would have mentioned it earlier, just thought it was something common that would be caught.

```
java.lang.Exception: Failed to copy file 'C:\Users\MyID\AppData\Roaming\BiglyBT\plugins\azneti2phelper\netDb\r-\routerInfo--WSKKD8~vldcNjJ2fZ1ViFAxccJsb5lpY3bCZ-adbio=.dat'
	at com.biglybt.core.backup.impl.BackupManagerImpl.copyFilesSupport(BackupManagerImpl.java:705)
	at com.biglybt.core.backup.impl.BackupManagerImpl.copyFilesSupport(BackupManagerImpl.java:664)
	at com.biglybt.core.backup.impl.BackupManagerImpl.copyFilesSupport(BackupManagerImpl.java:664)
	at com.biglybt.core.backup.impl.BackupManagerImpl.copyFilesSupport(BackupManagerImpl.java:664)
	at com.biglybt.core.backup.impl.BackupManagerImpl.copyFilesSupport(BackupManagerImpl.java:664)
	at com.biglybt.core.backup.impl.BackupManagerImpl.copyFiles(BackupManagerImpl.java:606)
	at com.biglybt.core.backup.impl.BackupManagerImpl.backupSupport(BackupManagerImpl.java:917)
	at com.biglybt.core.backup.impl.BackupManagerImpl$7.runSupport(BackupManagerImpl.java:575)
	at com.biglybt.core.util.AsyncDispatcher$1.run(AsyncDispatcher.java:161)
	at com.biglybt.core.util.AEThread2$threadWrapper.run(AEThread2.java:317)
```

Java 14 (64 bit)
  AdoptOpenJDK
c:\program files\adoptopenjdk\jre-14.0.0.36-openj9

SWT v4930r7, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.3.0.1_B33/4 az3

**Comment by parg** [comment]
thanks, fixed next beta
