### ISSUE TITLE
NPE at com.biglybt.ui.swt.views.TrackerView.fillMenu(TrackerView.java:376)

### ISSUE THREAD

**Issue by rindeal** [BiglySoftware/BiglyBT#1657]
debug log:
```
[22:06:17] [stderr] 	at com.biglybt.ui.Main.main(Main.java:239)
[22:06:17] [stderr] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:06:17] [stderr] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[22:06:17] [stderr] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:06:17] [stderr] 	at java.lang.reflect.Method.invoke(Method.java:498)
[22:06:17] [stderr] 	at com.biglybt.launcher.Launcher$1.run(Launcher.java:48)
[22:06:17] [stderr] 	at java.lang.Thread.run(Thread.java:748)
[22:06:17] java.lang.NullPointerException
	at com.biglybt.ui.swt.views.TrackerView.fillMenu(TrackerView.java:376)
	at com.biglybt.ui.swt.views.table.impl.TableViewSWT_Common.fillMenu(TableViewSWT_Common.java:971)
	at com.biglybt.ui.swt.views.table.painted.TableViewPainted$29.buildMenu(TableViewPainted.java:3063)
	at com.biglybt.ui.swt.MenuBuildUtils$1.menuShown(MenuBuildUtils.java:138)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:259)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5797)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1374)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1400)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1379)
	at org.eclipse.swt.widgets.Menu._setVisible(Menu.java:202)
	at org.eclipse.swt.widgets.Display.runPopups(Display.java:5093)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4573)
	at com.biglybt.ui.swt.mainwindow.SWTThread.<init>(SWTThread.java:367)
	at com.biglybt.ui.swt.mainwindow.SWTThread.createInstance(SWTThread.java:58)
	at com.biglybt.ui.swt.Initializer.<init>(Initializer.java:180)
	at com.biglybt.ui.swt.UI.takeMainThread(UI.java:136)
	at com.biglybt.ui.Main.main(Main.java:239)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.biglybt.launcher.Launcher$1.run(Launcher.java:48)
	at java.lang.Thread.run(Thread.java:748)
```

sys info:
```
BiglyBT version:         2.4.0.0
Operating System:        openSUSE Tumbleweed 20200519
KDE Plasma Version:      5.18.5
KDE Frameworks Version:  5.70.0
Qt Version:              5.14.1
OS Type:                 64-bit
```

**Comment by parg** [comment]
fixed next beta, thanks!
