### ISSUE TITLE
crash after `No space left on device`

### ISSUE THREAD

**Issue by rindeal** [BiglySoftware/BiglyBT#1658]
<details>
<summary>`debug_*.log` 1st crash</summary>

```
[00:00:57] [stderr] DEBUG::Mon May 25 00:00:57 UTC 2020::com.biglybt.core.diskmanager.file.impl.FMFileImpl::writeSupport::801:
[00:00:57] [stderr]   com.biglybt.core.diskmanager.file.FMFileManagerException: write fails
	at com.biglybt.core.diskmanager.file.impl.FMFileAccessLinear.write(FMFileAccessLinear.java:545)
	at com.biglybt.core.diskmanager.file.impl.FMFileAccessController.write(FMFileAccessController.java:484)
	at com.biglybt.core.diskmanager.file.impl.FMFileImpl.writeSupport(FMFileImpl.java:795)
	at com.biglybt.core.diskmanager.file.impl.FMFileLimited.write(FMFileLimited.java:310)
	at com.biglybt.core.diskmanager.cache.impl.CacheFileWithCache.multiBlockFlush(CacheFileWithCache.java:1102)
	at com.biglybt.core.diskmanager.cache.impl.CacheFileWithCache.flushCacheSupport(CacheFileWithCache.java:969)
	at com.biglybt.core.diskmanager.cache.impl.CacheFileWithCache.flushCache(CacheFileWithCache.java:832)
	at com.biglybt.core.diskmanager.cache.impl.CacheFileWithCache.flushCache(CacheFileWithCache.java:1151)
	at com.biglybt.core.diskmanager.cache.impl.CacheFileWithCache.flushCachePublic(CacheFileWithCache.java:1169)
	at com.biglybt.core.diskmanager.cache.impl.CacheFileWithCache.close(CacheFileWithCache.java:1750)
	at com.biglybt.core.disk.impl.DiskManagerImpl.stop(DiskManagerImpl.java:718)
	at com.biglybt.core.download.impl.DownloadManagerController$7.run(DownloadManagerController.java:982)
	at com.biglybt.core.util.NonDaemonTaskRunner$taskWrapper.run(NonDaemonTaskRunner.java:202)
	at com.biglybt.core.util.NonDaemonTaskRunner$1.run(NonDaemonTaskRunner.java:160)
	at com.biglybt.core.util.AEThread2$threadWrapper.run(AEThread2.java:317)
Caused by: java.io.IOException: No space left on device
	at sun.nio.ch.FileDispatcherImpl.writev0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.writev(FileDispatcherImpl.java:72)
	at sun.nio.ch.IOUtil.write(IOUtil.java:148)
	at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:239)
	at java.nio.channels.FileChannel.write(FileChannel.java:414)
	at com.biglybt.core.diskmanager.file.impl.FMFileAccessLinear.write(FMFileAccessLinear.java:484)
	... 14 more
[00:00:57] [stderr] 
[00:00:57] DEBUG::Mon May 25 00:00:57 UTC 2020  Recovered connection to /file.1 after access failure
```

the above message was repeated 66 times, then

```
[00:00:57] [alert] Alert:3:File close fails: flush fails, write fails, No space left on device
```

---
</details>

<details>
<summary>`debug_*.log` 2nd crash</summary>

same as 1st crash + this:

```
[00:00:55] [stderr] DEBUG::Mon May 25 00:00:55 CEST 2020::com.biglybt.core.disk.impl.access.impl.DMWriterImpl$3::writeFailed::525:
[00:00:55] [stderr]   com.biglybt.core.diskmanager.cache.CacheFileManagerException: flush fails
	at com.biglybt.core.diskmanager.cache.impl.CacheFileWithCache.multiBlockFlush(CacheFileWithCache.java:1112)
	at com.biglybt.core.diskmanager.cache.impl.CacheFileWithCache.flushCacheSupport(CacheFileWithCache.java:1032)
	at com.biglybt.core.diskmanager.cache.impl.CacheFileWithCache.flushCache(CacheFileWithCache.java:832)
	at com.biglybt.core.diskmanager.cache.impl.CacheFileWithCache.flushCache(CacheFileWithCache.java:1151)
	at com.biglybt.core.diskmanager.cache.impl.CacheFileManagerImpl.allocateCacheSpace(CacheFileManagerImpl.java:399)
	at com.biglybt.core.diskmanager.cache.impl.CacheFileWithCache.writeCache(CacheFileWithCache.java:725)
	at com.biglybt.core.diskmanager.cache.impl.CacheFileWithCache.writeAndHandoverBuffer(CacheFileWithCache.java:1666)
	at com.biglybt.core.diskmanager.access.impl.DiskAccessRequestImpl.runRequest(DiskAccessRequestImpl.java:99)
	at com.biglybt.core.diskmanager.access.impl.DiskAccessControllerInstance$requestDispatcher$1.run(DiskAccessControllerInstance.java:701)
	at com.biglybt.core.util.AEThread2$threadWrapper.run(AEThread2.java:317)
Caused by: com.biglybt.core.diskmanager.file.FMFileManagerException: write fails
	at com.biglybt.core.diskmanager.file.impl.FMFileAccessLinear.write(FMFileAccessLinear.java:545)
	at com.biglybt.core.diskmanager.file.impl.FMFileAccessController.write(FMFileAccessController.java:484)
	at com.biglybt.core.diskmanager.file.impl.FMFileImpl.writeSupport(FMFileImpl.java:795)
	at com.biglybt.core.diskmanager.file.impl.FMFileLimited.write(FMFileLimited.java:310)
	at com.biglybt.core.diskmanager.cache.impl.CacheFileWithCache.multiBlockFlush(CacheFileWithCache.java:1102)
	... 9 more
Caused by: java.io.IOException: No space left on device
	at sun.nio.ch.FileDispatcherImpl.writev0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.writev(FileDispatcherImpl.java:72)
	at sun.nio.ch.IOUtil.write(IOUtil.java:148)
	at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:239)
	at java.nio.channels.FileChannel.write(FileChannel.java:414)
	at com.biglybt.core.diskmanager.file.impl.FMFileAccessLinear.write(FMFileAccessLinear.java:484)
	... 13 more
[00:00:55] [stderr] 
[00:00:55] [alert] Alert:3:Disk write error: flush fails, write fails, No space left on device
```

repeated 36 times

---
</details>

Additional info:

- The space ran out on just one of the storages.
- BiglyBT installation and data directories were on a different storage with enough space left.
- The crash is reproducible, restarting BiglyBT causes a re-check of all active torrents, after which the infringing download restarts crashing BiglyBT again.
- after 3rd BiglyBT restart, the infringing torrent has finally stopped with a correct error message

**Comment by parg** [comment]
When you say 'crashing BiglyBT' what actually happens? Process vanishes? UI locks up?

**Comment by rindeal** [comment]
> When you say 'crashing BiglyBT' what actually happens? Process vanishes? UI locks up?

Yes, I've seen both. When the UI locks up, I send SIGTERM and it exits cleanly. When it just vanishes, the state is unclean, e.g. some `~/.biglybt/*.config.saving` files were present. The crash is triggered from within the app, i.e. no error signal from kernel is recorded.

**Comment by parg** [comment]
If the UI hangs please follow the instructions from the Wiki (https://github.com/BiglySoftware/BiglyBT/wiki/Diagnostics) to try and grab some diagnostics

**Comment by rindeal** [comment]
I managed to reproduce the bug and hang the UI, while capturing more diagnostics this time.

[debug_1.log](https://github.com/BiglySoftware/BiglyBT/files/4691957/debug_1.log)

**Comment by parg** [comment]
Hmm. well the GUI thread looks potentially stuck in native code associated with the UI library we use

   SWT Thread: Runnable, 10413ms CPU, B/W: 55/16
        org.eclipse.swt.internal.gtk.GDK._gdk_flush(Native Method)
        org.eclipse.swt.internal.gtk.GDK.gdk_flush(GDK.java:1278)
        org.eclipse.swt.widgets.Control.setCursor(Control.java:5003)
        org.eclipse.swt.widgets.Control.setCursor(Control.java:4996)
        com.biglybt.ui.swt.skin.SWTSkinObjectText2$9.runWithDisplay(SWTSkinObjectText2.java:626)
        com.biglybt.ui.swt.utils.SWTRunnable.run(SWTRunnable.java:37)
        org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)

not a lot I can think of that can be done about that :(

**Comment by parg** [comment]
Does the UI come back-to-life if you free up some space when it is in this state?
