### ISSUE TITLE
Would you please provided us tutorial video guide to set up development environment ?

### ISSUE THREAD

**Issue by ghost** [BiglySoftware/BiglyBT#1900]
Would you please provided us tutorial video guide to set up development environment ?

I am very new to java with eclipse. would you please show me how to configure development environment , i want to learn how to develop with BiglyBT.

I have experience a little with eclipse. i know how to develop a spring boot application with eclipse. 

But i have no idea how to setup biglyBT source code. 
I am always in bugs.

Never let it works.

**Comment by parg** [comment]
What issues do you have building BiglyBT? I assume added https://github.com/BiglySoftware/BiglyBT as a repository in Eclipse?

**Comment by netroby** [comment]
mostly about jni ( java library path), about the aereg64

**Comment by parg** [comment]
So you've installed eclipse, opened the GIT perspective:

![image](https://user-images.githubusercontent.com/395293/101334136-5f84dc00-386f-11eb-991b-aa9b790381d9.png)

Cloned https://github.com/BiglySoftware/BiglyBT

Imported the two projects

![image](https://user-images.githubusercontent.com/395293/101334236-880cd600-386f-11eb-9c57-dfd7248c3deb.png)

![image](https://user-images.githubusercontent.com/395293/101334319-9e1a9680-386f-11eb-9092-c054adb737d0.png)

Added a debug configuration

![image](https://user-images.githubusercontent.com/395293/101334388-b7234780-386f-11eb-89a8-2c78207ce9d3.png)

and set the 'main class' to 

    com.biglybt.ui.Main

and it runs?

**Comment by parg** [comment]
Once you've figured it out make a video and I'll link to it

**Comment by netroby** [comment]
```
[INFO] Running com.biglybt.core.internat.MessageTextTest
java.lang.UnsatisfiedLinkError: no aereg64 in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
	at java.lang.Runtime.loadLibrary0(Runtime.java:871)
	at java.lang.System.loadLibrary(System.java:1124)
	at com.biglybt.platform.win32.access.impl.AEWin32AccessInterface.<clinit>(AEWin32AccessInterface.java:66)
	at com.biglybt.platform.win32.access.impl.AEWin32AccessImpl.isEnabled(AEWin32AccessImpl.java:84)
	at com.biglybt.platform.win32.access.impl.AEWin32AccessImpl.<init>(AEWin32AccessImpl.java:74)
	at com.biglybt.platform.win32.access.impl.AEWin32AccessImpl.getSingleton(AEWin32AccessImpl.java:56)
	at com.biglybt.platform.win32.access.AEWin32Manager.getAccessor(AEWin32Manager.java:36)
	at com.biglybt.platform.win32.PlatformManagerImpl.<init>(PlatformManagerImpl.java:158)
	at com.biglybt.platform.win32.PlatformManagerImpl.getSingleton(PlatformManagerImpl.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.biglybt.platform.PlatformManagerFactory.getPlatformManager(PlatformManagerFactory.java:77)
	at com.biglybt.core.util.SystemProperties.getUserPath(SystemProperties.java:277)
	at com.biglybt.core.util.FileUtil.readResilientConfigFile(FileUtil.java:812)
	at com.biglybt.core.config.impl.ConfigurationManager.load(ConfigurationManager.java:186)
	at com.biglybt.core.config.impl.ConfigurationManager.load(ConfigurationManager.java:238)
	at com.biglybt.core.config.impl.ConfigurationManager.getInstance(ConfigurationManager.java:108)
	at com.biglybt.core.config.COConfigurationManager.initialise(COConfigurationManager.java:274)
	at com.biglybt.core.impl.CoreImpl.<init>(CoreImpl.java:256)
	at com.biglybt.core.impl.CoreImpl.create(CoreImpl.java:174)
	at com.biglybt.core.CoreFactory.create(CoreFactory.java:43)
	at com.biglybt.testutil.junit5.DefaultTestCoreConfiguration.beforeAll(DefaultTestCoreConfiguration.java:35)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.lambda$invokeBeforeAllCallbacks$8(ClassTestDescriptor.java:361)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.invokeBeforeAllCallbacks(ClassTestDescriptor.java:361)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.before(ClassTestDescriptor.java:197)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.before(ClassTestDescriptor.java:77)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:132)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
This is BAD - fix me!
java.lang.Throwable
	at com.biglybt.core.util.SystemProperties.getDocPath(SystemProperties.java:480)
	at com.biglybt.core.config.impl.ConfigurationDefaults.<init>(ConfigurationDefaults.java:314)
	at com.biglybt.core.config.impl.ConfigurationDefaults.getInstance(ConfigurationDefaults.java:105)
	at com.biglybt.core.config.impl.ConfigurationManager.getIntParameter(ConfigurationManager.java:371)
	at com.biglybt.core.config.COConfigurationManager.getIntParameter(COConfigurationManager.java:347)
	at com.biglybt.core.config.impl.ConfigurationChecker.checkConfiguration(ConfigurationChecker.java:487)
	at com.biglybt.core.config.impl.ConfigurationManager.initialise(ConfigurationManager.java:175)
	at com.biglybt.core.config.impl.ConfigurationManager.getInstance(ConfigurationManager.java:110)
	at com.biglybt.core.config.COConfigurationManager.initialise(COConfigurationManager.java:274)
	at com.biglybt.core.impl.CoreImpl.<init>(CoreImpl.java:256)
	at com.biglybt.core.impl.CoreImpl.create(CoreImpl.java:174)
	at com.biglybt.core.CoreFactory.create(CoreFactory.java:43)
	at com.biglybt.testutil.junit5.DefaultTestCoreConfiguration.beforeAll(DefaultTestCoreConfiguration.java:35)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.lambda$invokeBeforeAllCallbacks$8(ClassTestDescriptor.java:361)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.invokeBeforeAllCallbacks(ClassTestDescriptor.java:361)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.before(ClassTestDescriptor.java:197)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.before(ClassTestDescriptor.java:77)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:132)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

**Comment by parg** [comment]
Why are you running this?

    [INFO] Running com.biglybt.core.internat.MessageTextTest

I don't advise you run anything other than "com.biglybt.ui.Main", forget src.test and forget junit.

Grab "aereg64.dll" from an installation of BiglyBT and place it in wherever the 'home' directory is for your run-configuration.

If you are unsure of where this is then go to Options->Plugins in BiglyBT (once you have it running) and look for the 'shared plugins' folder - the home directory is the parent of this.
