### ISSUE TITLE
Unhandled GUI issue with latest beta when using Options text search

### ISSUE THREAD

**Issue by ferdnyc** [BiglySoftware/BiglyBT#1960]
Like the subject says, got an unhandled GUI issue alert with 2.6.0.1_B17, seemingly while I was using the Search box in the Options window:

```text
java.lang.ClassCastException: class org.eclipse.swt.layout.GridData cannot be cast to class org.eclipse.swt.layout.RowData (org.eclipse.swt.layout.GridData and org.eclipse.swt.layout.RowData are in unnamed module of loader 'app')
	at org.eclipse.swt.layout.RowLayout.layoutHorizontal(RowLayout.java:253)
	at org.eclipse.swt.layout.RowLayout.computeSize(RowLayout.java:207)
	at org.eclipse.swt.widgets.Composite.computeSizeInPixels(Composite.java:254)
	at org.eclipse.swt.widgets.Control.computeSize(Control.java:842)
	at org.eclipse.swt.layout.GridData.computeSize(GridData.java:493)
	at org.eclipse.swt.layout.GridLayout.layout(GridLayout.java:225)
	at org.eclipse.swt.layout.GridLayout.computeSize(GridLayout.java:168)
	at org.eclipse.swt.widgets.Composite.computeSizeInPixels(Composite.java:254)
	at org.eclipse.swt.widgets.Group.computeSizeInPixels(Group.java:112)
	at org.eclipse.swt.widgets.Control.computeSize(Control.java:842)
	at org.eclipse.swt.layout.GridData.computeSize(GridData.java:493)
	at org.eclipse.swt.layout.GridLayout.layout(GridLayout.java:225)
	at org.eclipse.swt.layout.GridLayout.computeSize(GridLayout.java:168)
	at org.eclipse.swt.widgets.Composite.computeSizeInPixels(Composite.java:254)
	at org.eclipse.swt.widgets.Control.computeSize(Control.java:842)
	at org.eclipse.swt.custom.ScrolledCompositeLayout.computeSize(ScrolledCompositeLayout.java:36)
	at org.eclipse.swt.widgets.Composite.computeSizeInPixels(Composite.java:254)
	at org.eclipse.swt.widgets.Control.computeSize(Control.java:842)
	at org.eclipse.swt.custom.StackLayout.computeSize(StackLayout.java:100)
	at org.eclipse.swt.widgets.Composite.computeSizeInPixels(Composite.java:254)
	at org.eclipse.swt.widgets.Control.computeSize(Control.java:842)
	at org.eclipse.swt.layout.GridData.computeSize(GridData.java:493)
	at org.eclipse.swt.layout.GridLayout.layout(GridLayout.java:225)
	at org.eclipse.swt.layout.GridLayout.computeSize(GridLayout.java:168)
	at org.eclipse.swt.widgets.Composite.computeSizeInPixels(Composite.java:254)
	at org.eclipse.swt.widgets.Control.computeSize(Control.java:842)
	at org.eclipse.swt.custom.SashFormLayout.computeSize(SashFormLayout.java:50)
	at org.eclipse.swt.widgets.Composite.computeSizeInPixels(Composite.java:254)
	at org.eclipse.swt.widgets.Control.computeSize(Control.java:842)
	at org.eclipse.swt.layout.GridData.computeSize(GridData.java:493)
	at org.eclipse.swt.layout.GridLayout.layout(GridLayout.java:225)
	at org.eclipse.swt.layout.GridLayout.computeSize(GridLayout.java:168)
	at org.eclipse.swt.widgets.Composite.computeSizeInPixels(Composite.java:254)
	at org.eclipse.swt.widgets.Control.computeSize(Control.java:842)
	at org.eclipse.swt.layout.GridData.computeSize(GridData.java:493)
	at org.eclipse.swt.layout.GridLayout.layout(GridLayout.java:225)
	at org.eclipse.swt.layout.GridLayout.computeSize(GridLayout.java:168)
	at org.eclipse.swt.widgets.Composite.computeSizeInPixels(Composite.java:254)
	at org.eclipse.swt.widgets.Control.computeSize(Control.java:842)
	at org.eclipse.swt.layout.GridData.computeSize(GridData.java:493)
	at org.eclipse.swt.layout.GridLayout.layout(GridLayout.java:225)
	at org.eclipse.swt.layout.GridLayout.layout(GridLayout.java:201)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1812)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1818)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1818)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1818)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1818)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1818)
	at org.eclipse.swt.widgets.Composite.setLayoutDeferred(Composite.java:1659)
	at org.eclipse.swt.widgets.Display.runDeferredLayouts(Display.java:4977)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4433)
	at com.biglybt.ui.swt.mainwindow.SWTThread.<init>(SWTThread.java:400)
	at com.biglybt.ui.swt.mainwindow.SWTThread.createInstance(SWTThread.java:58)
	at com.biglybt.ui.swt.Initializer.<init>(Initializer.java:181)
	at com.biglybt.ui.swt.UI.takeMainThread(UI.java:136)
	at com.biglybt.ui.Main.main(Main.java:247)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.biglybt.launcher.Launcher$1.run(Launcher.java:48)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

#### System details
```text
Java 11.0.9.1 (64 bit)
  Red Hat, Inc.
/usr/lib/jvm/java-11-openjdk-11.0.9.11-9.fc33.x86_64

SWT v4934r6, gtk/3.24.24, zoom=100, dpi=96
Linux v5.10.6-200.fc33.x86_64, amd64 (64 bit)
B2.6.0.1_B17/4 az3
```

**Comment by TuxPaper** [comment]
Might be able to find the offending config page by clicking on every config section and subsection until the same error throws and noting which screen it threw on.

**Comment by ferdnyc** [comment]
Understood, I'll see if I can even get it to happen again at all. If not, then doesn't seem like it's anything worth worrying too much about.

I'd originally thought the error occurred during the search filtering, since it seemed to take seconds longer than I would've expected before finally updating the pane's contents to highlight matches. Is that possible, or was it definitely the result of showing one of the options categories? 

(Hmm, I wonder if I might've clicked a category *while* it was still filtering, maybe?)

**Comment by ferdnyc** [comment]
@TuxPaper @parg 

My suspicion is confirmed; the traceback occurs when the search/filter text field at the bottom of the Options category list is filled in for the first time. No clicks are required — by the time the wait cursor stops spinning and the display updates to highlight matches, there's already a notification icon showing for the error message.

Subsequent searches don't trigger any additional notifications, but looking at the Console the same traceback does appear to be logged multiple times for each use of the search box. Possibly once for each additional filter-string character typed after the first one. (At least, my most recent search string was 4 letters long, and I see three tracebacks logged in quick succession.)

**Comment by parg** [comment]
Do you have any non-standard plugins installed?

**Comment by ferdnyc** [comment]
Not at all. They're all from the official list, nearly every one named 'az'-something except for mlab, mldht, rssfeed, and xmwebui. And mlab isn't even loaded.

**Comment by ferdnyc** [comment]
Oh, sorry, missed dorkboxupdater. That one too (also not loaded).

**Comment by parg** [comment]
Ah, reproduced it, I'll investigate

**Comment by parg** [comment]
fixed next beta, thanks!

**Comment by ferdnyc** [comment]
Indeed. In _B21, fixed it be.
