### ISSUE TITLE
Crash at startup on macOS 11 with JRE 11, 15, 16

### ISSUE THREAD

**Issue by kinosang** [BiglySoftware/BiglyBT#2051]
* OS and version macOS Big Sur 11.2
* BiglyBT Version Number almost every published version (tested with 1.9.0.0 ~ 2.7.0.2)

With JRE 1.8, it works well. But it crashes at startup with JRE 11, 15, 16.

I've tried with system-wide JDK and standalone JRE.bundle in `.install4j`.

Both Adopt 8 and Oracle OpenJDK 1.8 work well. But Adopt and Oracle OpenJDK 11~16 not.

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.biglybt.core.util.spi.AENameServiceJava9 (file:/Applications/BiglyBT/.biglybt/BiglyBT.jar) to field java.net.InetAddress.impl
WARNING: Please consider reporting this to the maintainers of com.biglybt.core.util.spi.AENameServiceJava9
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
DEBUG::Tue Mar 23 13:10:42 CST 2021::com.biglybt.core.impl.CoreImpl::create::176:
  Initialisation failed
    CoreFactory::create::43, Main::main::200, NativeMethodAccessorImpl::invoke0::-2, NativeMethodAccessorImpl::invoke::62, DelegatingMethodAccessorImpl::invoke::43, Method::invoke::566, Launcher$1::run::48, Launcher::launch::65, Launcher::checkAndLaunch::83, Main::main::80, NativeMethodAccessorImpl::invoke0::-2, NativeMethodAccessorImpl::invoke::62, DelegatingMethodAccessorImpl::invoke::43, Method::invoke::566, LauncherEngine::launch::84, MacLauncher::main::52
java.util.IllformedLocaleException: Ill-formed variant: #Hans [at index 0]
	at java.base/java.util.Locale$Builder.setVariant(Locale.java:2658)
	at com.biglybt.core.internat.MessageText.parseFormattedLocaleString(MessageText.java:879)
	at com.biglybt.core.internat.MessageText.loadBundle(MessageText.java:151)
	at com.biglybt.core.internat.MessageText.loadBundle(MessageText.java:144)
	at com.biglybt.core.impl.CoreImpl.<init>(CoreImpl.java:264)
	at com.biglybt.core.impl.CoreImpl.create(CoreImpl.java:176)
	at com.biglybt.core.CoreFactory.create(CoreFactory.java:43)
	at com.biglybt.ui.Main.main(Main.java:200)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.biglybt.launcher.Launcher$1.run(Launcher.java:48)
	at com.biglybt.launcher.Launcher.launch(Launcher.java:65)
	at com.biglybt.launcher.Launcher.checkAndLaunch(Launcher.java:83)
	at com.biglybt.ui.Main.main(Main.java:80)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.install4j.runtime.launcher.MacLauncher.main(MacLauncher.java:52)
Launch failed
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.biglybt.launcher.Launcher$1.run(Launcher.java:48)
	at com.biglybt.launcher.Launcher.launch(Launcher.java:65)
	at com.biglybt.launcher.Launcher.checkAndLaunch(Launcher.java:83)
	at com.biglybt.ui.Main.main(Main.java:80)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.install4j.runtime.launcher.MacLauncher.main(MacLauncher.java:52)
Caused by: java.util.IllformedLocaleException: Ill-formed variant: #Hans [at index 0]
	at java.base/java.util.Locale$Builder.setVariant(Locale.java:2658)
	at com.biglybt.core.internat.MessageText.parseFormattedLocaleString(MessageText.java:879)
	at com.biglybt.core.internat.MessageText.loadBundle(MessageText.java:151)
	at com.biglybt.core.internat.MessageText.loadBundle(MessageText.java:144)
	at com.biglybt.core.impl.CoreImpl.<init>(CoreImpl.java:264)
	at com.biglybt.core.impl.CoreImpl.create(CoreImpl.java:176)
	at com.biglybt.core.CoreFactory.create(CoreFactory.java:43)
	at com.biglybt.ui.Main.main(Main.java:200)
	... 14 more
java.lang.SecurityException: VM exit operation prohibited
	at com.biglybt.core.security.impl.SESecurityManagerImpl$ClientSecurityManager.checkExit(SESecurityManagerImpl.java:1881)
	at java.base/java.lang.Runtime.exit(Runtime.java:114)
	at java.base/java.lang.System.exit(System.java:1752)
	at com.biglybt.launcher.Launcher$1.run(Launcher.java:56)
	at com.biglybt.launcher.Launcher.launch(Launcher.java:65)
	at com.biglybt.launcher.Launcher.checkAndLaunch(Launcher.java:83)
	at com.biglybt.ui.Main.main(Main.java:80)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.install4j.runtime.launcher.MacLauncher.main(MacLauncher.java:52)
```

**Comment by parg** [comment]
What locale are you using BiglyBT in? It seems that Java started verifying the locale variant string from Java 11 onwards. The error is being thrown when trying to restore your previously selected locale (which appears to have the value #Hans, something I can't see in any of our language translations...)

**Comment by kinosang** [comment]
@parg #Hans seems the code for zh-Hans / zh-CN in newer JRE on macOS.

**Comment by parg** [comment]
Ah, https://stackoverflow.com/questions/29536631/getting-locale-variant-for-simplified-chinese - so did you switch to zh_CN or is that your OS default perhaps?

**Comment by parg** [comment]
you beat me to it!

**Comment by kinosang** [comment]
@parg I didn't change any thing in BiglyBT (I've tried to remove all the config files for BiglyBT before), it seems if I use Simplified Chinese for my OS default, the BiglyBT will get Hans instead of zh_CN.

**Comment by kinosang** [comment]
@parg It works well after I change the BiglyBT preferences.

I have to run BiglyBT with java 1.8, then change the Interface - Language to English. After changing the language, I can switch to JRE 11.

**Comment by parg** [comment]
I'll take a look at fixing it in future releases, thanks for reporting!
