### ISSUE TITLE
biglybt crashes on openjdk 16

### ISSUE THREAD

**Issue by moham96** [BiglySoftware/BiglyBT#2202]
* OS and version: manjaro linux (rolling)
* BiglyBT Version Number: 2.8.0.0
* For *nix: Desktop Environment: deepin

Biglybt is not working correctly with java 16(openjdk 16 to be specific), it either crashes or loads only the menu bar and then get stuck:
LOG:

```
Starting BiglyBT...
Suitable java version found [java = openjdk 16.0.2 2021-07-20]
Using swt/swt-x86_64.jar v4.942
java.lang.reflect.InaccessibleObjectException: Unable to make field private static transient java.net.InetAddress$NameService java.net.InetAddress.nameService accessible: module java.base does not "opens java.net" to unnamed module @467aecef
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:171)
        at com.biglybt.core.util.spi.AENameServiceJava12.init(AENameServiceJava12.java:38)
        at com.biglybt.core.config.COConfigurationManager.preInitialise(COConfigurationManager.java:240)
        at com.biglybt.core.config.impl.ConfigurationChecker.setSystemProperties(ConfigurationChecker.java:85)
        at com.biglybt.core.config.impl.ConfigurationManager.initialise(ConfigurationManager.java:177)
        at com.biglybt.core.config.impl.ConfigurationManager.getInstance(ConfigurationManager.java:110)
        at com.biglybt.core.config.COConfigurationManager.getStringParameter(COConfigurationManager.java:304)
        at com.biglybt.platform.unix.ScriptBeforeStartup.main(ScriptBeforeStartup.java:62)

(java:45432): GLib-GObject-CRITICAL **: 13:55:49.142: g_value_set_boxed: assertion 'G_VALUE_HOLDS_BOXED (value)' failed

(java:45432): Gtk-WARNING **: 13:55:49.149: Theme parsing error: gtk.css:3611:22: 'none' is not a valid color name
Loading BiglyBT:
java.lang.reflect.InaccessibleObjectException: Unable to make field private static transient java.net.InetAddress$NameService java.net.InetAddress.nameService accessible: module java.base does not "opens java.net" to unnamed module @5104ce6a
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:171)
        at com.biglybt.core.util.spi.AENameServiceJava12.init(AENameServiceJava12.java:38)
        at com.biglybt.core.config.COConfigurationManager.preInitialise(COConfigurationManager.java:240)
        at com.biglybt.ui.Main.main(Main.java:85)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at com.biglybt.launcher.Launcher$1.run(Launcher.java:48)
        at java.base/java.lang.Thread.run(Thread.java:831)
changeLocale: *Default Language* != English (United States). Searching without country..
changeLocale: Searching for language English in *any* country..
changeLocale: no message properties for Locale 'English (United States)' (en_US), using 'English (default)'

(java:45465): GLib-GObject-CRITICAL **: 13:55:50.010: g_value_set_boxed: assertion 'G_VALUE_HOLDS_BOXED (value)' failed

(java:45465): Gtk-WARNING **: 13:55:50.017: Theme parsing error: gtk.css:3611:22: 'none' is not a valid color name
UIFunctions/ImageLoad took 0ms
new shell took 25ms
new shell setup took 25ms
skin init took 25ms
MainMenu init took 25ms
pre skin widgets init took 0ms
skin widgets (1/2) init took 75ms
skin widgets (2/2) init took 50ms
pre SWTInstance init took 0ms
Init Core Columns took 25ms
SWTInstance init took 0ms
shell.layout took 0ms
---------SHOWN AT 1628938550313;337ms
---------DONE DISPATCH AT 1628938550364;388ms
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Aug 14, 2021 1:55:50 PM com.sun.jna.Native$1 uncaughtException
WARNING: JNA: Callback dorkbox.util.jna.linux.GtkEventDispatch$5@2d08d276 threw the following exception
org.eclipse.swt.SWTException: Invalid thread access
        at org.eclipse.swt.SWT.error(SWT.java:4889)
        at org.eclipse.swt.SWT.error(SWT.java:4804)
        at org.eclipse.swt.SWT.error(SWT.java:4775)
        at org.eclipse.swt.widgets.Widget.error(Widget.java:555)
        at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:471)
        at org.eclipse.swt.widgets.Control.isVisible(Control.java:4514)
        at org.eclipse.swt.widgets.ProgressBar.timerProc(ProgressBar.java:311)
        at org.eclipse.swt.widgets.Display.windowTimerProc(Display.java:6101)
        at dorkbox.util.jna.linux.Gtk3.g_main_loop_run(Native Method)
        at dorkbox.util.jna.linux.GtkEventDispatch$2.run(GtkEventDispatch.java:107)

---------READY AT 1628938550790;814ms
shell.open took 477ms
processStartupDMS took 0ms
postPluginSetup init took 0ms
Locale Initializing took 25ms
Core Initializing took 150ms
java.lang.UnsupportedOperationException: IPv6 not available
        at java.base/sun.nio.ch.DatagramChannelImpl.<init>(DatagramChannelImpl.java:183)
        at java.base/sun.nio.ch.SelectorProviderImpl.openDatagramChannel(SelectorProviderImpl.java:59)
        at java.base/java.nio.channels.DatagramChannel.open(DatagramChannel.java:197)
        at lbms.plugins.mldht.kad.utils.AddressUtils.getDefaultRoute(AddressUtils.java:215)
        at lbms.plugins.mldht.kad.DHT.start(DHT.java:734)
        at lbms.plugins.mldht.azureus.MlDHTPlugin$9.runSupport(MlDHTPlugin.java:670)
        at com.biglybt.core.util.AsyncDispatcher$1.run(AsyncDispatcher.java:168)
        at com.biglybt.core.util.AEThread2$threadWrapper.run(AEThread2.java:317)
Exit from BiglyBT complete
java.lang.reflect.InaccessibleObjectException: Unable to make field private static transient java.net.InetAddress$NameService java.net.InetAddress.nameService accessible: module java.base does not "opens java.net" to unnamed module @4bbfb90a
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:171)
        at com.biglybt.core.util.spi.AENameServiceJava12.init(AENameServiceJava12.java:38)
        at com.biglybt.core.config.COConfigurationManager.preInitialise(COConfigurationManager.java:240)
        at com.biglybt.core.config.impl.ConfigurationChecker.setSystemProperties(ConfigurationChecker.java:85)
        at com.biglybt.core.config.impl.ConfigurationManager.initialise(ConfigurationManager.java:177)
        at com.biglybt.core.config.impl.ConfigurationManager.getInstance(ConfigurationManager.java:110)
        at com.biglybt.core.config.COConfigurationManager.getStringParameter(COConfigurationManager.java:304)
        at com.biglybt.platform.unix.ScriptAfterShutdown.main(ScriptAfterShutdown.java:43)
No shutdown tasks to do
BiglyBT TERMINATED.
```

**Comment by TuxPaper** [comment]
Try removing `dorkbox-systemtray.jar` from the BiglyBT install directory (or temporarily move it somewhere else) and see if that changes anything. At the very least it will rule out one exception thrown :)
