### ISSUE TITLE
SWT throws error during startup

### ISSUE THREAD

**Issue by csylvain** [BiglySoftware/BiglyBT#2336]
after an update added the command line parameter "-Dazureus.script.version=10", the initial blank BiglyBT frame appears, then disappears. not sure how to troubleshoot. should i consider removing the ALL-UNNAMED line from java.vmoptions?

shell.layout took 25ms
---------SHOWN AT 1637529159400;1203ms
---------DONE DISPATCH AT 1637529159642;1439ms
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
JNA: Callback dorkbox.util.jna.linux.GtkEventDispatch$5@dcaa304 threw the following exception:
org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(SWT.java:4889)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.SWT.error(SWT.java:4775)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:555)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:471)
	at org.eclipse.swt.widgets.Control.isVisible(Control.java:4514)
	at org.eclipse.swt.widgets.ProgressBar.timerProc(ProgressBar.java:311)
	at org.eclipse.swt.widgets.Display.windowTimerProc(Display.java:6101)
	at dorkbox.util.jna.linux.Gtk3.g_main_loop_run(Native Method)
	at dorkbox.util.jna.linux.GtkEventDispatch$2.run(GtkEventDispatch.java:107)
---------READY AT 1637529160345;2142ms

current system particulars:
(unchanged since last report) (unable to obtain info from Help->About because empty window does not stick around)

**Comment by TuxPaper** [comment]
Try moving `dorkbox-systemtray.jar` out of the biglybt app dir (or rename it to something other than .jar extension) and see if that helps.

**Comment by csylvain** [comment]
```
$ mv -v dorkbox-systemtray.jar dorkbox-systemtray.jar.renamed
renamed 'dorkbox-systemtray.jar' -> 'dorkbox-systemtray.jar.renamed'
```

**back in business** -- thanks!

pre SWTInstance init took 5ms
Init Core Columns took 60ms
SWTInstance init took 21ms
shell.layout took 0ms
---------SHOWN AT 1637540333476;1121ms
---------DONE DISPATCH AT 1637540333780;1421ms
DEBUG::Sun Nov 21 19:18:53 EST 2021  com.biglybt.ui.swt.systray.TrayDork
---------READY AT 1637540333805;1446ms
shell.open took 329ms
processStartupDMS took 0ms
postPluginSetup init took 0ms
