### ISSUE TITLE
Warning on startup.

### ISSUE THREAD

**Issue by Achaean** [BiglySoftware/BiglyBT#2530]
No hint if it's a serious event or just random noise!  :-)

BBT just installed (official installer) on PCLinux.

```
>java -version
java version "15.0.2" 2021-01-19
Java(TM) SE Runtime Environment (build 15.0.2+7-27)
Java HotSpot(TM) 64-Bit Server VM (build 15.0.2+7-27, mixed mode, sharing)
>
```

```
Java 15.0.2 (64 bit)
  Oracle Corporation
/usr/lib/jvm/jdk-15.0.2

SWT v4942r22, gtk/3.24.33, zoom=100, dpi=96
Linux v5.16.20-pclos1, amd64 (64 bit)
B3.0.0.0/4 az3
```

Console's output:
```
>./biglybt
Starting BiglyBT...
Suitable java version found [java = java 15.0.2 2021-01-19]
Using swt/swt-x86_64.jar v4.942
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.biglybt.core.util.spi.AENameServiceJava12 (file:/home/giorgos/biglybt/BiglyBT.jar) to field java.net.InetAddress.nameService
WARNING: Please consider reporting this to the maintainers of com.biglybt.core.util.spi.AENameServiceJava12
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Loading BiglyBT:
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.biglybt.core.util.spi.AENameServiceJava12 (file:/home/giorgos/biglybt/BiglyBT.jar) to field java.net.InetAddress.nameService
WARNING: Please consider reporting this to the maintainers of com.biglybt.core.util.spi.AENameServiceJava12
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
UIFunctions/ImageLoad took 25ms
new shell took 125ms
new shell setup took 101ms
skin init took 157ms
MainMenu init took 154ms
pre skin widgets init took 51ms
skin widgets (1/2) init took 326ms
skin widgets (2/2) init took 176ms
pre SWTInstance init took 0ms
Init Core Columns took 101ms
SWTInstance init took 0ms
shell.layout took 76ms
---------SHOWN AT 1650168959173;1659ms
---------DONE DISPATCH AT 1650168959651;2137ms
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
DEBUG::Sun Apr 17 07:16:00 EEST 2022  com/sun/jna/Callback
---------READY AT 1650168960153;2639ms
shell.open took 980ms
processStartupDMS took 0ms
postPluginSetup init took 0ms
Locale Initializing took 13ms
Continent file not found
INFO: Native CPUID library libjcpuid-x86-linux.so loaded from resource
INFO: Resource name [libjbigi-linux-jaguar_64.so] was not found
INFO: Resource name [libjbigi-linux-jaguar.so] was not found
INFO: Loaded library: jar:file:/home/giorgos/.biglybt/plugins/azneti2phelper/jbigi-linux_0.4.jar!/libjbigi-linux-bobcat_64.so
INFO: Native BigInteger library libjbigi-linux-bobcat_64.so loaded from resource
Core Initializing took 1305ms
Warning - No client apps or router console configured - we are just a router
java.net.SocketException: Το δίκτυο δεν είναι προσπελάσιμο
at java.base/sun.nio.ch.Net.connect0(Native Method)
at java.base/sun.nio.ch.Net.connect(Net.java:574)
at java.base/sun.nio.ch.DatagramChannelImpl.connect(DatagramChannelImpl.java:1243)
at java.base/sun.nio.ch.DatagramChannelImpl.connect(DatagramChannelImpl.java:1202)
at lbms.plugins.mldht.kad.utils.AddressUtils.getDefaultRoute(AddressUtils.java:221)
at lbms.plugins.mldht.kad.DHT.start(DHT.java:734)
at lbms.plugins.mldht.azureus.MlDHTPlugin$9.runSupport(MlDHTPlugin.java:670)
at com.biglybt.core.util.AsyncDispatcher$1.run(AsyncDispatcher.java:168)
at com.biglybt.core.util.AEThread2$threadWrapper.run(AEThread2.java:317)
core.stop
CRIT  [enDispatcher] net.i2p.router.Router         : Shutdown imminent
CRIT  [enDispatcher] net.i2p.router.Router         : Shutdown(3) complete
core.stop done in 3428
Exit from BiglyBT complete
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.biglybt.core.util.spi.AENameServiceJava12 (file:/home/giorgos/biglybt/BiglyBT.jar) to field java.net.InetAddress.nameService
WARNING: Please consider reporting this to the maintainers of com.biglybt.core.util.spi.AENameServiceJava12
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
No shutdown tasks to do
BiglyBT TERMINATED.
>
```
[debug.zip](https://github.com/BiglySoftware/BiglyBT/files/8501290/debug.zip)

**Comment by parg** [comment]
random noise!

**Comment by Achaean** [comment]
Nice!!!  :-)

Have a happy Easter holiday season!
Hopefully a peaceful one.

**Comment by parg** [comment]
You too!
