### ISSUE TITLE
azmsgsync File name too long?

### ISSUE THREAD

**Issue by drelephant** [BiglySoftware/BiglyBT#2556]
Using BiglyBT 3.0.0.0 on Ubuntu 18.04.6 LTS (Gnome), often over VNC.

BiglyBT crashes every now and then, I still haven't worked out what's causing it but the GUI becomes unclickable and doesn't refresh the display.

Often I can still connect from the Android app when this happens however.

Not sure if it's related but I see a lot of errors on the console about filename too long:
````
[01:13:50] [stderr]     FileUtil::writeResilientFile::663, FileUtil::writeResilientFile::644, MsgSyncHandler::saveMessages::6077, MsgSyncHandler::timerTick::2139, MsgSyncPlugin$3::perform::257, TimerEventPeriodic::perform::104, TimerEvent::runSupport::133, AERunnable::run::36, ThreadPool::runIt::336, ThreadPool$threadPoolWorker::run::726, AEThread2$threadWrapper::run::317
[01:13:50] [stderr] java.io.FileNotFoundException: /home/redacted/.biglybt/plugins/azmsgsync/save/IJUWO3DZIJKDUICJGJIDUICEJZJSARTFMVSFW4DLHVAVGM2XGJLUQRSHIZIU2RBSJNKTOWRSLFCDESKNLFEVUSRVKJDTGNCBK42FKUSQJNIFCN2OJJJEGWSLJJKTEUCEKI2ESR2HIVBUMTCKJVHVCTKBKJATOMSTIRFDIMSZEZZG6PJRLUp.dat.saving (File name too long)
[01:13:50] [stderr] 	at java.base/java.io.FileOutputStream.open0(Native Method)
[01:13:50] [stderr] 	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
[01:13:50] [stderr] 	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
[01:13:50] [stderr] 	at com.biglybt.core.util.FileHandler.newFileOutputStream(FileHandler.java:69)
[01:13:50] [stderr] 	at com.biglybt.core.util.FileUtil.newFileOutputStream(FileUtil.java:2519)
[01:13:50] [stderr] 	at com.biglybt.core.util.FileUtil.writeResilientFile(FileUtil.java:744)
[01:13:50] [stderr] 	at com.biglybt.core.util.FileUtil.writeResilientFile(FileUtil.java:684)
[01:13:50] [stderr] 	at com.biglybt.core.util.FileUtil.writeResilientFile(FileUtil.java:663)
[01:13:50] [stderr] 	at com.biglybt.core.util.FileUtil.writeResilientFile(FileUtil.java:644)
[01:13:50] [stderr] 	at com.vuze.plugins.azmsgsync.MsgSyncHandler.saveMessages(MsgSyncHandler.java:6077)
[01:13:50] [stderr] 	at com.vuze.plugins.azmsgsync.MsgSyncHandler.timerTick(MsgSyncHandler.java:2139)
[01:13:50] [stderr] 	at com.vuze.plugins.azmsgsync.MsgSyncPlugin$3.perform(MsgSyncPlugin.java:257)
[01:13:50] [stderr] 	at com.biglybt.core.util.TimerEventPeriodic.perform(TimerEventPeriodic.java:104)
[01:13:50] [stderr] 	at com.biglybt.core.util.TimerEvent.runSupport(TimerEvent.java:133)
[01:13:50] [stderr] 	at com.biglybt.core.util.AERunnable.run(AERunnable.java:36)
[01:13:50] [stderr] 	at com.biglybt.core.util.ThreadPool.runIt(ThreadPool.java:336)
[01:13:50] [stderr] 	at com.biglybt.core.util.ThreadPool$threadPoolWorker.run(ThreadPool.java:726)
[01:13:50] [stderr] 	at com.biglybt.core.util.AEThread2$threadWrapper.run(AEThread2.java:317)
[01:13:50] java.io.FileNotFoundException: /home/redacted/.biglybt/plugins/azmsgsync/save/IJUWO3DZIJKDUICJGJIDUICEJZJSARTFMVSFW4DLHVAVGM2XGJLUQRSHIZIU2RBSJNKTOWRSLFCDESKNLFEVUSRVKJDTGNCBK42FKUSQJNIFCN2OJJJEGWSLJJKTEUCEKI2ESR2HIVBUMTCKJVHVCTKBKJATOMSTIRFDIMSZEZZG6PJRLUp.dat.saving (File name too long)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at com.biglybt.core.util.FileHandler.newFileOutputStream(FileHandler.java:69)
	at com.biglybt.core.util.FileUtil.newFileOutputStream(FileUtil.java:2519)
	at com.biglybt.core.util.FileUtil.writeResilientFile(FileUtil.java:744)
	at com.biglybt.core.util.FileUtil.writeResilientFile(FileUtil.java:684)
	at com.biglybt.core.util.FileUtil.writeResilientFile(FileUtil.java:663)
	at com.biglybt.core.util.FileUtil.writeResilientFile(FileUtil.java:644)
	at com.vuze.plugins.azmsgsync.MsgSyncHandler.saveMessages(MsgSyncHandler.java:6077)
	at com.vuze.plugins.azmsgsync.MsgSyncHandler.timerTick(MsgSyncHandler.java:2139)
	at com.vuze.plugins.azmsgsync.MsgSyncPlugin$3.perform(MsgSyncPlugin.java:257)
	at com.biglybt.core.util.TimerEventPeriodic.perform(TimerEventPeriodic.java:104)
	at com.biglybt.core.util.TimerEvent.runSupport(TimerEvent.java:133)
	at com.biglybt.core.util.AERunnable.run(AERunnable.java:36)
	at com.biglybt.core.util.ThreadPool.runIt(ThreadPool.java:336)
	at com.biglybt.core.util.ThreadPool$threadPoolWorker.run(ThreadPool.java:726)
	at com.biglybt.core.util.AEThread2$threadWrapper.run(AEThread2.java:317)
````

How can I fix these errors and hopefully stop biglybt from freezing up?

**Comment by parg** [comment]
Doesn't seem very long to me, do you have some lame file system?

I can't see how that error can be related to BiglyBT freezing. The usual cause of that is low Java VM memory, do you have a lot of active downloads? Check https://github.com/BiglySoftware/BiglyBT/wiki/Diagnostics for some info.

**Comment by drelephant** [comment]
It's ext4 with encrypted /home, don't think that should make a difference though?

Definitely getting that error though, even from the command line:
`touch '/home/redacted/.biglybt/plugins/azmsgsync/save/IJUWO3DZIJKDUICJGJIDUICEJZJSARTFMVSFW4DLHVAVGM2XGJLUQRSHIZIU2RBSJNKTOWRSLFCDESKNLFEVUSRVKJDTGNCBK42FKUSQJNIFCN2OJJJEGWSLJJKTEUCEKI2ESR2HIVBUMTCKJVHVCTKBKJATOMSTIRFDIMSZEZZG6PJRLUp.dat.saving'`

`touch: cannot touch '/home/redacted/.biglybt/plugins/azmsgsync/save/IJUWO3DZIJKDUICJGJIDUICEJZJSARTFMVSFW4DLHVAVGM2XGJLUQRSHIZIU2RBSJNKTOWRSLFCDESKNLFEVUSRVKJDTGNCBK42FKUSQJNIFCN2OJJJEGWSLJJKTEUCEKI2ESR2HIVBUMTCKJVHVCTKBKJATOMSTIRFDIMSZEZZG6PJRLUp.dat.saving': File name too long`

But I know ext4 is meant to allow 255 byte names and unlimited path size, so it's very odd.

I have only about 10 active downloads?

**Comment by parg** [comment]
I've fixed things if you join the beta program

**Comment by drelephant** [comment]
OK great, just joined.

Thanks again!!
