### ISSUE TITLE
Context menu broken in tables, with _B44

### ISSUE THREAD

**Issue by ferdnyc** [BiglySoftware/BiglyBT#2612]
Running 3.0.0.1_B44, this gets logged whenever I try to right-click on a torrent row in the Library tables. (The context menu does not appear.)

```
[11:51:58.868] {alert} Alert:3:An unhandled error occurred in the GUI, further errors may be reported.
[11:51:58.868] {stderr} DEBUG::Thu Jun 30 11:51:58 EDT 2022::com.biglybt.ui.swt.mainwindow.SWTThread::<init>::459:
[11:51:58.868] {stderr}   java.lang.ClassCastException: class com.biglybt.ui.swt.views.table.painted.TableViewPainted$27 cannot be cast to class com.biglybt.ui.common.table.TableView (com.biglybt.ui.swt.views.table.painted.TableViewPainted$27 and com.biglybt.ui.common.table.TableView are in unnamed module of loader 'app')
	at com.biglybt.ui.swt.MenuBuildUtils$MenuItemPluginMenuControllerImpl.notifyFillListeners(MenuBuildUtils.java:228)
	at com.biglybt.ui.swt.MenuBuildUtils.addPluginMenuItems(MenuBuildUtils.java:296)
	at com.biglybt.ui.swt.views.table.impl.TableViewSWT_Common.fillMenu(TableViewSWT_Common.java:1018)
	at com.biglybt.ui.swt.views.table.painted.TableViewPainted$28.buildMenu(TableViewPainted.java:3164)
	at com.biglybt.ui.swt.MenuBuildUtils$1.menuShown(MenuBuildUtils.java:144)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:259)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5831)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1427)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1453)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1432)
	at org.eclipse.swt.widgets.Menu._setVisible(Menu.java:248)
	at org.eclipse.swt.widgets.Display.runPopups(Display.java:5134)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4560)
	at com.biglybt.ui.swt.mainwindow.SWTThread.<init>(SWTThread.java:438)
	at com.biglybt.ui.swt.mainwindow.SWTThread.createInstance(SWTThread.java:58)
	at com.biglybt.ui.swt.Initializer.<init>(Initializer.java:181)
	at com.biglybt.ui.swt.UI.takeMainThread(UI.java:162)
	at com.biglybt.ui.Main.main(Main.java:247)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.biglybt.launcher.Launcher$1.run(Launcher.java:48)
	at java.base/java.lang.Thread.run(Thread.java:829)
[11:51:58.868] {stderr} 
```

#### System block
Java 11.0.15 (64 bit)
  Red Hat, Inc.
/usr/lib/jvm/java-11-openjdk-11.0.15.0.10-1.fc36.x86_64

SWT v4942r22, gtk/3.24.34, zoom=100, dpi=96
Linux v5.17.12-300.fc36.x86_64, amd64 (64 bit)
B3.0.0.1_B44/4 az3

**Comment by ferdnyc** [comment]
If I hide the Tags column, it fixes the issue, so looks almost certain this is due to 1662d45c8ca197348054d6068212a889c0e4a1ba

**Comment by parg** [comment]
Yah, I can see the borkage! Thanks

**Comment by ferdnyc** [comment]
Fixed it be, in _B45. :+1:
