### ISSUE TITLE
InaccessibleObjectException when launching in Ubuntu 22.04

### ISSUE THREAD

**Issue by WrichikBasu** [BiglySoftware/BiglyBT#2696]
* OS and version: Ubuntu 22.04.1
* BiglyBT Version Number: biglybt (2.9.0.0-3) [universe]
* For *nix: Desktop Environment: Gnome 42.2

I installed BiglyBT on my system using `sudo apt install biglybt`. Upon launching it from the Gnome applications page, nothing came up. When I executed it from the terminal, got the following exception:

```java
$ biglybt
java.lang.reflect.InaccessibleObjectException: Unable to make field private static transient java.net.InetAddress$NameService java.net.InetAddress.nameService accessible: module java.base does not "opens java.net" to unnamed module @3e07d849
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at com.biglybt.core.util.spi.AENameServiceJava12.init(AENameServiceJava12.java:38)
	at com.biglybt.core.config.COConfigurationManager.preInitialise(COConfigurationManager.java:240)
	at com.biglybt.ui.Main.main(Main.java:85)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.biglybt.launcher.Launcher$1.run(Launcher.java:48)
	at java.base/java.lang.Thread.run(Thread.java:833)
DEBUG::Tue Aug 30 22:43:50 IST 2022::com.biglybt.core.security.impl.SESecurityManagerImpl::initialise::201:
  No SSL provider available
    SESecurityManager::initialise::55, ConfigurationChecker::setSystemProperties::287, ConfigurationManager::initialise::177, ConfigurationManager::getInstance::110, COConfigurationManager::initialise::274, CoreImpl::<init>::258, CoreImpl::create::176, CoreFactory::create::43, Main::main::200, NativeMethodAccessorImpl::invoke0::-2, NativeMethodAccessorImpl::invoke::77, DelegatingMethodAccessorImpl::invoke::43, Method::invoke::568, Launcher$1::run::48, Thread::run::833
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by com.biglybt.core.security.impl.SESecurityManagerImpl (file:/usr/share/java/biglybt-core.jar)
WARNING: Please consider reporting this to the maintainers of com.biglybt.core.security.impl.SESecurityManagerImpl
WARNING: System::setSecurityManager will be removed in a future release
Launch failed
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.biglybt.launcher.Launcher$1.run(Launcher.java:48)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
	no swt-gtk-4944r26 in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
	no swt-gtk in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
	no swt in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
	Can't load library: /usr/lib/jni/libswt-gtk.so
	Can't load library: /usr/lib/jni/libswt.so
	Can't load library: /home/wrichik-basu/.swt/lib/linux/x86_64/libswt-gtk-4944r26.so
	Can't load library: /home/wrichik-basu/.swt/lib/linux/x86_64/libswt-gtk.so
	Can't load library: /home/wrichik-basu/.swt/lib/linux/x86_64/libswt.so

	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:352)
	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:257)
	at org.eclipse.swt.internal.C.<clinit>(C.java:19)
	at org.eclipse.swt.internal.Converter.wcsToMbcs(Converter.java:209)
	at org.eclipse.swt.internal.Converter.wcsToMbcs(Converter.java:155)
	at org.eclipse.swt.widgets.Display.<clinit>(Display.java:165)
	at com.biglybt.ui.swt.mainwindow.SWTThread.<init>(SWTThread.java:81)
	at com.biglybt.ui.swt.mainwindow.SWTThread.createInstance(SWTThread.java:58)
	at com.biglybt.ui.swt.Initializer.<init>(Initializer.java:181)
	at com.biglybt.ui.swt.UI.takeMainThread(UI.java:136)
	at com.biglybt.ui.Main.main(Main.java:247)
	... 6 more
Exception in thread "BiglyBT" java.lang.SecurityException: VM exit operation prohibited
	at com.biglybt.core.security.impl.SESecurityManagerImpl$ClientSecurityManager.checkExit(SESecurityManagerImpl.java:1881)
	at java.base/java.lang.Runtime.exit(Runtime.java:113)
	at java.base/java.lang.System.exit(System.java:1860)
	at com.biglybt.launcher.Launcher$1.run(Launcher.java:56)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
I think the version in [Ubuntu repositories](https://packages.ubuntu.com/ko/jammy/ppc64el/biglybt) is long outdated. You should update it.

Thanks for contributing to and supporting Open Source.

**Comment by parg** [comment]
BiglyBT devs aren't involved in the maintenance of the various Linux repositories, that task has always fallen to people wanting to help out. 

Have you tried installing locally from the version on [https://www.biglybt.com/ ?](https://www.biglybt.com/download/) ?

**Comment by WrichikBasu** [comment]
@parg Yes, I have tried using the `Github_BiglyBT_Installer.sh` of the latest release in GitHub, and that seems to work fine.


> BiglyBT devs aren't involved in the maintenance of the various Linux repositories, that task has always fallen to people wanting to help out.

In that case, I will probably close the issue because the bug isn't present in the latest version.

**Comment by parg** [comment]
Maybe someone will come along a fix things sometime, we can live in hope.
