### ISSUE TITLE
Failed to run jar

### ISSUE THREAD

**Issue by Ygarr** [BiglySoftware/BiglyBT#2744]
"java -jar .\GitHub_BiglyBT.jar"
```
Error: Unable to initialize main class com.biglybt.ui.Main
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/cli/ParseException
```
Is it possible without installing?

**Comment by parg** [comment]
See https://github.com/BiglySoftware/BiglyBT/wiki/Command-Line-Options

**Comment by Ygarr** [comment]
Thanks for reply

```
C:\SFT\JAVM\BiglyBT
λ ls
GitHub_BiglyBT.jar
```

```
C:\SFT\JAVM\BiglyBT
λ start /D "C:\SFT\JAVM\BiglyBT" javaw.exe -cp "BiglyBT.jar;commons-cli.jar;swt.jar" com.biglybt.ui.Main
```

Last command returns no errors but do nothing. Also nothing in VisualVM, for example

**Comment by Ygarr** [comment]
Thanks for attention. 

Tried this. Javaw presents. but nothing happens
![image](https://user-images.githubusercontent.com/14309871/195918255-53844400-2cce-4a9c-bb46-cbf08ac6de8b.png)

**Comment by parg** [comment]
Weird. Try

java -cp "BiglyBT.jar.......

instead of 

javaw -cp "BiglyBT.jar.....

**Comment by Ygarr** [comment]
What we have. Seems it looks like you have to install through the installer...
```
java.exe -cp "BiglyBT.jar;commons-cli.jar;swt.jar" com.biglybt.ui.Main
Error: Unable to initialize main class com.biglybt.ui.Main
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/cli/ParseException
```

**Comment by Ygarr** [comment]
Runned this with manually downloaded libs:

```
PS C:\SFT\JAVM\BiglyBT> ls


    Directory: C:\SFT\JAVM\BiglyBT


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        10/13/2022   5:12 PM       20479579 BiglyBT.jar
-a----        10/14/2022  11:01 PM         757977 commons-cli-1.5.0-bin.zip
-a----         1/22/2020   3:10 PM          58284 commons-cli.jar
-a----        10/14/2022  11:02 PM        4382324 swt-4.25-win32-win32-x86_64.zip
-a----         8/31/2022  10:21 PM        2518014 swt.jar


PS C:\SFT\JAVM\BiglyBT> java  -cp "commons-cli.jar;swt.jar;BiglyBT.jar" com.biglybt.ui.Main
java.lang.ClassNotFoundException: java.net.InetAddress$NameService
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:383)
        at java.base/java.lang.Class.forName(Class.java:376)
        at com.biglybt.core.util.spi.AENameServiceJava12.init(AENameServiceJava12.java:29)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:577)
        at com.biglybt.core.config.COConfigurationManager.preInitialise(COConfigurationManager.java:240)
        at com.biglybt.ui.Main.main(Main.java:85)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:577)
        at com.biglybt.launcher.Launcher$1.run(Launcher.java:48)
        at java.base/java.lang.Thread.run(Thread.java:833)
java.lang.UnsatisfiedLinkError: no aereg64 in java.library.path: C:\SFT\zulu18.32.13-ca-fx-jdk18.0.2.1-win_x64\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\SFT\zulu18.32.13-ca-fx-jdk18.0.2.1-win_x64\lib;C:\SFT\openjfx-18.0.2_windows-x64_bin-sdk\javafx-sdk-18.0.2\lib;C:\SFT\zulu18.32.13-ca-fx-jdk18.0.2.1-win_x64\bin;%PATH%;C:\Program Files\VSCodium\bin;C:\Users\nataly\scoop\apps\gawk\current;C:\SFT\openjdk-11.0.15_10\bin;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\Hostx64\x64;C:\Program Files\dotnet\;C:\SFT\nodejs\;C:\SFT\groovy\bin;C:\z88dk\bin;C:\z88dk\Lib;C:\SFT\zxbasic;C:\Users\nataly\scoop\apps\oh-my-posh\current\bin;C:\Users\nataly\scoop\apps\python\current\Scripts;C:\Users\nataly\scoop\apps\python\current;C:\Users\nataly\scoop\apps\ant\current\bin;C:\Users\nataly\scoop\apps\maven\current\bin;C:\Users\nataly\scoop\apps\vscodium-portable\current\bin;C:\Users\nataly\scoop\apps\perl\current\perl\site\bin;C:\Users\nataly\scoop\apps\perl\current\perl\bin;C:\Users\nataly\scoop\apps\perl\current\c\bin;C:\Users\nataly\scoop\shims;C:\Users\nataly\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Java_64_bit\bin;C:\Users\nataly\AppData\Local\Microsoft\WindowsApps;C:\WINDOWS\System32;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Users\nataly\AppData\Roaming\npm;C:\Program Files (x86)\Brackets\;C:\Users\nataly\AppData\Local\atom\bin;.
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2434)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:848)
        at java.base/java.lang.System.loadLibrary(System.java:2015)
        at com.biglybt.platform.win32.access.impl.AEWin32AccessInterface.<clinit>(AEWin32AccessInterface.java:66)
        at com.biglybt.platform.win32.access.impl.AEWin32AccessImpl.isEnabled(AEWin32AccessImpl.java:84)
        at com.biglybt.platform.win32.access.impl.AEWin32AccessImpl.<init>(AEWin32AccessImpl.java:74)
        at com.biglybt.platform.win32.access.impl.AEWin32AccessImpl.getSingleton(AEWin32AccessImpl.java:56)
        at com.biglybt.platform.win32.access.AEWin32Manager.getAccessor(AEWin32Manager.java:36)
        at com.biglybt.platform.win32.PlatformManagerImpl.<init>(PlatformManagerImpl.java:158)
        at com.biglybt.platform.win32.PlatformManagerImpl.getSingleton(PlatformManagerImpl.java:109)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:577)
        at com.biglybt.platform.PlatformManagerFactory.getPlatformManager(PlatformManagerFactory.java:77)
        at com.biglybt.core.util.SystemProperties.getUserPath(SystemProperties.java:278)
        at com.biglybt.core.util.FileUtil.readResilientConfigFile(FileUtil.java:961)
        at com.biglybt.core.config.impl.ConfigurationManager.load(ConfigurationManager.java:186)
        at com.biglybt.core.config.impl.ConfigurationManager.load(ConfigurationManager.java:238)
        at com.biglybt.core.config.impl.ConfigurationManager.getInstance(ConfigurationManager.java:108)
        at com.biglybt.core.config.COConfigurationManager.addAndFireParameterListener(COConfigurationManager.java:614)
        at com.biglybt.ui.swt.UI.<clinit>(UI.java:73)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:383)
        at java.base/java.lang.Class.forName(Class.java:376)
        at com.biglybt.ui.common.UserInterfaceFactory.getUI(UserInterfaceFactory.java:33)
        at com.biglybt.ui.Main.buildUIList(Main.java:323)
        at com.biglybt.ui.Main.main(Main.java:115)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:577)
        at com.biglybt.launcher.Launcher$1.run(Launcher.java:48)
        at java.base/java.lang.Thread.run(Thread.java:833)
This is BAD - fix me!
java.lang.Throwable
        at com.biglybt.core.util.SystemProperties.getDocPath(SystemProperties.java:481)
        at com.biglybt.core.config.impl.ConfigurationDefaults.<init>(ConfigurationDefaults.java:323)
        at com.biglybt.core.config.impl.ConfigurationDefaults.getInstance(ConfigurationDefaults.java:107)
        at com.biglybt.core.config.impl.ConfigurationManager.getIntParameter(ConfigurationManager.java:374)
        at com.biglybt.core.config.COConfigurationManager.getIntParameter(COConfigurationManager.java:346)
        at com.biglybt.core.util.RandomUtils.generateRandomNetworkListenPort(RandomUtils.java:128)
        at com.biglybt.core.util.RandomUtils.generateRandomNetworkListenPort(RandomUtils.java:92)
        at com.biglybt.core.config.impl.ConfigurationChecker.checkConfiguration(ConfigurationChecker.java:414)
        at com.biglybt.core.config.impl.ConfigurationManager.initialise(ConfigurationManager.java:175)
        at com.biglybt.core.config.impl.ConfigurationManager.getInstance(ConfigurationManager.java:110)
        at com.biglybt.core.config.COConfigurationManager.addAndFireParameterListener(COConfigurationManager.java:614)
        at com.biglybt.ui.swt.UI.<clinit>(UI.java:73)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:383)
        at java.base/java.lang.Class.forName(Class.java:376)
        at com.biglybt.ui.common.UserInterfaceFactory.getUI(UserInterfaceFactory.java:33)
        at com.biglybt.ui.Main.buildUIList(Main.java:323)
        at com.biglybt.ui.Main.main(Main.java:115)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:577)
        at com.biglybt.launcher.Launcher$1.run(Launcher.java:48)
        at java.base/java.lang.Thread.run(Thread.java:833)
DEBUG::Fri Oct 14 23:06:38 EEST 2022::com.biglybt.core.security.impl.SESecurityManagerImpl::installSecurityManager::387:
  java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
        at java.base/java.lang.System.setSecurityManager(System.java:416)
        at com.biglybt.core.security.impl.SESecurityManagerImpl.installSecurityManager(SESecurityManagerImpl.java:383)
        at com.biglybt.core.security.impl.SESecurityManagerImpl.initialise(SESecurityManagerImpl.java:215)
        at com.biglybt.core.security.SESecurityManager.initialise(SESecurityManager.java:55)
        at com.biglybt.core.config.impl.ConfigurationChecker.setSystemProperties(ConfigurationChecker.java:287)
        at com.biglybt.core.config.impl.ConfigurationManager.initialise(ConfigurationManager.java:177)
        at com.biglybt.core.config.impl.ConfigurationManager.getInstance(ConfigurationManager.java:110)
        at com.biglybt.core.config.COConfigurationManager.addAndFireParameterListener(COConfigurationManager.java:614)
        at com.biglybt.ui.swt.UI.<clinit>(UI.java:73)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:383)
        at java.base/java.lang.Class.forName(Class.java:376)
        at com.biglybt.ui.common.UserInterfaceFactory.getUI(UserInterfaceFactory.java:33)
        at com.biglybt.ui.Main.buildUIList(Main.java:323)
        at com.biglybt.ui.Main.main(Main.java:115)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:577)
        at com.biglybt.launcher.Launcher$1.run(Launcher.java:48)
        at java.base/java.lang.Thread.run(Thread.java:833)

changeLocale: *Default Language* != English (United States). Searching without country..
changeLocale: Searching for language English in *any* country..
changeLocale: no message properties for Locale 'English (United States)' (en_US), using 'English (default)'
DEBUG::Fri Oct 14 23:06:38 EEST 2022  Successfully migrated key management
UIFunctions/ImageLoad took 25ms
DEBUG::Fri Oct 14 23:06:38 EEST 2022::com.biglybt.core.util.DebugLight::printStackTrace::35:
  java.lang.UnsatisfiedLinkError: 'java.lang.String com.biglybt.platform.win32.access.impl.AEWin32AccessInterface.getVersion()'
        at com.biglybt.platform.win32.access.impl.AEWin32AccessInterface.getVersion(Native Method)
        at com.biglybt.platform.win32.access.impl.AEWin32AccessImpl.getVersion(AEWin32AccessImpl.java:164)
        at com.biglybt.ui.swt.win32.Win32UIEnhancer$1.run(Win32UIEnhancer.java:403)
        at com.biglybt.core.util.AEThread2$threadWrapper.run(AEThread2.java:334)

new shell took 104ms
new shell setup took 128ms
skin init took 78ms
MainMenu init took 26ms
pre skin widgets init took 25ms
skin widgets (1/2) init took 233ms
skin widgets (2/2) init took 104ms
pre SWTInstance init took 0ms
Init Core Columns took 77ms
SWTInstance init took 0ms
shell.layout took 104ms
---------SHOWN AT 1665777999867;1177ms
---------DONE DISPATCH AT 1665778000229;1539ms
---------READY AT 1665778000306;1616ms
shell.open took 491ms
processStartupDMS took 0ms
postPluginSetup init took 0ms
Locale Initializing took 0ms
DEBUG::Fri Oct 14 23:06:40 EEST 2022  Successfully migrated key management
Core Initializing took 918ms
```

**Comment by parg** [comment]
You need the native DLL for Windows, BiglyBT should automatically download it if it is missing - did it?
