### ISSUE TITLE
Fatal error trying to restore fresh backup from previous OS

### ISSUE THREAD

**Issue by cglmrfreeman** [BiglySoftware/BiglyBT#2767]
* OS and version: openSUSE 20221025 x86_64 Linux 6.0.3-1-default
* BiglyBT Version Number: B3.2.0.0/4 az3 (Git release)
* For *nix: Desktop Environment: KDE 5.99.0 / Plasma 5.26.1 (KWin)
```
DEBUG::Thu Oct 27 14:58:48 PDT 2022::com.biglybt.core.backup.impl.BackupManagerImpl::restoreSupport::1300:
    BackupManagerImpl$9::runSupport::979, AsyncDispatcher$1::run::168, AEThread2$threadWrapper::run::334
java.lang.Exception: Invalid backup: biglybt.config not found
        at com.biglybt.core.backup.impl.BackupManagerImpl.restoreSupport(BackupManagerImpl.java:1143)
        at com.biglybt.core.backup.impl.BackupManagerImpl$9.runSupport(BackupManagerImpl.java:979)
        at com.biglybt.core.util.AsyncDispatcher$1.run(AsyncDispatcher.java:168)
        at com.biglybt.core.util.AEThread2$threadWrapper.run(AEThread2.java:334)
core.stop
CRIT  [enDispatcher] net.i2p.router.Router         : Shutdown imminent
CRIT  [enDispatcher] net.i2p.router.Router         : Shutdown(3) complete

(BiglyBT:4598): Gtk-CRITICAL **: 14:59:01.910: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f80e1a4f3cd, pid=4598, tid=4617
#
# JRE version: OpenJDK Runtime Environment (11.0.17) (build 11.0.17+0-suse-1.1-x8664)
# Java VM: OpenJDK 64-Bit Server VM (11.0.17+0-suse-1.1-x8664, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libswt-pi3-gtk-4942r22.so+0x4f3cd]  Java_org_eclipse_swt_internal_gtk_OS_G_1OBJECT_1TYPE+0x0
#
# Core dump will be written. Default location: Core dumps may be processed with "/bin/false" (or dumping to /home/rob/biglybt/core.4598)
#
# An error report file with more information is saved as:
# /home/rob/biglybt/hs_err_pid4598.log
Compiled method (nm)   31404 4834     n 0       org.eclipse.swt.internal.gtk.OS::G_OBJECT_TYPE (native)
 total in heap  [0x00007f8138616890,0x00007f8138616c28] = 920
 relocation     [0x00007f8138616a08,0x00007f8138616a38] = 48
 main code      [0x00007f8138616a40,0x00007f8138616c20] = 480
 oops           [0x00007f8138616c20,0x00007f8138616c28] = 8
Compiled method (nm)   31404 4834     n 0       org.eclipse.swt.internal.gtk.OS::G_OBJECT_TYPE (native)
 total in heap  [0x00007f8138616890,0x00007f8138616c28] = 920
 relocation     [0x00007f8138616a08,0x00007f8138616a38] = 48
 main code      [0x00007f8138616a40,0x00007f8138616c20] = 480
 oops           [0x00007f8138616c20,0x00007f8138616c28] = 8
Compiled method (nm)   31406 4834     n 0       org.eclipse.swt.internal.gtk.OS::G_OBJECT_TYPE (native)
 total in heap  [0x00007f8138616890,0x00007f8138616c28] = 920
 relocation     [0x00007f8138616a08,0x00007f8138616a38] = 48
 main code      [0x00007f8138616a40,0x00007f8138616c20] = 480
 oops           [0x00007f8138616c20,0x00007f8138616c28] = 8
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
/home/rob/biglybt/biglybt: line 227:  4598 Aborted                 (core dumped) ${JAVA_PROGRAM_DIR}java -Xmx256m -cp "${CLASSPATH}" "-Djava.library.path=${PROGRAM_DIR}" "-Dazureus.install.path=${PROGRAM_DIR}" "-Dazureus.script=$0" ${JAVA_PROPS} ${JAVA_ARGS} ${START_CLASS} ${OTHER_PARAMS} "$@"
Exit from BiglyBT complete
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.biglybt.core.util.spi.AENameServiceJava9 (file:/home/rob/biglybt/BiglyBT.jar) to field java.net.InetAddress.impl
WARNING: Please consider reporting this to the maintainers of com.biglybt.core.util.spi.AENameServiceJava9
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
No shutdown tasks to do
BiglyBT TERMINATED.
```

Generated log here: [hs_err_pid4598.log](https://github.com/BiglySoftware/BiglyBT/files/9883457/hs_err_pid4598.log)

And debug generated: [debug.zip](https://github.com/BiglySoftware/BiglyBT/files/9883466/debug.zip)

**Comment by parg** [comment]
This is a crash in the SWT library BiglyBT uses. I reported this to Eclipse over a year ago but they don't seem interested.

https://bugs.eclipse.org/bugs/show_bug.cgi?id=573208

The only thing you could try is joining the Beta programme (see the Help menu). When you do you will then be updated to the latest SWT version, perhaps they have inadvertently fixed it. Then again, probably not :(

**Comment by cglmrfreeman** [comment]
> This is a crash in the SWT library BiglyBT uses. I reported this to Eclipse over a year ago but they don't seem interested.

I like how they seem to be like "Well _you_ could look into the issue :wink:" Ah well. Manually copied over my `.biglybt` folder instead of from a backup and all appears to be normal with it.

So should this issue be closed as a duplicate because the crash is the same, or is it a new issue because it's the same crash caused by a different method? :thinking:

**Comment by parg** [comment]
I'll close it and reference it from the other
