### ISSUE TITLE
Very slow to run, URLs not handled as before.

### ISSUE THREAD

**Issue by iWoodsman** [BiglySoftware/BiglyBT#2776]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B3.2.0.0/4 az3

Startup of BiglyBT on 3 platforms has been very fast for years, then suddenly a week ago, on Windows, it began to do two things: 
1. on app run it takes near a full minute of no activity before the window appears. Once started, performance is fine except for;
2. the running instance of BiglyBT no longer collects/handles URLs for torrent links by importing the new torrent info, rather clicking a magnet link now tries to run a second instance of BiglyBT, which eventually fails with an error that the desired port is already open.
Both these problems sound like possible OS issues, yet only BiglyBT has so far showed bad behavior.
I have deleted BiglyBT, it's AppData Roaming data and the user data directory, nuking it as completely as I can see how, but on reinstall the effect persists.
Running the debug executable generates many occurrences of the below message. I'm not sure where TCP network manager reader comes into it, but all other network activity on the PC seems normal.
C:\Program Files\BiglyBT>BiglyBT-console.exe
changeLocale: *Default Language* != English (United States). Searching without country..
changeLocale: Searching for language English in *any* country..
changeLocale: no message properties for Locale 'English (United States)' (en_US), using 'English (default)'
DEBUG::Wed Nov 02 13:07:15 EDT 2022::com.biglybt.core.networkmanager.impl.tcp.VirtualChannelSelectorImpl::<init>::325:
  ERROR: caught exception on Selector.open() for 'TCP network manager reader'
    VirtualChannelSelector::<init>::55, TCPNetworkManager::<init>::123, TCPNetworkManager::<clinit>::50, NetworkManager::getMinMssSize::323, ByteBucketST::ensureByteBucketMinBurstRate::172, ByteBucketST::<init>::58, ByteBucketST::<init>::44, TransferProcessor::createBucket::684, TransferProcessor::<init>::99, NetworkManager::<init>::207, NetworkManager::<clinit>::54, CoreImpl::<init>::345, CoreImpl::create::176, CoreFactory::create::43, Main::main::200, NativeMethodAccessorImpl::invoke0::-2, NativeMethodAccessorImpl::invoke::-1, DelegatingMethodAccessorImpl::invoke::-1, Method::invoke::-1, Launcher$1::run::48, Thread::run::-1
java.io.IOException: Unable to establish loopback connection
        at sun.nio.ch.PipeImpl$Initializer.run(Unknown Source)
        at sun.nio.ch.PipeImpl$Initializer.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.nio.ch.PipeImpl.<init>(Unknown Source)
        at sun.nio.ch.SelectorProviderImpl.openPipe(Unknown Source)
        at java.nio.channels.Pipe.open(Unknown Source)
        at sun.nio.ch.WindowsSelectorImpl.<init>(Unknown Source)
        at sun.nio.ch.WindowsSelectorProvider.openSelector(Unknown Source)
        at java.nio.channels.Selector.open(Unknown Source)
        at com.biglybt.core.networkmanager.impl.tcp.VirtualChannelSelectorImpl$2.run(VirtualChannelSelectorImpl.java:180)
        at com.biglybt.core.util.AEThread2$threadWrapper.run(AEThread2.java:334)
Caused by: java.net.SocketException: Permission denied: connect
        at sun.nio.ch.Net.connect0(Native Method)
        at sun.nio.ch.Net.connect(Unknown Source)
        at sun.nio.ch.Net.connect(Unknown Source)
        at sun.nio.ch.SocketChannelImpl.connect(Unknown Source)
        at java.nio.channels.SocketChannel.open(Unknown Source)
        at sun.nio.ch.PipeImpl$Initializer$LoopbackConnector.run(Unknown Source)
        ... 11 more

**Comment by iWoodsman** [comment]
Resolution: my Windows Firewall list of Allows contained 5 occurrences of BiglyBT and 2 of BiglyBT Launcher. One of the Launcher occurrences only had Private network traffic allowed. I made it like the others with both Public and Private traffic permitted. Upon starting BiglyBT again, startup speed and URL handling was normal again. I do not manipulate the Firewall entries manually so I don't know why this happened.

**Comment by parg** [comment]
If something prevents BiglyBT from having the ability to listen on network sockets then you will see these kind of issues, glad you figured it out!
