### ISSUE TITLE
Installation fails with java-17-openjdk-17.0.5.0.8-1.fc37.x86_64

### ISSUE THREAD

**Issue by afberendsen** [BiglySoftware/BiglyBT#2810]
* OS and version
`Linux HG000009 6.0.12-300.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Dec 8 16:58:47 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
* BiglyBT Version Number
Latest download from website (2022-Dec-13)
* For *nix: Desktop Environment
Gnome

* Issue
When running the installer BiglyBT_Installer.sh, with java-17-openjdk-17.0.5.0.8-1.fc37.x86_64, it fails with an error for at awt. However, when using java-11-openjdk-11.0.17.0.8-1.fc37.x86_64, installation works BUT the application hangs at the startup.

When using java-17-openjdk-17.0.5.0.8-1.fc37.x86_64,:

```
$ sudo alternatives --config java

There are 3 programs which provide 'java'.

  Selection    Command
-----------------------------------------------
*  1           java-17-openjdk.x86_64 (/usr/lib/jvm/java-17-openjdk-17.0.5.0.8-1.fc37.x86_64/bin/java)
 + 2           java-11-openjdk.x86_64 (/usr/lib/jvm/java-11-openjdk-11.0.17.0.8-1.fc37.x86_64/bin/java)
   3           java-latest-openjdk.x86_64 (/usr/lib/jvm/java-19-openjdk-19.0.1.0.10-2.rolling.fc37.x86_64/bin/java)

Enter to keep the current selection[+], or type selection number: 1
$ java -version
openjdk version "17.0.5" 2022-10-18
OpenJDK Runtime Environment (Red_Hat-17.0.5.0.8-1.fc37) (build 17.0.5+8)
OpenJDK 64-Bit Server VM (Red_Hat-17.0.5.0.8-1.fc37) (build 17.0.5+8, mixed mode, sharing)
$ ~/Downloads/BiglyBT_Installer.sh 
don't need JNA
not wayland
Starting Installer ...
An error occurred:
java.lang.NoClassDefFoundError: Could not initialize class java.awt.Toolkit
Error log: /tmp/install4jError1969830221104864501.log
java.lang.NoClassDefFoundError: Could not initialize class java.awt.Toolkit
	at java.desktop/java.awt.Color.<clinit>(Color.java:277)
	at com.install4j.runtime.installer.frontend.GUIHelper.<clinit>(GUIHelper.java:46)
	at com.install4j.runtime.installer.frontend.headless.AbstractHeadlessScreenExecutor.init(AbstractHeadlessScreenExecutor.java:83)
	at com.install4j.runtime.installer.frontend.headless.ConsoleScreenExecutor.<init>(ConsoleScreenExecutor.java:25)
	at com.install4j.runtime.installer.frontend.headless.InstallerConsoleScreenExecutor.<init>(InstallerConsoleScreenExecutor.java:6)
	at com.install4j.runtime.installer.Installer.getScreenExecutor(Installer.java:84)
	at com.install4j.runtime.installer.Installer.runInProcess(Installer.java:60)
	at com.install4j.runtime.installer.Installer.main(Installer.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.install4j.runtime.launcher.UnixLauncher.start(UnixLauncher.java:69)
	at install4j.Installer3792011337.main(Unknown Source)
$ find /usr/lib/jvm/java-17-openjdk-17.0.5.0.8-1.fc37.x86_64 -name '*wt*' 
/usr/lib/jvm/java-17-openjdk-17.0.5.0.8-1.fc37.x86_64/lib/libawt_headless.so
/usr/lib/jvm/java-17-openjdk-17.0.5.0.8-1.fc37.x86_64/lib/libawt.so
$ ldd /usr/lib/jvm/java-17-openjdk-17.0.5.0.8-1.fc37.x86_64/lib/libawt.so
	linux-vdso.so.1 (0x00007ffd2def5000)
	libjava.so => /usr/lib/jvm/java-17-openjdk-17.0.5.0.8-1.fc37.x86_64/lib/libjava.so (0x00007f86117dd000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f86116e7000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f861150a000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f86118fe000)
	libjvm.so => not found
```
When using  java-11-openjdk-11.0.17.0.8-1.fc37.x86_64

Installation works properly but the application hangs when started from the GUI. I am not sure what and how information I should collect.

**Comment by parg** [comment]
What distro?

**Comment by parg** [comment]
Seems to be a RedHat JDK - perhaps try another?

**Comment by parg** [comment]
I installed the RedHat Java 11 runtime in my Kubuntu VM and everything worked fine:

Java 11.0.17 (64 bit)
  Red Hat, Inc.
/home/paul/Java/JDK11RedHat

SWT v4942r22, gtk/3.24.33, zoom=100, dpi=96
Linux v5.15.0-52-generic, amd64 (64 bit)
B3.2.0.1_B05/4 az3

**Comment by afberendsen** [comment]
Fedora Linux 37
```
$ cat /etc/os-release
NAME="Fedora Linux"
VERSION="37 (Workstation Edition)"
ID=fedora
VERSION_ID=37
VERSION_CODENAME=""
PLATFORM_ID="platform:f37"
PRETTY_NAME="Fedora Linux 37 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:37"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f37/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=37
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=37
SUPPORT_END=2023-11-14
VARIANT="Workstation Edition"
VARIANT_ID=workstation

```

**Comment by afberendsen** [comment]
If I can stick to `dnf` to install pakcages, it would be better.
It was working ok on Fedora Linux 36 until the last update, which broke completely BigLyBT.

These is what I have available from `jdk`  

```
$ sudo dnf search jdk
Last metadata expiration check: 1:41:10 ago on Tue 13 Dec 2022 16:26:17 CET.
================================================================================================================ Name & Summary Matched: jdk =================================================================================================================
commons-compiler-jdk.noarch : Commons Compiler JDK
copy-jdk-configs.noarch : JDKs configuration files copier
java-1.8.0-openjdk.x86_64 : OpenJDK 8 Runtime Environment
java-1.8.0-openjdk-demo.x86_64 : OpenJDK 8 Demos
java-1.8.0-openjdk-demo-fastdebug.x86_64 : OpenJDK 8 Demos optimised with full debugging on
java-1.8.0-openjdk-demo-slowdebug.x86_64 : OpenJDK 8 Demos unoptimised with full debugging on
java-1.8.0-openjdk-devel.x86_64 : OpenJDK 8 Development Environment
java-1.8.0-openjdk-devel-fastdebug.x86_64 : OpenJDK 8 Development Environment optimised with full debugging on
java-1.8.0-openjdk-devel-slowdebug.x86_64 : OpenJDK 8 Development Environment unoptimised with full debugging on
java-1.8.0-openjdk-fastdebug.x86_64 : OpenJDK 8 Runtime Environment optimised with full debugging on
java-1.8.0-openjdk-headless.x86_64 : OpenJDK 8 Headless Runtime Environment
java-1.8.0-openjdk-headless-fastdebug.x86_64 : OpenJDK 8 Runtime Environment optimised with full debugging on
java-1.8.0-openjdk-headless-slowdebug.x86_64 : OpenJDK 8 Runtime Environment unoptimised with full debugging on
java-1.8.0-openjdk-javadoc.noarch : OpenJDK 8 API documentation
java-1.8.0-openjdk-javadoc-zip.noarch : OpenJDK 8 API documentation compressed in a single archive
java-1.8.0-openjdk-openjfx.x86_64 : OpenJDK x OpenJFX connector. This package adds symliks finishing Java FX integration to java-1.8.0-openjdk
java-1.8.0-openjdk-openjfx-devel.x86_64 : OpenJDK x OpenJFX connector for FX developers. This package adds symliks finishing Java FX integration to java-1.8.0-openjdk-devel
java-1.8.0-openjdk-openjfx-devel-fastdebug.x86_64 : OpenJDK x OpenJFX connector for FX developers for packages with debugging on and optimisation. This package adds symliks finishing Java FX integration to java-1.8.0-openjdk-devel-slowdebug
java-1.8.0-openjdk-openjfx-devel-slowdebug.x86_64 : OpenJDK x OpenJFX connector for FX developers for packages with debugging on and no optimisation. This package adds symliks finishing Java FX integration to java-1.8.0-openjdk-devel-slowdebug
java-1.8.0-openjdk-openjfx-fastdebug.x86_64 : OpenJDK x OpenJFX connector for packages with debugging on and optimisation. his package adds symliks finishing Java FX integration to java-1.8.0-openjdk-fastdebug
java-1.8.0-openjdk-openjfx-slowdebug.x86_64 : OpenJDK x OpenJFX connector for packages with debugging on and no optimisation. his package adds symliks finishing Java FX integration to java-1.8.0-openjdk-slowdebug
java-1.8.0-openjdk-slowdebug.x86_64 : OpenJDK 8 Runtime Environment unoptimised with full debugging on
java-1.8.0-openjdk-src.x86_64 : OpenJDK 8 Source Bundle
java-1.8.0-openjdk-src-fastdebug.x86_64 : OpenJDK 8 Source Bundle for packages with debugging on and optimisation
java-1.8.0-openjdk-src-slowdebug.x86_64 : OpenJDK 8 Source Bundle for packages with debugging on and no optimisation
java-11-openjdk.x86_64 : OpenJDK 11 Runtime Environment
java-11-openjdk-demo.x86_64 : OpenJDK 11 Demos
java-11-openjdk-demo-fastdebug.x86_64 : OpenJDK 11 Demos optimised with full debugging on
java-11-openjdk-demo-slowdebug.x86_64 : OpenJDK 11 Demos unoptimised with full debugging on
java-11-openjdk-devel.x86_64 : OpenJDK 11 Development Environment
java-11-openjdk-devel-fastdebug.x86_64 : OpenJDK 11 Development Environment optimised with full debugging on
java-11-openjdk-devel-slowdebug.x86_64 : OpenJDK 11 Development Environment unoptimised with full debugging on
java-11-openjdk-fastdebug.x86_64 : OpenJDK 11 Runtime Environment optimised with full debugging on
java-11-openjdk-headless.x86_64 : OpenJDK 11 Headless Runtime Environment
java-11-openjdk-headless-fastdebug.x86_64 : OpenJDK 11 Runtime Environment optimised with full debugging on
java-11-openjdk-headless-slowdebug.x86_64 : OpenJDK 11 Runtime Environment unoptimised with full debugging on
java-11-openjdk-javadoc.x86_64 : OpenJDK 11 API documentation
java-11-openjdk-javadoc-zip.x86_64 : OpenJDK 11 API documentation compressed in a single archive
java-11-openjdk-jmods.x86_64 : JMods for OpenJDK 11
java-11-openjdk-jmods-fastdebug.x86_64 : JMods for OpenJDK 11 optimised with full debugging on
java-11-openjdk-jmods-slowdebug.x86_64 : JMods for OpenJDK 11 unoptimised with full debugging on
java-11-openjdk-slowdebug.x86_64 : OpenJDK 11 Runtime Environment unoptimised with full debugging on
java-11-openjdk-src.x86_64 : OpenJDK 11 Source Bundle
java-11-openjdk-src-fastdebug.x86_64 : OpenJDK 11 Source Bundle for packages with debugging on and optimisation
java-11-openjdk-src-slowdebug.x86_64 : OpenJDK 11 Source Bundle for packages with debugging on and no optimisation
java-11-openjdk-static-libs.x86_64 : OpenJDK 11 libraries for static linking
java-11-openjdk-static-libs-fastdebug.x86_64 : OpenJDK 11 libraries for static linking optimised with full debugging on
java-11-openjdk-static-libs-slowdebug.x86_64 : OpenJDK 11 libraries for static linking unoptimised with full debugging on
java-17-openjdk.x86_64 : OpenJDK 17 Runtime Environment
java-17-openjdk-demo.x86_64 : OpenJDK 17 Demos
java-17-openjdk-demo-fastdebug.x86_64 : OpenJDK 17 Demos optimised with full debugging on
java-17-openjdk-demo-slowdebug.x86_64 : OpenJDK 17 Demos unoptimised with full debugging on
java-17-openjdk-devel.x86_64 : OpenJDK 17 Development Environment
java-17-openjdk-devel-fastdebug.x86_64 : OpenJDK 17 Development Environment optimised with full debugging on
java-17-openjdk-devel-slowdebug.x86_64 : OpenJDK 17 Development Environment unoptimised with full debugging on
java-17-openjdk-fastdebug.x86_64 : OpenJDK 17 Runtime Environment optimised with full debugging on
java-17-openjdk-headless.x86_64 : OpenJDK 17 Headless Runtime Environment
java-17-openjdk-headless-fastdebug.x86_64 : OpenJDK 17 Runtime Environment optimised with full debugging on
java-17-openjdk-headless-slowdebug.x86_64 : OpenJDK 17 Runtime Environment unoptimised with full debugging on
java-17-openjdk-javadoc.x86_64 : OpenJDK 17 API documentation
java-17-openjdk-javadoc-zip.x86_64 : OpenJDK 17 API documentation compressed in a single archive
java-17-openjdk-jmods.x86_64 : JMods for OpenJDK 17
java-17-openjdk-jmods-fastdebug.x86_64 : JMods for OpenJDK 17 optimised with full debugging on
java-17-openjdk-jmods-slowdebug.x86_64 : JMods for OpenJDK 17 unoptimised with full debugging on
java-17-openjdk-slowdebug.x86_64 : OpenJDK 17 Runtime Environment unoptimised with full debugging on
java-17-openjdk-src.x86_64 : OpenJDK 17 Source Bundle
java-17-openjdk-src-fastdebug.x86_64 : OpenJDK 17 Source Bundle for packages with debugging on and optimisation
java-17-openjdk-src-slowdebug.x86_64 : OpenJDK 17 Source Bundle for packages with debugging on and no optimisation
java-17-openjdk-static-libs.x86_64 : OpenJDK 17 libraries for static linking
java-17-openjdk-static-libs-fastdebug.x86_64 : OpenJDK 17 libraries for static linking optimised with full debugging on
java-17-openjdk-static-libs-slowdebug.x86_64 : OpenJDK 17 libraries for static linking unoptimised with full debugging on
java-latest-openjdk.x86_64 : OpenJDK 19 Runtime Environment
java-latest-openjdk-demo.x86_64 : OpenJDK 19 Demos
java-latest-openjdk-demo-fastdebug.x86_64 : OpenJDK 19 Demos optimised with full debugging on
java-latest-openjdk-demo-slowdebug.x86_64 : OpenJDK 19 Demos unoptimised with full debugging on
java-latest-openjdk-devel.x86_64 : OpenJDK 19 Development Environment
java-latest-openjdk-devel-fastdebug.x86_64 : OpenJDK 19 Development Environment optimised with full debugging on
java-latest-openjdk-devel-slowdebug.x86_64 : OpenJDK 19 Development Environment unoptimised with full debugging on
java-latest-openjdk-fastdebug.x86_64 : OpenJDK 19 Runtime Environment optimised with full debugging on
java-latest-openjdk-headless.x86_64 : OpenJDK 19 Headless Runtime Environment
java-latest-openjdk-headless-fastdebug.x86_64 : OpenJDK 19 Runtime Environment optimised with full debugging on
java-latest-openjdk-headless-slowdebug.x86_64 : OpenJDK 19 Runtime Environment unoptimised with full debugging on
java-latest-openjdk-javadoc.x86_64 : OpenJDK 19 API documentation
java-latest-openjdk-javadoc-zip.x86_64 : OpenJDK 19 API documentation compressed in a single archive
java-latest-openjdk-jmods.x86_64 : JMods for OpenJDK 19
java-latest-openjdk-jmods-fastdebug.x86_64 : JMods for OpenJDK 19 optimised with full debugging on
java-latest-openjdk-jmods-slowdebug.x86_64 : JMods for OpenJDK 19 unoptimised with full debugging on
java-latest-openjdk-slowdebug.x86_64 : OpenJDK 19 Runtime Environment unoptimised with full debugging on
java-latest-openjdk-src.x86_64 : OpenJDK 19 Source Bundle
java-latest-openjdk-src-fastdebug.x86_64 : OpenJDK 19 Source Bundle for packages with debugging on and optimisation
java-latest-openjdk-src-slowdebug.x86_64 : OpenJDK 19 Source Bundle for packages with debugging on and no optimisation
java-latest-openjdk-static-libs.x86_64 : OpenJDK 19 libraries for static linking
java-latest-openjdk-static-libs-fastdebug.x86_64 : OpenJDK 19 libraries for static linking optimised with full debugging on
java-latest-openjdk-static-libs-slowdebug.x86_64 : OpenJDK 19 libraries for static linking unoptimised with full debugging on
javapackages-bootstrap-openjdk8.noarch : OpenJDK 8 toolchain for Java Packages Bootstrap
maven-local-openjdk11.noarch : OpenJDK 11 toolchain for XMvn
maven-local-openjdk17.noarch : OpenJDK 17 toolchain for XMvn
maven-local-openjdk8.noarch : OpenJDK 8 toolchain for XMvn
maven-openjdk11.noarch : OpenJDK 11 binding for Maven
maven-openjdk17.noarch : OpenJDK 17 binding for Maven
maven-openjdk8.noarch : OpenJDK 8 binding for Maven
openjdk-asmtools-javadoc.noarch : Javadoc for openjdk-asmtools
openjdk-asmtools7.noarch : To develop tools create proper & improper Java '.class' files for jdk11 and down
openjdk-asmtools7-javadoc.noarch : Javadoc for openjdk-asmtools7
prometheus-jmx-exporter-openjdk11.noarch : OpenJDK 11 binding for prometheus-jmx-exporter
prometheus-jmx-exporter-openjdk17.noarch : OpenJDK 17 binding for prometheus-jmx-exporter
prometheus-jmx-exporter-openjdk8.noarch : OpenJDK 1.8.0 binding for prometheus-jmx-exporter
slf4j-jdk14.noarch : SLF4J JDK14 Binding
===================================================================================================================== Name Matched: jdk ======================================================================================================================
dogtag-ldapjdk.noarch : LDAP SDK
dogtag-ldapjdk-javadoc.noarch : Javadoc for LDAP SDK
golang-github-jdkato-prose-devel.noarch : Golang library for text processing
golang-github-jdkato-syllables-devel.noarch : Go syllable counter
openjdk-asmtools.noarch : To develop tools create proper & improper Java '.class' files
```

**Comment by afberendsen** [comment]
After executing from the command line, it seems to stop at SLF4J
```
.
.
.
IFunctions/ImageLoad took 0ms
new shell took 125ms
new shell setup took 50ms
skin init took 76ms
MainMenu init took 104ms
pre skin widgets init took 52ms
skin widgets (1/2) init took 252ms
skin widgets (2/2) init took 133ms
pre SWTInstance init took 0ms
Init Core Columns took 75ms
SWTInstance init took 0ms
shell.layout took 0ms
---------SHOWN AT 1670951859176;1117ms
---------DONE DISPATCH AT 1670951859725;1666ms
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

**Comment by afberendsen** [comment]
After installin slf4j.noarch, I still get the same behavioru

**Comment by afberendsen** [comment]
...after changing back to java-17-openjdk.x86_64 works again...
```
 sudo alternatives --config java

There are 3 programs which provide 'java'.

  Selection    Command
-----------------------------------------------
*  1           java-17-openjdk.x86_64 (/usr/lib/jvm/java-17-openjdk-17.0.5.0.8-1.fc37.x86_64/bin/java)
   2           java-11-openjdk.x86_64 (/usr/lib/jvm/java-11-openjdk-11.0.17.0.8-1.fc37.x86_64/bin/java)
 + 3           java-latest-openjdk.x86_64 (/usr/lib/jvm/java-19-openjdk-19.0.1.0.10-2.rolling.fc37.x86_64/bin/java)

Enter to keep the current selection[+], or type selection number: 1
$ java -cp /usr/share/java/jna.jar:./BiglyBT.jar:./commons-cli.jar:./dorkbox-systemtray.jar:swt/swt-x86_64.jar -Djava.library.path=/home/afberendsen/biglybt -Dazureus.install.path=/home/afberendsen/biglybt -Dazureus.script=/home/afberendsen/biglybt/biglybt -Dazureus.script.version=10 -Xmx12g -XX:MaxDirectMemorySize=8g com.biglybt.ui.Main
.
.
.

```

**Comment by parg** [comment]
The slf4j warning is as expected, ignore that.

That java.lang.ClassNotFoundException: java.net.InetAddress$NameService issue is a weird one, BigyBT only attempts to load it between Java 12 and 17, not 11.

**Comment by afberendsen** [comment]
After closing the app...
```
(BiglyBT:1624283): Gtk-CRITICAL **: 18:59:46.969: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f90ce24f3cd, pid=1624283, tid=1624303
#
# JRE version: OpenJDK Runtime Environment (Red_Hat-17.0.5.0.8-1.fc37) (17.0.5+8) (build 17.0.5+8)
# Java VM: OpenJDK 64-Bit Server VM (Red_Hat-17.0.5.0.8-1.fc37) (17.0.5+8, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libswt-pi3-gtk-4942r22.so+0x4f3cd]  Java_org_eclipse_swt_internal_gtk_OS_G_1OBJECT_1TYPE+0x0
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" (or dumping to /home/afberendsen/biglybt/core.1624283)
#
# An error report file with more information is saved as:
# /home/afberendsen/biglybt/hs_err_pid1624283.log
core.stop done in 44920
Compiled method (n/a) 1984476 3097     n 0       org.eclipse.swt.internal.gtk.OS::G_OBJECT_TYPE (native)
 total in heap  [0x00007f9124c99210,0x00007f9124c99580] = 880
 relocation     [0x00007f9124c99370,0x00007f9124c993a0] = 48
 main code      [0x00007f9124c993a0,0x00007f9124c99578] = 472
 oops           [0x00007f9124c99578,0x00007f9124c99580] = 8
Compiled method (n/a) 1984476 3097     n 0       org.eclipse.swt.internal.gtk.OS::G_OBJECT_TYPE (native)
 total in heap  [0x00007f9124c99210,0x00007f9124c99580] = 880
 relocation     [0x00007f9124c99370,0x00007f9124c993a0] = 48
 main code      [0x00007f9124c993a0,0x00007f9124c99578] = 472
 oops           [0x00007f9124c99578,0x00007f9124c99580] = 8
Compiled method (n/a) 1984482 3097     n 0       org.eclipse.swt.internal.gtk.OS::G_OBJECT_TYPE (native)
 total in heap  [0x00007f9124c99210,0x00007f9124c99580] = 880
 relocation     [0x00007f9124c99370,0x00007f9124c993a0] = 48
 main code      [0x00007f9124c993a0,0x00007f9124c99578] = 472
 oops           [0x00007f9124c99578,0x00007f9124c99580] = 8
#
# If you would like to submit a bug report, please visit:
#   https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora&component=java-17-openjdk&version=37
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Aborted (core dumped)
```

**Comment by parg** [comment]
Join the Beta Program (Help menu), you'll get a newer SWT library

**Comment by parg** [comment]
(not that I promise it'll fix anything...)

**Comment by afberendsen** [comment]
Ok. I will try it tomorrow.

**Comment by parg** [comment]
When transfers drop to zero check out

Statistics->Cache for bytes queued for disk
Statistics->Transfers for bytes queued for network
Statistics->Counters for various internal queue sizes etc

Never seen those "Unknown BT message ID" errors, would seem to imply a peer is sending garbage

The UnsupportedAddressTypeException error might be related to IPv6, do you have any bind addresses set under

Options->Connection->Advanced Network Settings: Bind to local IP address or interface

?

**Comment by parg** [comment]
BTW, I installed Fedora 37 in a VirtualBox VM and can confirm the installation error with the default Java 17. Switching to Java 11 seems to have everything running OK and I've not experienced any crashes. My network config is simpler than yours though, no VPN

**Comment by afberendsen** [comment]
1. Yes, I do have a bind to local IP. Into the nordlynx interface.
2. Is there anyway to identify the (possible) peer sending gargabe so I cna block it?
3. Those are the current statiscs. At this moment is limited to 7.3KiB/s. Before I used to have between 5 to 10 MBi/s
![Screenshot 2022-12-14 185612](https://user-images.githubusercontent.com/30361962/207671140-bd091008-0541-424b-b602-0a7da4801f41.png)
![Screenshot 2022-12-14 185918](https://user-images.githubusercontent.com/30361962/207671605-93220ad8-2de9-4bae-9d36-bb18a9783e11.png)
![Screenshot 2022-12-14 190049](https://user-images.githubusercontent.com/30361962/207671932-786324c1-df55-4953-a394-ee93d7ac9993.png)
![Screenshot 2022-12-14 190111](https://user-images.githubusercontent.com/30361962/207671943-834c835b-76ff-4086-953d-730b64c9ef3a.png)

**Comment by afberendsen** [comment]
I just noticed the following error (see below)
Current java in use is
```
$ java -version
openjdk version "17.0.5" 2022-10-18
OpenJDK Runtime Environment (Red_Hat-17.0.5.0.8-1.fc37) (build 17.0.5+8)
OpenJDK 64-Bit Server VM (Red_Hat-17.0.5.0.8-1.fc37) (build 17.0.5+8, mixed mode, sharing)
```
BitLyBT  app run options
```
java -Xmx256m -cp /usr/share/java/jna.jar:./BiglyBT.jar:./commons-cli.jar:./dorkbox-systemtray.jar:swt/swt-x86_64.jar -Djava.library.path=/home/afberendsen/biglybt -Dazureus.install.path=/home/afberendsen/biglybt -Dazureus.script=/home/afberendsen/biglybt/biglybt -Dazureus.script.version=10 -Xmx8g -XX:MaxDirectMemorySize=2g com.biglybt.ui.Main
```
![Screenshot 2022-12-14 203212](https://user-images.githubusercontent.com/30361962/207697249-465a005e-9d30-4a29-abcd-a95d81e33bd8.png)

**Comment by afberendsen** [comment]
After restarting
```
$ ps aux|grep -i biglybt
afberen+  276434  0.0  0.0 223068  3608 ?        S    20:36   0:00 bash /home/afberendsen/biglybt/biglybt
afberen+  278756 79.1  2.3 17295540 1522636 ?    Sl   20:36   6:57 java -Xmx256m -cp /usr/share/java/jna.jar:./BiglyBT.jar:./commons-cli.jar:./dorkbox-systemtray.jar:swt/swt-x86_64.jar -Djava.library.path=/home/afberendsen/biglybt -Dazureus.install.path=/home/afberendsen/biglybt -Dazureus.script=/home/afberendsen/biglybt/biglybt -Dazureus.script.version=10 -Xmx8g -XX:MaxDirectMemorySize=2g com.biglybt.ui.Main
afberen+  290044  6.9  0.0  25112 17516 ?        S    20:36   0:35 /home/afberendsen/.biglybt/plugins/aznettor/tor -f config.txt
```

**Comment by afberendsen** [comment]
> BTW, I installed Fedora 37 in a VirtualBox VM and can confirm the installation error with the default Java 17. Switching to Java 11 seems to have everything running OK and I've not experienced any crashes. My network config is simpler than yours though, no VPN

Using java 11 to run BigLyBT makes it to hang at srat-up. I cannot see any error messags in `/var/log/messages` that can help.

Using Java 17 to run BigLyBt makes it to run out of memory. I will try to run it from the command line (there are two `-Xmx` when running from the Gnome desktop icon.

**Comment by afberendsen** [comment]
and the download speed just keep improving
![Screenshot 2022-12-15 055250](https://user-images.githubusercontent.com/30361962/207775632-ec8ea245-d48c-499c-95fd-d8e2dd950c68.png)

**Comment by parg** [comment]
Maybe re-enable the plugin and see what happens?

**Comment by afberendsen** [comment]
I will try tit today.

However, I believe the biggest problem here is the processing of the java command line, which is taking the `-Xmx256m` option and ignoring any conflicting options.

**Comment by afberendsen** [comment]
After more than 24 hours, BL is still stable and no memory or connections problems.
