### ISSUE TITLE
I appear to have some sort of error....

### ISSUE THREAD

**Issue by DumbJoe** [BiglySoftware/BiglyBT#2968]
No idea what this could be caused by:
```
Error while processing advanced socket options (rcv=0, snd=0, tos=, port=0, bind=/0:0:0:0:0:0:0:1)
java.net.BindException: Cannot assign requested address
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:461)
        at sun.nio.ch.Net.bind(Net.java:453)
        at sun.nio.ch.SocketChannelImpl.bind(SocketChannelImpl.java:584)
        at sun.nio.ch.SocketAdaptor.bind(SocketAdaptor.java:147)
        at com.biglybt.core.networkmanager.impl.tcp.TCPConnectionManager.addNewRequest(TCPConnectionManager.java:426)
        at com.biglybt.core.networkmanager.impl.tcp.TCPConnectionManager.runSelect(TCPConnectionManager.java:890)
        at com.biglybt.core.networkmanager.impl.tcp.TCPConnectionManager$7.run(TCPConnectionManager.java:300)
```

**Comment by parg** [comment]
well it is attempting to bind the outbound TCP socket to IPv6 "localhost" and it failed for some reason

**Comment by DumbJoe** [comment]
Is it supposed to do that?

**Comment by parg** [comment]
you tell me

**Comment by DumbJoe** [comment]
That sounds like it's not supposed to and my service provider is blocking the attempt(presumably one of the torrents requires it...?)......for some reason....or it's a bug and you don't know about it and asking me if I know anything about it which I don't or else why would I ask the question.....? 😜

**Comment by parg** [comment]
Do you have a functioning IPv6 network that BiglyBT is using? 

If you have bind ip(s) specified under 

Options->Connection->Advanced Network Settings: Bind to local IP address or interface

along with setting 

Options->Connection->Advanced Network Settings: Enforce IP bindings even when interfaces are not available, prevents any connections if none of the specified interfaces are available

then if your bind ip is not available (e.g. it is a VPN and the VPN is down) then BiglyBT will use "localhost" instead of the missing bind ip in order to ensure that the connection attempt fails.

Perhaps you are seeing that
