### ISSUE TITLE
Backup failing from Java exception could have more descriptive error

### ISSUE THREAD

**Issue by dizzyMongoose** [BiglySoftware/BiglyBT#2971]
Java 1.8.0_202 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4942r22, win32, zoom=100, dpi=111
Windows 10 v10.0, amd64 (64 bit)
B3.4.0.0/4 az3

I'm getting a "Backup failed" error message in my notifications:

java.lang.Exception: Failed to copy file 'C:\Users\sherw\AppData\Roaming\BiglyBT\active\0F1EBD20C4CEE36EB2C75CA30A20BD50DD19B124.dat'
	at com.biglybt.core.backup.impl.BackupManagerImpl.copyFilesSupport(BackupManagerImpl.java:707)
	at com.biglybt.core.backup.impl.BackupManagerImpl.copyFilesSupport(BackupManagerImpl.java:666)
	at com.biglybt.core.backup.impl.BackupManagerImpl.copyFiles(BackupManagerImpl.java:606)
	at com.biglybt.core.backup.impl.BackupManagerImpl.backupSupport(BackupManagerImpl.java:928)
	at com.biglybt.core.backup.impl.BackupManagerImpl$7.runSupport(BackupManagerImpl.java:575)
	at com.biglybt.core.util.AsyncDispatcher$1.run(AsyncDispatcher.java:168)
	at com.biglybt.core.util.AEThread2$threadWrapper.run(AEThread2.java:334)

I'm guessing it has to do with running out of space to copy the file, but it'd be nice to have a more user-facing error message.

**Comment by parg** [comment]
You could check the debug_1.log/debug_2.log files in the logs folder (not that I disagree with your comment!)
