### ISSUE TITLE
3d look not working

### ISSUE THREAD

**Issue by legacychimera247** [BiglySoftware/BiglyBT#2973]
hello, downloaded the 3d swarm plugin and this is what i get
![image](https://github.com/BiglySoftware/BiglyBT/assets/22254556/b8baa6a3-7243-4057-80c8-4cb9abb248d1)
i thought, back in the days, that since i am on linux, maybe my nvidia graphic card had problems with it, but recently switched to amd and it's still not working at all

not relevant but it was nice to have...

**Comment by legacychimera247** [comment]
Same, completely blank...
started using linux about ten years ago and the 3d look never worked, on any of my pcs (all were running fedora workstation) and in vuze neither...

**Comment by parg** [comment]
I spun up Fedora and checked the logs - it has 

~/.swt/lib/linux/x86_64/libswt-glx-gtk-4956r12.so: libGLU.so.1: cannot open shared object file: No such file or directory

sudo dnf install mesa-libGLU

fixed it for me

**Comment by legacychimera247** [comment]
seems it's already installed...

**Comment by parg** [comment]
So what error is in your logs?

**Comment by legacychimera247** [comment]
well, how do i see logs?

**Comment by parg** [comment]
~/.biglybt/logs/debug_1.log and debug_2.log

**Comment by legacychimera247** [comment]
[debug_1.log](https://github.com/BiglySoftware/BiglyBT/files/11599307/debug_1.log)
[debug_2.log](https://github.com/BiglySoftware/BiglyBT/files/11599309/debug_2.log)
maybe you want to have a look? :)

**Comment by parg** [comment]
Well the error is

[11:01:26] [stderr] org.eclipse.swt.SWTException: Unsupported color depth
[11:01:26] [stderr] 	at org.eclipse.swt.SWT.error(SWT.java:4889)
[11:01:26] [stderr] 	at org.eclipse.swt.SWT.error(SWT.java:4804)
[11:01:26] [stderr] 	at org.eclipse.swt.SWT.error(SWT.java:4775)
[11:01:26] [stderr] 	at org.eclipse.swt.opengl.GLCanvas.<init>(GLCanvas.java:118)

You have any non-standard settings that might result in that?

You could try disabling

Options->Plugins->3D View: Anti-alias scene using accumulation buffers - can use lots of CPU (e.g. on old Macs)

to see if that prevents the error.

**Comment by legacychimera247** [comment]
that does not help, no non standard settings that i can think of, apart for night light which is anyway disabled since it's day

the only thing i can tell you is that it has never worked for me since i switched to linux (at the time fedora 22 was out, we're now at 38), i had 4 in this cycle, including the current one, with different configurations and specs, but it has never worked (on vuze either)

no problems at all in windows, i recently installed that on a windows machine and works as intended...

**Comment by ferdnyc** [comment]
#WorksForMe, on Fedora 38, and I'm even using a VNC session for display (headless server) so purely software OpenGL.

![image](https://github.com/BiglySoftware/BiglyBT/assets/538020/a5efb0eb-b40c-48f5-8523-b1e279e701c2)

(I don't have any actually-active torrents at the moment.)

**Comment by ferdnyc** [comment]
Interestingly, on my local system with an Nvidia card (using the nouveau open-source drivers), it _doesn't_ work. I get the same "unsupported color depth" error.

But I'm also having (_seemingly_-unrelated?) problems with BiglyBT itself hard-crashing, when `org.eclipse.swt.internal.C::strlen` attempts to call libc's `__strlen_sse2`.

```text
DEBUG::Sun Aug 20 19:14:00 EDT 2023::com.biglybt.ui.swt.pifimpl.UISWTViewImpl::triggerEvent::330:
  ViewID=view3d.name; EventID=Shown; data=null
    BaseMdiEntry::triggerEvent::669, BaseMdiEntry::show::730, SideBarEntrySWT::swt_show::606, SideBarEntrySWT::access$17::583, SideBarEntrySWT$7::runSupport::578, AERunnable::run::36, RunnableLock::run::40, Synchronizer::runAsyncMessages::185, Display::runAsyncMessages::5067, Display::readAndDispatch::4573, SWTThread::<init>::526, SWTThread::createInstance::58, Initializer::<init>::183, UI::takeMainThread::162, Main::main::247, NativeMethodAccessorImpl::invoke0::-2, NativeMethodAccessorImpl::invoke::77, DelegatingMethodAccessorImpl::invoke::43, Method::invoke::568, Launcher$1::run::48, Thread::run::833
org.eclipse.swt.SWTException: Unsupported color depth
	at org.eclipse.swt.SWT.error(SWT.java:4889)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.SWT.error(SWT.java:4775)
	at org.eclipse.swt.opengl.GLCanvas.<init>(GLCanvas.java:118)
	at com.aelitis.azureus.plugins.view3d.Peers3DGraphicView.initialize(Peers3DGraphicView.java:272)
	at com.aelitis.azureus.plugins.view3d.Peers3DGraphicView.<init>(Peers3DGraphicView.java:242)
	at com.aelitis.azureus.plugins.view3d.Panel3D.get3DView(Panel3D.java:83)
	at com.aelitis.azureus.plugins.view3d.Panel3D.initUI(Panel3D.java:228)
	at com.aelitis.azureus.plugins.view3d.Panel3D.initialize(Panel3D.java:127)
	at com.aelitis.azureus.plugins.view3d.Plugin3D$ViewListener.eventOccurred(Plugin3D.java:238)
	at com.biglybt.ui.swt.pifimpl.UISWTViewImpl.triggerBooleanEvent(UISWTViewImpl.java:462)
	at com.biglybt.ui.swt.pifimpl.UISWTViewImpl.triggerEvent(UISWTViewImpl.java:330)
	at com.biglybt.ui.swt.mdi.BaseMdiEntry.triggerEvent(BaseMdiEntry.java:669)
	at com.biglybt.ui.swt.mdi.BaseMdiEntry.show(BaseMdiEntry.java:730)
	at com.biglybt.ui.swt.views.skin.sidebar.SideBarEntrySWT.swt_show(SideBarEntrySWT.java:606)
	at com.biglybt.ui.swt.views.skin.sidebar.SideBarEntrySWT.access$17(SideBarEntrySWT.java:583)
	at com.biglybt.ui.swt.views.skin.sidebar.SideBarEntrySWT$7.runSupport(SideBarEntrySWT.java:578)
	at com.biglybt.core.util.AERunnable.run(AERunnable.java:36)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:5067)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4573)
	at com.biglybt.ui.swt.mainwindow.SWTThread.<init>(SWTThread.java:526)
	at com.biglybt.ui.swt.mainwindow.SWTThread.createInstance(SWTThread.java:58)
	at com.biglybt.ui.swt.Initializer.<init>(Initializer.java:183)
	at com.biglybt.ui.swt.UI.takeMainThread(UI.java:162)
	at com.biglybt.ui.Main.main(Main.java:247)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.biglybt.launcher.Launcher$1.run(Launcher.java:48)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

```text
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f2ba57784fa, pid=1703031, tid=1703051
#
# JRE version: OpenJDK Runtime Environment (Red_Hat-17.0.8.0.7-1.fc38) (17.0.8+7) (build 17.0.8+7)
# Java VM: OpenJDK 64-Bit Server VM (Red_Hat-17.0.8.0.7-1.fc38) (17.0.8+7, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libc.so.6+0xae4fa]  __strlen_sse2+0x2a
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" (or dumping to /home/ferd/.local/lib/biglybt/core.1703031)
#
# An error report file with more information is saved as:
# /home/ferd/.local/lib/biglybt/hs_err_pid1703031.log
Compiled method (n/a)   93878 2879     n 0       org.eclipse.swt.internal.C::strlen (native)
 total in heap  [0x00007f2b90bf9210,0x00007f2b90bf9580] = 880
 relocation     [0x00007f2b90bf9370,0x00007f2b90bf93a0] = 48
 main code      [0x00007f2b90bf93a0,0x00007f2b90bf9578] = 472
 oops           [0x00007f2b90bf9578,0x00007f2b90bf9580] = 8
Compiled method (n/a)   93878 2879     n 0       org.eclipse.swt.internal.C::strlen (native)
 total in heap  [0x00007f2b90bf9210,0x00007f2b90bf9580] = 880
 relocation     [0x00007f2b90bf9370,0x00007f2b90bf93a0] = 48
 main code      [0x00007f2b90bf93a0,0x00007f2b90bf9578] = 472
 oops           [0x00007f2b90bf9578,0x00007f2b90bf9580] = 8
Compiled method (n/a)   93883 2879     n 0       org.eclipse.swt.internal.C::strlen (native)
 total in heap  [0x00007f2b90bf9210,0x00007f2b90bf9580] = 880
 relocation     [0x00007f2b90bf9370,0x00007f2b90bf93a0] = 48
 main code      [0x00007f2b90bf93a0,0x00007f2b90bf9578] = 472
 oops           [0x00007f2b90bf9578,0x00007f2b90bf9580] = 8
#
# If you would like to submit a bug report, please visit:
#   https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora&component=java-17-openjdk-portable&version=38
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
/home/ferd/lib/biglybt/biglybt: line 232: 1703031 Aborted                 (core dumped) ${JAVA_BIN} -Xmx256m -cp "${CLASSPATH}" "-Djava.library.path=${PROGRAM_DIR}" "-Dazureus.install.path=${PROGRAM_DIR}" "-Dazureus.script=$0" ${JAVA_PROPS} ${JAVA_ARGS} ${START_CLASS} ${OTHER_PARAMS} "$@"
Exit from BiglyBT complete
java.lang.reflect.InaccessibleObjectException: Unable to make field private static transient java.net.InetAddress$NameService java.net.InetAddress.nameService accessible: module java.base does not "opens java.net" to unnamed module @4f4207d0
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at com.biglybt.core.util.spi.AENameServiceJava12.init(AENameServiceJava12.java:37)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.biglybt.core.config.COConfigurationManager.preInitialise(COConfigurationManager.java:242)
	at com.biglybt.core.config.impl.ConfigurationChecker.setSystemProperties(ConfigurationChecker.java:85)
	at com.biglybt.core.config.impl.ConfigurationManager.initialise(ConfigurationManager.java:177)
	at com.biglybt.core.config.impl.ConfigurationManager.getInstance(ConfigurationManager.java:110)
	at com.biglybt.core.config.COConfigurationManager.getStringParameter(COConfigurationManager.java:303)
	at com.biglybt.platform.unix.ScriptAfterShutdown.main(ScriptAfterShutdown.java:43)
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by com.biglybt.core.security.impl.ClientSecurityManager (file:/home/ferd/.local/lib/biglybt/BiglyBT.jar)
WARNING: Please consider reporting this to the maintainers of com.biglybt.core.security.impl.ClientSecurityManager
WARNING: System::setSecurityManager will be removed in a future release
No shutdown tasks to do
BiglyBT TERMINATED.
```

**Comment by ferdnyc** [comment]
I'm beginning to suspect that the 3DView plugin issue may be due to incompatibilities between "legacy" LWJGL 2.9.3 ([which is from January 2015](https://legacy.lwjgl.org/)) and... well, Wayland, for starters.

There's a LWJGL3 that replaced the 2.x versions, and is explicitly compatible with things like Linux Wayland, but apparently the API is far from a drop-in replacement for LWJGL2.

**Comment by parg** [comment]
yeah, I looked at LWJGL3 and gave up on it.
