### ISSUE TITLE
[UI] Possible improvement for scroll bars (MacOS)

### ISSUE THREAD

**Issue by superbonaci** [BiglySoftware/BiglyBT#3009]
System:
```
Java 1.8.0_292 (64 bit)
  Azul Systems, Inc.
/Applications/BiglyBT/.install4j/jre.bundle/Contents/Home

SWT v4944r26, cocoa, zoom=200, dpi=72
Mac OS X v13.4.1, aarch64 (64 bit)
B3.4.0.0/4 az3
```

Description of issue:
Select any active torrent, go to Files tab and place the Pieces column at the leftmost place. Then resize it to be wider than the program window.

After that, moving with the mouse in a direction where is no displacement possible, the scroll bars are not shown. For example, if you have already moved to the bottom and left, if you move with the mouse or arrow keys even more in that direction, the scroll bars are not displayed:

<img width="1173" alt="bitly-no-scroll-bars" src="https://github.com/BiglySoftware/BiglyBT/assets/8339596/b16abf91-7d28-4c9e-b490-6ecf277b9450">

To make them actually appear, have to move slightly in the opposite direction where movement is possible then they appear, however the effect fades fast and covers part of the content:

<img width="1174" alt="do-bars" src="https://github.com/BiglySoftware/BiglyBT/assets/8339596/dead18b2-e99f-4d5b-b037-258d23b182c8">

My discussion, is if could be possible to improve this behavior somehow, for example:

- Making the bars permanent for those dimensions where content does not fit screen.
- Making the bar appear outside the limits of the contents, no they don't overlap (how Vuze 5.7.7.0 does).
- Make the bard appear even when trying to scroll in a direction where movement is not possible.

![vuze-always-bars](https://github.com/BiglySoftware/BiglyBT/assets/8339596/88741851-7890-4e67-9d34-8c2787878010)

**Comment by parg** [comment]
Can you switch to Java 11 or higher?

https://github.com/BiglySoftware/BiglyBT/wiki/Java-Versions

With Java 11+ you get a more recent SWT UI library, might help.

**Comment by superbonaci** [comment]
I have a higher version of java installed, in fact I installed both openjdk and bitlybt (cask) with brew.sh:
```
$ java -version
openjdk version "20.0.1" 2023-04-18
OpenJDK Runtime Environment Homebrew (build 20.0.1)
OpenJDK 64-Bit Server VM Homebrew (build 20.0.1, mixed mode, sharing)
```
```
$ /usr/libexec/java_home -V
Matching Java Virtual Machines (2):
    20.0.1 (arm64) "Homebrew" - "OpenJDK 20.0.1" /opt/homebrew/Cellar/openjdk/20.0.1/libexec/openjdk.jdk/Contents/Home
    1.8.0_382 (arm64) "Azul Systems, Inc." - "Zulu 8.72.0.17" /Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home
/opt/homebrew/Cellar/openjdk/20.0.1/libexec/openjdk.jdk/Contents/Home
```
```
$ ls -1A /Library/Java/JavaVirtualMachines
openjdk.jdk
zulu-8.jdk
```

I don't a configuration setting to change where the java installation is located.

**Comment by parg** [comment]
Could you try installing Java 11 as well? I'm not an OSX guru but there might be a maximum Java version that the launcher will accept.

**Comment by superbonaci** [comment]
Installed but no biglybt change:
```
Java 1.8.0_292 (64 bit)
  Azul Systems, Inc.
/Applications/BiglyBT/.install4j/jre.bundle/Contents/Home

SWT v4944r26, cocoa, zoom=200, dpi=72
Mac OS X v13.4.1, aarch64 (64 bit)
B3.4.0.0/4 az3
```
This is the system:
```
$ ls -1A /opt/homebrew/Cellar/openjdk*
/opt/homebrew/Cellar/openjdk:
20.0.1

/opt/homebrew/Cellar/openjdk@11:
11.0.20
```
```
brew list openjdk@11
/opt/homebrew/Cellar/openjdk@11/11.0.20/bin/jar
/opt/homebrew/Cellar/openjdk@11/11.0.20/bin/jarsigner
/opt/homebrew/Cellar/openjdk@11/11.0.20/bin/java
/opt/homebrew/Cellar/openjdk@11/11.0.20/bin/javac
/opt/homebrew/Cellar/openjdk@11/11.0.20/bin/javadoc
/opt/homebrew/Cellar/openjdk@11/11.0.20/bin/javap
/opt/homebrew/Cellar/openjdk@11/11.0.20/bin/jcmd
/opt/homebrew/Cellar/openjdk@11/11.0.20/bin/jconsole
/opt/homebrew/Cellar/openjdk@11/11.0.20/bin/jdb
/opt/homebrew/Cellar/openjdk@11/11.0.20/bin/jdeprscan
/opt/homebrew/Cellar/openjdk@11/11.0.20/bin/jdeps
/opt/homebrew/Cellar/openjdk@11/11.0.20/bin/jfr
/opt/homebrew/Cellar/openjdk@11/11.0.20/bin/jhsdb
/opt/homebrew/Cellar/openjdk@11/11.0.20/bin/jimage
/opt/homebrew/Cellar/openjdk@11/11.0.20/bin/jinfo
/opt/homebrew/Cellar/openjdk@11/11.0.20/bin/jjs
/opt/homebrew/Cellar/openjdk@11/11.0.20/bin/jlink
/opt/homebrew/Cellar/openjdk@11/11.0.20/bin/jmap
/opt/homebrew/Cellar/openjdk@11/11.0.20/bin/jmod
/opt/homebrew/Cellar/openjdk@11/11.0.20/bin/jps
/opt/homebrew/Cellar/openjdk@11/11.0.20/bin/jrunscript
/opt/homebrew/Cellar/openjdk@11/11.0.20/bin/jshell
/opt/homebrew/Cellar/openjdk@11/11.0.20/bin/jstack
/opt/homebrew/Cellar/openjdk@11/11.0.20/bin/jstat
/opt/homebrew/Cellar/openjdk@11/11.0.20/bin/jstatd
/opt/homebrew/Cellar/openjdk@11/11.0.20/bin/keytool
/opt/homebrew/Cellar/openjdk@11/11.0.20/bin/pack200
/opt/homebrew/Cellar/openjdk@11/11.0.20/bin/rmic
/opt/homebrew/Cellar/openjdk@11/11.0.20/bin/rmid
/opt/homebrew/Cellar/openjdk@11/11.0.20/bin/rmiregistry
/opt/homebrew/Cellar/openjdk@11/11.0.20/bin/serialver
/opt/homebrew/Cellar/openjdk@11/11.0.20/bin/unpack200
/opt/homebrew/Cellar/openjdk@11/11.0.20/include/ (8 files)
/opt/homebrew/Cellar/openjdk@11/11.0.20/libexec/openjdk.jdk/ (598 files)
/opt/homebrew/Cellar/openjdk@11/11.0.20/share/man/ (25 files)
```

**Comment by parg** [comment]
You could experiment by launching BiglyBT from the command line:

https://github.com/BiglySoftware/BiglyBT/wiki/Command-Line-Options#macos

As it says, it won't handle BiglyBT restart correctly.

**Comment by superbonaci** [comment]
Yes, when running from the command line detect newer java version:
```
Java 20.0.1 (64 bit)
  Homebrew
/opt/homebrew/Cellar/openjdk/20.0.1/libexec/openjdk.jdk/Contents/Home

SWT v4944r26, cocoa, zoom=200, dpi=72
Mac OS X v13.5, aarch64 (64 bit)
B3.4.0.0/4 az3
```

If you could just fix the dmg.

**Comment by superbonaci** [comment]
Still the issues are happening.

**Comment by parg** [comment]
With Java 20 you should be updated to SWT version 4956r21, you are still be on 4944r26.

Did you get prompted to restart to complete the update? If so then close BiglyBT and re-launch via command line.

**Comment by superbonaci** [comment]
Restarting several times doesn't fix it, still in v4944r26.

**Comment by parg** [comment]
If you explicitly run Help->Check For Updates and then click on the "progress reporting" icon in the BiglyBT status bar what does it show for SWT update checks?

For example, I get

```
Checking for Updates - added
Checking for Updates
    BiglyBT Core -     Core: latest_version = '3.4.0.1_B12', file = 'http://version.biglybt.com/biglybt-files/core/BiglyBT3401-B12-signed.jar.torrent?i2p=1'
    SWT library -     SWT: current version = 4956r13, latest version = 4956r12
    SWT library - Finished
    BiglyBT Core -     Adding update: Core BiglyBT Version

```

**Comment by superbonaci** [comment]
Fails to check for updates:
```
DEBUG::Thu Jul 27 15:39:11 2023::com.biglybt.core.proxy.impl.AEPluginProxyHandler::installTor::785:
  Tor Helper install declined (either user reply or auto-remembered)
    AEPluginProxyHandler::checkPluginInstallation::629, AEPluginProxyHandler::getPluginProxy::270, AEProxyFactory::getPluginProxy::116, AEProxyFactory::getPluginProxy::97, AEProxyFactory::getPluginProxy::88, VersionCheckClient::executeHTTP::979, VersionCheckClient::performVersionCheck::864, VersionCheckClient::getVersionCheckInfoSupport::342, VersionCheckClient::getVersionCheckInfo::230, VersionCheckClient::getVersionCheckInfo::212, CoreUpdateChecker::checkForUpdate::230, UpdateCheckInstanceImpl$3::run::330, AEThread2$threadWrapper::run::334
DEBUG::Thu Jul 27 15:39:11 2023  VersionCheckClient - java.net.SocketException: Unexpected end of file from server
[plug] [CoreUpdater]
DEBUG::Thu Jul 27 15:39:11 2023::com.biglybt.update.CoreUpdateChecker::checkForUpdate::471:
  java.net.SocketException: Unexpected end of file from server
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:956)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:760)
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:953)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:760)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1672)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1581)
	at com.biglybt.core.versioncheck.VersionCheckClient.executeHTTP(VersionCheckClient.java:963)
	at com.biglybt.core.versioncheck.VersionCheckClient.performVersionCheck(VersionCheckClient.java:864)
	at com.biglybt.core.versioncheck.VersionCheckClient.getVersionCheckInfoSupport(VersionCheckClient.java:342)
	at com.biglybt.core.versioncheck.VersionCheckClient.getVersionCheckInfo(VersionCheckClient.java:230)
	at com.biglybt.core.versioncheck.VersionCheckClient.getVersionCheckInfo(VersionCheckClient.java:212)
	at com.biglybt.update.CoreUpdateChecker.checkForUpdate(CoreUpdateChecker.java:230)
	at com.biglybt.pifimpl.local.update.UpdateCheckInstanceImpl$3.run(UpdateCheckInstanceImpl.java:330)
	at com.biglybt.core.util.AEThread2$threadWrapper.run(AEThread2.java:334)

DEBUG::Thu Jul 27 15:39:11 2023::com.biglybt.update.CoreUpdateChecker::checkForUpdate::473:
  java.net.SocketException: Unexpected end of file from server
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:956)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:760)
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:953)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:760)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1672)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1581)
	at com.biglybt.core.versioncheck.VersionCheckClient.executeHTTP(VersionCheckClient.java:963)
	at com.biglybt.core.versioncheck.VersionCheckClient.performVersionCheck(VersionCheckClient.java:864)
	at com.biglybt.core.versioncheck.VersionCheckClient.getVersionCheckInfoSupport(VersionCheckClient.java:342)
	at com.biglybt.core.versioncheck.VersionCheckClient.getVersionCheckInfo(VersionCheckClient.java:230)
	at com.biglybt.core.versioncheck.VersionCheckClient.getVersionCheckInfo(VersionCheckClient.java:212)
	at com.biglybt.update.CoreUpdateChecker.checkForUpdate(CoreUpdateChecker.java:230)
	at com.biglybt.pifimpl.local.update.UpdateCheckInstanceImpl$3.run(UpdateCheckInstanceImpl.java:330)
	at com.biglybt.core.util.AEThread2$threadWrapper.run(AEThread2.java:334)

DEBUG::Thu Jul 27 15:39:11 2023  VersionCheckClient - java.net.SocketException: Unexpected end of file from server
DEBUG::Thu Jul 27 15:39:11 2023  VersionCheckClient - java.net.SocketException: Unexpected end of file from server
```

**Comment by parg** [comment]
Did you enable "Options->Interface->Start: Update anonymously. Requires I2P and Tor plugins to be installed and can cause updates to fail." ?

**Comment by superbonaci** [comment]
No, and it's disabled. Here's the full launch log because I think the issue is somewhere else:
```
#! /bin/bash

BIGLYBT=/Applications/BiglyBT/.biglybt

java -XstartOnFirstThread -cp $BIGLYBT/BiglyBT.jar:$BIGLYBT/commons-cli.jar:$BIGLYBT/log4j.jar:$BIGLYBT/swt.jar -Duser.dir=$BIGLYBT com.biglybt.ui.Main
java.lang.reflect.InaccessibleObjectException: Unable to make field private static final java.net.spi.InetAddressResolver java.net.InetAddress.BUILTIN_RESOLVER accessible: module java.base does not "opens java.net" to unnamed module @3f3e6f71
	at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(AccessibleObject.java:387)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:363)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:311)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:181)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:175)
	at com.biglybt.core.util.spi.AENameServiceJava18.init(AENameServiceJava18.java:39)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at com.biglybt.core.config.COConfigurationManager.preInitialise(COConfigurationManager.java:238)
	at com.biglybt.ui.Main.main(Main.java:85)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at com.biglybt.launcher.Launcher$1.run(Launcher.java:48)
	at com.biglybt.launcher.Launcher.launch(Launcher.java:65)
	at com.biglybt.launcher.Launcher.checkAndLaunch(Launcher.java:83)
	at com.biglybt.ui.Main.main(Main.java:80)
DEBUG::Fri Jul 28 21:28:05 2023::com.biglybt.core.security.impl.SESecurityManagerImpl::installSecurityManager::386:
  java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at com.biglybt.core.security.impl.ClientSecurityManager.<init>(ClientSecurityManager.java:70)
	at com.biglybt.core.security.impl.SESecurityManagerImpl.installSecurityManager(SESecurityManagerImpl.java:382)
	at com.biglybt.core.security.impl.SESecurityManagerImpl.initialise(SESecurityManagerImpl.java:217)
	at com.biglybt.core.security.SESecurityManager.initialise(SESecurityManager.java:55)
	at com.biglybt.core.config.impl.ConfigurationChecker.setSystemProperties(ConfigurationChecker.java:287)
	at com.biglybt.core.config.impl.ConfigurationManager.initialise(ConfigurationManager.java:177)
	at com.biglybt.core.config.impl.ConfigurationManager.getInstance(ConfigurationManager.java:110)
	at com.biglybt.core.config.COConfigurationManager.addAndFireParameterListener(COConfigurationManager.java:614)
	at com.biglybt.ui.swt.UI.<clinit>(UI.java:73)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:391)
	at java.base/java.lang.Class.forName(Class.java:382)
	at com.biglybt.ui.common.UserInterfaceFactory.getUI(UserInterfaceFactory.java:33)
	at com.biglybt.ui.Main.buildUIList(Main.java:323)
	at com.biglybt.ui.Main.main(Main.java:115)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at com.biglybt.launcher.Launcher$1.run(Launcher.java:48)
	at com.biglybt.launcher.Launcher.launch(Launcher.java:65)
	at com.biglybt.launcher.Launcher.checkAndLaunch(Launcher.java:83)
	at com.biglybt.ui.Main.main(Main.java:80)

Enabling broken select detection: diablo=false, freebsd 7+=false, osx 10.6+=true
UIFunctions/ImageLoad took 0ms
new shell took 0ms
new shell setup took 30ms
skin init took 30ms
MainMenu init took 30ms
pre skin widgets init took 0ms
skin widgets (1/2) init took 88ms
skin widgets (2/2) init took 30ms
pre SWTInstance init took 0ms
Init Core Columns took 30ms
SWTInstance init took 0ms
shell.layout took 0ms
---------SHOWN AT 1690540086152;733ms
---------DONE DISPATCH AT 1690540086329;910ms
---------READY AT 1690540086329;910ms
shell.open took 207ms
processStartupDMS took 0ms
postPluginSetup init took 0ms
Locale Initializing took 0ms
Core Initializing took 229ms
psDMS 0ms
DEBUG::Fri Jul 28 21:28:06 2023  VersionCheckClient - java.net.SocketException: Unexpected end of file from server
java.net.NoRouteToHostException: No route to host
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:580)
	at java.base/sun.nio.ch.DatagramChannelImpl.connect(DatagramChannelImpl.java:1314)
	at java.base/sun.nio.ch.DatagramChannelImpl.connect(DatagramChannelImpl.java:1272)
	at lbms.plugins.mldht.kad.utils.AddressUtils.getDefaultRoute(AddressUtils.java:221)
	at lbms.plugins.mldht.kad.DHT.start(DHT.java:734)
	at lbms.plugins.mldht.azureus.MlDHTPlugin$9.runSupport(MlDHTPlugin.java:680)
	at com.biglybt.core.util.AsyncDispatcher$1.run(AsyncDispatcher.java:168)
	at com.biglybt.core.util.AEThread2$threadWrapper.run(AEThread2.java:334)
DEBUG::Fri Jul 28 21:28:06 2023::com.biglybt.core.proxy.impl.AEPluginProxyHandler::installTor::785:
  Tor Helper install declined (either user reply or auto-remembered)
    AEPluginProxyHandler::checkPluginInstallation::629, AEPluginProxyHandler::getPluginProxy::270, AEProxyFactory::getPluginProxy::116, AEProxyFactory::getPluginProxy::97, AEProxyFactory::getPluginProxy::88, VersionCheckClient::executeHTTP::979, VersionCheckClient::performVersionCheck::864, VersionCheckClient::getVersionCheckInfoSupport::342, VersionCheckClient::getVersionCheckInfo::230, VersionCheckClient::DHTEnableAllowed::698, DHTPlugin$14::run::1008, AEThread2$threadWrapper::run::334
DEBUG::Fri Jul 28 21:28:06 2023  VersionCheckClient - java.net.SocketException: Unexpected end of file from server
DEBUG::Fri Jul 28 21:28:07 2023  VersionCheckClient - java.net.SocketException: Unexpected end of file from server
Starting idle sleep preventer: /usr/bin/caffeinate
DEBUG::Fri Jul 28 21:28:07 2023  VersionCheckClient - java.net.SocketException: Unexpected end of file from server
DEBUG::Fri Jul 28 21:28:07 2023  VersionCheckClient - java.net.SocketException: Unexpected end of file from server
DEBUG::Fri Jul 28 21:28:07 2023  VersionCheckClient - java.net.SocketException: Unexpected end of file from server
java.io.UncheckedIOException: java.net.SocketException: Can't connect to port 0
	at java.base/sun.nio.ch.DatagramSocketAdaptor.connect(DatagramSocketAdaptor.java:124)
	at java.base/java.net.DatagramSocket.connect(DatagramSocket.java:472)
	at com.vuze.plugin.azVPN_Helper.CheckerCommon.handleFindBindingAddress(CheckerCommon.java:439)
	at com.vuze.plugin.azVPN_Helper.CheckerCommon.handleFindBindingAddress(CheckerCommon.java:263)
	at com.vuze.plugin.azVPN_Helper.CheckerCommon.findBindingAddress(CheckerCommon.java:739)
	at com.vuze.plugin.azVPN_Helper.CheckerCommon.portBindingCheck(CheckerCommon.java:764)
	at com.vuze.plugin.azVPN_Helper.PluginVPNHelper$4.runSupport(PluginVPNHelper.java:402)
	at com.biglybt.core.util.AERunnable.run(AERunnable.java:36)
	at com.biglybt.pifimpl.local.utils.UtilitiesImpl.callWithPluginThreadContext(UtilitiesImpl.java:1049)
	at com.biglybt.pifimpl.local.utils.UtilitiesImpl$2.run(UtilitiesImpl.java:375)
	at com.biglybt.core.util.AEThread2$threadWrapper.run(AEThread2.java:334)
Caused by: java.net.SocketException: Can't connect to port 0
	at java.base/sun.nio.ch.DatagramChannelImpl.connect(DatagramChannelImpl.java:1304)
	at java.base/sun.nio.ch.DatagramSocketAdaptor.connectInternal(DatagramSocketAdaptor.java:95)
	at java.base/sun.nio.ch.DatagramSocketAdaptor.connect(DatagramSocketAdaptor.java:122)
	... 10 more
java.io.UncheckedIOException: java.net.SocketException: Can't connect to port 0
	at java.base/sun.nio.ch.DatagramSocketAdaptor.connect(DatagramSocketAdaptor.java:124)
	at java.base/java.net.DatagramSocket.connect(DatagramSocket.java:472)
	at com.vuze.plugin.azVPN_Helper.CheckerCommon.handleFindBindingAddress(CheckerCommon.java:439)
	at com.vuze.plugin.azVPN_Helper.CheckerCommon.handleFindBindingAddress(CheckerCommon.java:564)
	at com.vuze.plugin.azVPN_Helper.CheckerCommon.handleFindBindingAddress(CheckerCommon.java:263)
	at com.vuze.plugin.azVPN_Helper.CheckerCommon.findBindingAddress(CheckerCommon.java:739)
	at com.vuze.plugin.azVPN_Helper.CheckerCommon.portBindingCheck(CheckerCommon.java:764)
	at com.vuze.plugin.azVPN_Helper.PluginVPNHelper$4.runSupport(PluginVPNHelper.java:402)
	at com.biglybt.core.util.AERunnable.run(AERunnable.java:36)
	at com.biglybt.pifimpl.local.utils.UtilitiesImpl.callWithPluginThreadContext(UtilitiesImpl.java:1049)
	at com.biglybt.pifimpl.local.utils.UtilitiesImpl$2.run(UtilitiesImpl.java:375)
	at com.biglybt.core.util.AEThread2$threadWrapper.run(AEThread2.java:334)
Caused by: java.net.SocketException: Can't connect to port 0
	at java.base/sun.nio.ch.DatagramChannelImpl.connect(DatagramChannelImpl.java:1304)
	at java.base/sun.nio.ch.DatagramSocketAdaptor.connectInternal(DatagramSocketAdaptor.java:95)
	at java.base/sun.nio.ch.DatagramSocketAdaptor.connect(DatagramSocketAdaptor.java:122)
	... 11 more
DEBUG::Fri Jul 28 21:28:07 2023  VersionCheckClient - java.net.SocketException: Unexpected end of file from server
DEBUG::Fri Jul 28 21:28:07 2023  VersionCheckClient - java.net.SocketException: Unexpected end of file from server
DEBUG::Fri Jul 28 21:28:08 2023  VersionCheckClient - java.net.SocketException: Unexpected end of file from server
[net] PRUDPPacketHandler: sendAndReceive to version.biglybt.com/34.203.76.220:2080 failed: Can't assign requested address
[net] PRUDPPacketHandler: sendAndReceive to version.biglybt.com/34.203.76.220:2080 failed: Can't assign requested address
[net] PRUDPPacketHandler: sendAndReceive to version.biglybt.com/34.203.76.220:2080 failed: Can't assign requested address
java.io.UncheckedIOException: java.net.SocketException: Can't connect to port 0
	at java.base/sun.nio.ch.DatagramSocketAdaptor.connect(DatagramSocketAdaptor.java:124)
	at java.base/java.net.DatagramSocket.connect(DatagramSocket.java:472)
	at com.vuze.plugin.azVPN_Helper.CheckerCommon.handleFindBindingAddress(CheckerCommon.java:439)
	at com.vuze.plugin.azVPN_Helper.CheckerCommon.handleFindBindingAddress(CheckerCommon.java:263)
	at com.vuze.plugin.azVPN_Helper.CheckerCommon.findBindingAddress(CheckerCommon.java:739)
	at com.vuze.plugin.azVPN_Helper.CheckerCommon.portBindingCheck(CheckerCommon.java:764)
	at com.vuze.plugin.azVPN_Helper.Checker_PIA.processCLI(Checker_PIA.java:285)
	at com.vuze.plugin.azVPN_Helper.Checker_PIA.lambda$0(Checker_PIA.java:228)
	at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: java.net.SocketException: Can't connect to port 0
	at java.base/sun.nio.ch.DatagramChannelImpl.connect(DatagramChannelImpl.java:1304)
	at java.base/sun.nio.ch.DatagramSocketAdaptor.connectInternal(DatagramSocketAdaptor.java:95)
	at java.base/sun.nio.ch.DatagramSocketAdaptor.connect(DatagramSocketAdaptor.java:122)
	... 8 more
java.io.UncheckedIOException: java.net.SocketException: Can't connect to port 0
	at java.base/sun.nio.ch.DatagramSocketAdaptor.connect(DatagramSocketAdaptor.java:124)
	at java.base/java.net.DatagramSocket.connect(DatagramSocket.java:472)
	at com.vuze.plugin.azVPN_Helper.CheckerCommon.handleFindBindingAddress(CheckerCommon.java:439)
	at com.vuze.plugin.azVPN_Helper.CheckerCommon.handleFindBindingAddress(CheckerCommon.java:564)
	at com.vuze.plugin.azVPN_Helper.CheckerCommon.handleFindBindingAddress(CheckerCommon.java:263)
	at com.vuze.plugin.azVPN_Helper.CheckerCommon.findBindingAddress(CheckerCommon.java:739)
	at com.vuze.plugin.azVPN_Helper.CheckerCommon.portBindingCheck(CheckerCommon.java:764)
	at com.vuze.plugin.azVPN_Helper.Checker_PIA.processCLI(Checker_PIA.java:285)
	at com.vuze.plugin.azVPN_Helper.Checker_PIA.lambda$0(Checker_PIA.java:228)
	at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: java.net.SocketException: Can't connect to port 0
	at java.base/sun.nio.ch.DatagramChannelImpl.connect(DatagramChannelImpl.java:1304)
	at java.base/sun.nio.ch.DatagramSocketAdaptor.connectInternal(DatagramSocketAdaptor.java:95)
	at java.base/sun.nio.ch.DatagramSocketAdaptor.connect(DatagramSocketAdaptor.java:122)
	... 9 more
core.stop
Stopping idle sleep preventer
core.stop done in 2551
```

**Comment by parg** [comment]
Hard to say, do you have BiglyBT bound to a network interface? Or a VPN semi-configured?

**Comment by superbonaci** [comment]
The issue only happens when launching from command line, when opening the .app it checks for updates successfully. I don't have any bound network interface or VPN semi-configured that I know of. All my other programs works perfectly.
