### ISSUE TITLE
Can't start, after installation.

### ISSUE THREAD

**Issue by Achaean** [BiglySoftware/BiglyBT#3018]
I just installed the latest Bigly on a Debian oldstable based distro.
```
>java --version
openjdk 17.0.7 2023-04-18
OpenJDK Runtime Environment (build 17.0.7+7-Debian-1deb11u1)
OpenJDK 64-Bit Server VM (build 17.0.7+7-Debian-1deb11u1, mixed mode, sharing)
>
```
However Bigly can't start and autoclosing.
Here's console's output:
```
>./biglybt
Starting BiglyBT...
Suitable java version found [java = openjdk 17.0.7 2023-04-18]
Using swt/swt-x86_64.jar v4.942
java.lang.reflect.InaccessibleObjectException: Unable to make field private static transient java.net.InetAddress$NameService java.net.InetAddress.nameService accessible: module java.base does not "opens java.net" to unnamed module @6f2fd062
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at com.biglybt.core.util.spi.AENameServiceJava12.init(AENameServiceJava12.java:37)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.biglybt.core.config.COConfigurationManager.preInitialise(COConfigurationManager.java:242)
	at com.biglybt.core.config.impl.ConfigurationChecker.setSystemProperties(ConfigurationChecker.java:85)
	at com.biglybt.core.config.impl.ConfigurationManager.initialise(ConfigurationManager.java:177)
	at com.biglybt.core.config.impl.ConfigurationManager.getInstance(ConfigurationManager.java:110)
	at com.biglybt.core.config.COConfigurationManager.getStringParameter(COConfigurationManager.java:303)
	at com.biglybt.platform.unix.ScriptBeforeStartup.main(ScriptBeforeStartup.java:62)
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by com.biglybt.core.security.impl.ClientSecurityManager (file:/home/giorgos/biglybt/BiglyBT.jar)
WARNING: Please consider reporting this to the maintainers of com.biglybt.core.security.impl.ClientSecurityManager
WARNING: System::setSecurityManager will be removed in a future release
Loading BiglyBT:
java.lang.reflect.InaccessibleObjectException: Unable to make field private static transient java.net.InetAddress$NameService java.net.InetAddress.nameService accessible: module java.base does not "opens java.net" to unnamed module @6f2fd062
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at com.biglybt.core.util.spi.AENameServiceJava12.init(AENameServiceJava12.java:37)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.biglybt.core.config.COConfigurationManager.preInitialise(COConfigurationManager.java:242)
	at com.biglybt.ui.Main.main(Main.java:85)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.biglybt.launcher.Launcher$1.run(Launcher.java:48)
	at java.base/java.lang.Thread.run(Thread.java:833)
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by com.biglybt.core.security.impl.ClientSecurityManager (file:/home/giorgos/biglybt/BiglyBT.jar)
WARNING: Please consider reporting this to the maintainers of com.biglybt.core.security.impl.ClientSecurityManager
WARNING: System::setSecurityManager will be removed in a future release
changeLocale: *Default Language* != English (United States). Searching without country..
changeLocale: Searching for language English in *any* country..
changeLocale: no message properties for Locale 'English (United States)' (en_US), using 'English (default)'
[alert] Alert:3:Installation of at least one component failed. See <A HREF="https://wiki.biglybt.com/w/Failed_Update">BiglyBT Wiki: Failed Update</A> [install.act,install.act.utf8]
UIFunctions/ImageLoad took 0ms
new shell took 151ms
new shell setup took 100ms
skin init took 151ms
MainMenu init took 101ms
pre skin widgets init took 75ms
skin widgets (1/2) init took 352ms
skin widgets (2/2) init took 150ms
pre SWTInstance init took 0ms
Init Core Columns took 101ms
SWTInstance init took 0ms
shell.layout took 101ms
---------SHOWN AT 1690649397828;1726ms
---------DONE DISPATCH AT 1690649398481;2379ms
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Jul 29, 2023 7:49:59 PM com.sun.jna.Native$1 uncaughtException
WARNING: JNA: Callback dorkbox.util.jna.linux.GtkEventDispatch$5@7a5f215b threw the following exception
org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(SWT.java:4889)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.SWT.error(SWT.java:4775)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:555)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:471)
	at org.eclipse.swt.widgets.Control.isVisible(Control.java:4514)
	at org.eclipse.swt.widgets.ProgressBar.timerProc(ProgressBar.java:311)
	at org.eclipse.swt.widgets.Display.windowTimerProc(Display.java:6101)
	at dorkbox.util.jna.linux.Gtk3.g_main_loop_run(Native Method)
	at dorkbox.util.jna.linux.GtkEventDispatch$2.run(GtkEventDispatch.java:107)

---------READY AT 1690649399643;3553ms
shell.open took 1840ms
processStartupDMS took 0ms
postPluginSetup init took 0ms
Locale Initializing took 0ms
Core Initializing took 1336ms
INFO: Native CPUID library libjcpuid-x86-linux.so loaded from resource
psDMS 0ms
INFO: Resource name [libjbigi-linux-jaguar_64.so] was not found
INFO: Resource name [libjbigi-linux-jaguar.so] was not found
INFO: Loaded library: jar:file:/home/giorgos/.biglybt/plugins/azneti2phelper/jbigi-linux_0.5.jar!/libjbigi-linux-bobcat_64.so
INFO: Native BigInteger library libjbigi-linux-bobcat_64.so loaded from resource
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
java: ../../src/xcb_io.c:269: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
java: ../../src/xcb_io.c:269: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
./biglybt: line 227:  4229 Aborted                 (core dumped) ${JAVA_PROGRAM_DIR}java -Xmx256m -cp "${CLASSPATH}" "-Djava.library.path=${PROGRAM_DIR}" "-Dazureus.install.path=${PROGRAM_DIR}" "-Dazureus.script=$0" ${JAVA_PROPS} ${JAVA_ARGS} ${START_CLASS} ${OTHER_PARAMS} "$@"
Exit from BiglyBT complete
java.lang.reflect.InaccessibleObjectException: Unable to make field private static transient java.net.InetAddress$NameService java.net.InetAddress.nameService accessible: module java.base does not "opens java.net" to unnamed module @6f2fd062
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at com.biglybt.core.util.spi.AENameServiceJava12.init(AENameServiceJava12.java:37)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.biglybt.core.config.COConfigurationManager.preInitialise(COConfigurationManager.java:242)
	at com.biglybt.core.config.impl.ConfigurationChecker.setSystemProperties(ConfigurationChecker.java:85)
	at com.biglybt.core.config.impl.ConfigurationManager.initialise(ConfigurationManager.java:177)
	at com.biglybt.core.config.impl.ConfigurationManager.getInstance(ConfigurationManager.java:110)
	at com.biglybt.core.config.COConfigurationManager.getStringParameter(COConfigurationManager.java:303)
	at com.biglybt.platform.unix.ScriptAfterShutdown.main(ScriptAfterShutdown.java:43)
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by com.biglybt.core.security.impl.ClientSecurityManager (file:/home/giorgos/biglybt/BiglyBT.jar)
WARNING: Please consider reporting this to the maintainers of com.biglybt.core.security.impl.ClientSecurityManager
WARNING: System::setSecurityManager will be removed in a future release
No shutdown tasks to do
BiglyBT TERMINATED.
>
```

**Comment by parg** [comment]
Try removing the dorkbox .jar file

**Comment by Achaean** [comment]
OK! I delete the dorkbox-systemtray.jar file and start again.

Now it starts, but it complains for the DNS manager installation failure.

![Screenshot](https://github.com/BiglySoftware/BiglyBT/assets/3608053/52afa530-4e20-4ba3-89a4-d12de57969a9)

Console's output:
```
./biglybt
Starting BiglyBT...
Suitable java version found [java = openjdk 17.0.7 2023-04-18]
Using swt/swt-x86_64.jar v4.942
java.lang.reflect.InaccessibleObjectException: Unable to make field private static transient java.net.InetAddress$NameService java.net.InetAddress.nameService accessible: module java.base does not "opens java.net" to unnamed module @6f2fd062
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at com.biglybt.core.util.spi.AENameServiceJava12.init(AENameServiceJava12.java:37)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.biglybt.core.config.COConfigurationManager.preInitialise(COConfigurationManager.java:242)
	at com.biglybt.core.config.impl.ConfigurationChecker.setSystemProperties(ConfigurationChecker.java:85)
	at com.biglybt.core.config.impl.ConfigurationManager.initialise(ConfigurationManager.java:177)
	at com.biglybt.core.config.impl.ConfigurationManager.getInstance(ConfigurationManager.java:110)
	at com.biglybt.core.config.COConfigurationManager.getStringParameter(COConfigurationManager.java:303)
	at com.biglybt.platform.unix.ScriptBeforeStartup.main(ScriptBeforeStartup.java:62)
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by com.biglybt.core.security.impl.ClientSecurityManager (file:/home/giorgos/biglybt/BiglyBT.jar)
WARNING: Please consider reporting this to the maintainers of com.biglybt.core.security.impl.ClientSecurityManager
WARNING: System::setSecurityManager will be removed in a future release
Loading BiglyBT:
java.lang.reflect.InaccessibleObjectException: Unable to make field private static transient java.net.InetAddress$NameService java.net.InetAddress.nameService accessible: module java.base does not "opens java.net" to unnamed module @6f2fd062
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at com.biglybt.core.util.spi.AENameServiceJava12.init(AENameServiceJava12.java:37)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.biglybt.core.config.COConfigurationManager.preInitialise(COConfigurationManager.java:242)
	at com.biglybt.ui.Main.main(Main.java:85)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.biglybt.launcher.Launcher$1.run(Launcher.java:48)
	at java.base/java.lang.Thread.run(Thread.java:833)
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by com.biglybt.core.security.impl.ClientSecurityManager (file:/home/giorgos/biglybt/BiglyBT.jar)
WARNING: Please consider reporting this to the maintainers of com.biglybt.core.security.impl.ClientSecurityManager
WARNING: System::setSecurityManager will be removed in a future release
changeLocale: *Default Language* != English (United States). Searching without country..
changeLocale: Searching for language English in *any* country..
changeLocale: no message properties for Locale 'English (United States)' (en_US), using 'English (default)'
UIFunctions/ImageLoad took 25ms
new shell took 126ms
new shell setup took 127ms
skin init took 151ms
MainMenu init took 126ms
pre skin widgets init took 84ms
skin widgets (1/2) init took 352ms
skin widgets (2/2) init took 126ms
pre SWTInstance init took 0ms
Init Core Columns took 126ms
SWTInstance init took 0ms
shell.layout took 100ms
---------SHOWN AT 1690841491315;1800ms
---------DONE DISPATCH AT 1690841491692;2177ms
DEBUG::Tue Aug 01 01:11:31 EEST 2023  com.biglybt.ui.swt.systray.TrayDork
---------READY AT 1690841491718;2203ms
shell.open took 403ms
processStartupDMS took 0ms
postPluginSetup init took 0ms
Locale Initializing took 25ms
INFO: Native CPUID library libjcpuid-x86-linux.so loaded from resource
INFO: Resource name [libjbigi-linux-jaguar_64.so] was not found
INFO: Resource name [libjbigi-linux-jaguar.so] was not found
INFO: Loaded library: jar:file:/home/giorgos/.biglybt/plugins/azneti2phelper/jbigi-linux_0.5.jar!/libjbigi-linux-bobcat_64.so
INFO: Native BigInteger library libjbigi-linux-bobcat_64.so loaded from resource
Core Initializing took 1388ms
Warning - No client apps or router console configured - we are just a router
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:579)
	at java.base/sun.nio.ch.DatagramChannelImpl.connect(DatagramChannelImpl.java:1249)
	at java.base/sun.nio.ch.DatagramChannelImpl.connect(DatagramChannelImpl.java:1207)
	at lbms.plugins.mldht.kad.utils.AddressUtils.getDefaultRoute(AddressUtils.java:221)
	at lbms.plugins.mldht.kad.DHT.start(DHT.java:734)
	at lbms.plugins.mldht.azureus.MlDHTPlugin$9.runSupport(MlDHTPlugin.java:680)
	at com.biglybt.core.util.AsyncDispatcher$1.run(AsyncDispatcher.java:168)
	at com.biglybt.core.util.AEThread2$threadWrapper.run(AEThread2.java:334)

(BiglyBT:15840): Gtk-CRITICAL **: 01:11:38.252: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(BiglyBT:15840): Gtk-CRITICAL **: 01:11:38.591: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(BiglyBT:15840): Gtk-CRITICAL **: 01:11:38.649: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(BiglyBT:15840): Gtk-CRITICAL **: 01:11:38.651: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(BiglyBT:15840): Gtk-WARNING **: 01:11:39.040: Negative content width -2 (allocation 0, extents 1x1) while allocating gadget (node progress, owner GtkProgressBar)
core.stop
CRIT  [enDispatcher] net.i2p.router.Router         : Shutdown imminent
CRIT  [enDispatcher] net.i2p.router.Router         : Shutdown(3) complete
DEBUG::Tue Aug 01 01:12:47 EEST 2023::org.parg.azureus.plugins.networks.i2p.router.I2PSMHolder::<init>::96:
  Failed to create socket manager
    I2PHelperRouterDHT$1::<init>::218, I2PHelperRouterDHT::initialiseDHT::218, I2PHelperRouter::initialiseDHT::916, I2PHelperRouter::selectDHT::1045, I2PHelperDHTPluginInterface$2$1::run::157, AEThread2$threadWrapper::run::334
net.i2p.client.I2PSessionException: [BiglyBT: DHT Pure+(CLOSED)]: Failed to build tunnels - Disconnected from router while waiting for tunnels: Router shutdown
	at net.i2p.client.impl.I2PSessionImpl.connect(I2PSessionImpl.java:840)
	at org.parg.azureus.plugins.networks.i2p.router.I2PHelperRouterDHT$1.createSocketManager(I2PHelperRouterDHT.java:250)
	at org.parg.azureus.plugins.networks.i2p.router.I2PSMHolder.<init>(I2PSMHolder.java:96)
	at org.parg.azureus.plugins.networks.i2p.router.I2PHelperRouterDHT$1.<init>(I2PHelperRouterDHT.java:218)
	at org.parg.azureus.plugins.networks.i2p.router.I2PHelperRouterDHT.initialiseDHT(I2PHelperRouterDHT.java:218)
	at org.parg.azureus.plugins.networks.i2p.router.I2PHelperRouter.initialiseDHT(I2PHelperRouter.java:916)
	at org.parg.azureus.plugins.networks.i2p.router.I2PHelperRouter.selectDHT(I2PHelperRouter.java:1045)
	at org.parg.azureus.plugins.networks.i2p.plugindht.I2PHelperDHTPluginInterface$2$1.run(I2PHelperDHTPluginInterface.java:157)
	at com.biglybt.core.util.AEThread2$threadWrapper.run(AEThread2.java:334)
Caused by: java.io.IOException: Disconnected from router while waiting for tunnels: Router shutdown
	at net.i2p.client.impl.I2PSessionImpl.connect(I2PSessionImpl.java:796)
	... 8 more
Caused by: net.i2p.client.I2PSessionException: Disconnect Message received: Router shutdown
	at net.i2p.client.impl.DisconnectMessageHandler.handleMessage(DisconnectMessageHandler.java:33)
	at net.i2p.client.impl.I2PSessionImpl.messageReceived(I2PSessionImpl.java:1065)
	at net.i2p.internal.QueuedI2CPMessageReader$QueuedI2CPMessageReaderRunner.run2(QueuedI2CPMessageReader.java:56)
	at net.i2p.data.i2cp.I2CPMessageReader$I2CPMessageReaderRunner.run(I2CPMessageReader.java:164)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at net.i2p.util.I2PThread.run(I2PThread.java:103)
core.stop done in 3743
Exit from BiglyBT complete
java.lang.reflect.InaccessibleObjectException: Unable to make field private static transient java.net.InetAddress$NameService java.net.InetAddress.nameService accessible: module java.base does not "opens java.net" to unnamed module @6f2fd062
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at com.biglybt.core.util.spi.AENameServiceJava12.init(AENameServiceJava12.java:37)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.biglybt.core.config.COConfigurationManager.preInitialise(COConfigurationManager.java:242)
	at com.biglybt.core.config.impl.ConfigurationChecker.setSystemProperties(ConfigurationChecker.java:85)
	at com.biglybt.core.config.impl.ConfigurationManager.initialise(ConfigurationManager.java:177)
	at com.biglybt.core.config.impl.ConfigurationManager.getInstance(ConfigurationManager.java:110)
	at com.biglybt.core.config.COConfigurationManager.getStringParameter(COConfigurationManager.java:303)
	at com.biglybt.platform.unix.ScriptAfterShutdown.main(ScriptAfterShutdown.java:43)
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by com.biglybt.core.security.impl.ClientSecurityManager (file:/home/giorgos/biglybt/BiglyBT.jar)
WARNING: Please consider reporting this to the maintainers of com.biglybt.core.security.impl.ClientSecurityManager
WARNING: System::setSecurityManager will be removed in a future release
No shutdown tasks to do
BiglyBT TERMINATED.
>
```

**Comment by parg** [comment]
That's a Java version issue - see https://github.com/BiglySoftware/BiglyBT/wiki/Java-Versions

**Comment by Achaean** [comment]
Ehm...not that I fully understand the esoterics of Java, not even the (somewhat strange) versioning scheme!  :-)

Anyway! I rolled back to the earlier Java version and the problem got away!
```
>java --version
openjdk 11.0.18 2023-01-17
OpenJDK Runtime Environment (build 11.0.18+10-post-Debian-1deb11u1)
OpenJDK 64-Bit Server VM (build 11.0.18+10-post-Debian-1deb11u1, mixed mode, sharing)
>
```

**THANKS** parg!!!  ;-)

**Comment by parg** [comment]
No problem - sorry about the issues you had.

We don't maintain any linux packages so the problem is they can be quite out of date. The dorkbox issue was resolved a while back (by removing it).

We recommend Java 8 (or 1.8 as it is also known), mainly because on Windows that is the version that users go to java.com 

On linux, as you can see, the versions they recommend are much more recent (and have had things removed/deprecated/changed)

**Comment by Achaean** [comment]
I don't think that there's a real need for DEB (or any other type of) packages, since the existing installer works fine.
(I'm not sure, if dorkbox has to be excluded though, from installation).

My own background story (on this issue), was that I installed Java, manually (from repos), 
There are many versions there, and since I'm not any kind of expert, nor I have any special needs, without much thought I grubbed the most recent version.
Later on, I realized that there is a "default" package, which autoselects which version to install (and I choose it).

PS. We are not any more, at the old glorious DOS days, and you have not (at my experience), much guarantee, that  a program that runs on an interpreter (or any kind of virtual environment), will run flawlessly across different OSes or different versions of the same OS. It may run, or probably it may need at "hack", a "retouch", or something, in order to work. Nothing unusual!

**MANY THANKS** for all your hard work!!!
**REALLY appreciated!!!**
Giorgos.

**Comment by Achaean** [comment]
Just a random, but useful finding:

Adoptium Java still supports a v.11 LTS version, for yet one year
One can go to  https://adoptium.net/temurin/releases/?os=linux&arch=x64&package=jre&version=11
and download it.
(As one can see from this link, I choose Linux, x64, JRE and Java 11 LTS). 

With this version, Bigly runs flawlesslly (NO DNS manager problem).  

Availability until : At least Oct 2024
Related page: https://adoptium.net/support/
