### ISSUE TITLE
have to restart Mac every time

### ISSUE THREAD

**Issue by exekutive** [BiglySoftware/BiglyBT#3030]
BiglyBT 3.4.0.0
M2 Macbook Pro
MacOS Venture 13.5

I get to launch BiglyBT only _once_. If I quit, it will not open again. The icon just bounces for a minute.
If I restart, it launches fine again. Super annoying. Reinstalling does not help.

**Comment by parg** [comment]
Are you quitting via the File->Exit menu?

**Comment by exekutive** [comment]
I usually use ⌘-Q to quit apps

**Comment by parg** [comment]
ok, same thing :) Once you've quit it is there any sign of it still running in the Activity Monitor? I don't have this problem on my old Intel Mac but don't have a way to test on anything else.

**Comment by exekutive** [comment]
I don't see BiglyBT in Activity Monitor

**Comment by parg** [comment]
When BiglyBT is running go to Preferences->Plugins and look at the top where the user-specific plugin install folder is

For me it is /Users/paul/Library/Application Support/BiglyBT/plugins

Go to the parent folder of that ( /Users/paul/Library/Application Support/BiglyBT) and select the "logs" folder. 

There are various log files in there, for example Debug_1.log and Debug_2.log.

Close BiglyBT and then attempt to re-open it, let it bounce in the dock until it stops and then check those Debug files to see if there are any log messages from the time you attempts to re-open BiglyBT.

**Comment by exekutive** [comment]
nothing

**Comment by exekutive** [comment]
there is a lot of this in the console though

<img width="1524" alt="Screenshot 2023-08-21 at 02 14 45" src="https://github.com/BiglySoftware/BiglyBT/assets/4755215/4a748679-207d-4561-aacc-3183618f7275">
<img width="1524" alt="Screenshot 2023-08-21 at 02 14 39" src="https://github.com/BiglySoftware/BiglyBT/assets/4755215/2071568f-6d67-42b7-8ad9-d6dedb4a45e4">

**Comment by exekutive** [comment]
More from Console

```
default	02:17:53.925652-0700	runningboardd	Launch request for app<application.com.biglybt.43656735.43656739(501)> is using uid 501 (divined from auid 501 euid 501)
default	02:17:53.925832-0700	runningboardd	Acquiring assertion targeting app<application.com.biglybt.43656735.43656739(501)> from originator [osservice<com.apple.Dock.agent(501)>:495] with description <RBSAssertionDescriptor| "LS launch com.biglybt" ID:166-495-349792 target:app<application.com.biglybt.43656735.43656739(501)> attributes:[
	<RBSDomainAttribute| domain:"com.apple.launchservicesd" name:"LaunchRoleUserInteractive" sourceEnvironment:"(null)">
	]>
default	02:17:53.926001-0700	runningboardd	Assertion 166-495-349792 (target:app<application.com.biglybt.43656735.43656739(501)>) will be created as active
default	02:17:53.926045-0700	runningboardd	setting abstract target for <private> to <private>
default	02:17:53.926637-0700	runningboardd	[app<application.com.biglybt.43656735.43656739(501)>:1293] Ignoring jetsam update because this process is not memory-managed
default	02:17:53.926655-0700	runningboardd	Calculated state for app<application.com.biglybt.43656735.43656739(501)>: running-active (role: UserInteractive)
default	02:17:53.926667-0700	runningboardd	[app<application.com.biglybt.43656735.43656739(501)>:1293] Ignoring suspend because this process is not lifecycle managed
default	02:17:53.926702-0700	runningboardd	[app<application.com.biglybt.43656735.43656739(501)>:1293] Ignoring GPU update because this process is not GPU managed
default	02:17:53.926947-0700	runningboardd	[app<application.com.biglybt.43656735.43656739(501)>:1293] Ignoring memory limit update because this process is not memory-managed
default	02:17:53.927275-0700	runningboardd	Executing launch request for app<application.com.biglybt.43656735.43656739(501)> (LS launch com.biglybt)
default	02:17:53.927305-0700	runningboardd	Checking PreventLaunch: global:0 exPath:/Applications/BiglyBT/BiglyBT.app/Contents/MacOS/JavaApplicationStub predicates:(null) allow:(null)
default	02:17:53.930826-0700	WindowServer	Dispatching digitizer event with 2 children, _eventMask=0x42 _childEventMask=0x42 Cancel=0 Touching=0 inRange=1
default	02:17:53.931358-0700	runningboardd	Acquiring assertion targeting [app<application.com.biglybt.43656735.43656739(501)>:1293] from originator [osservice<com.apple.coreservices.launchservicesd>:129] with description <RBSAssertionDescriptor| "foregroundApp:1293" ID:166-129-349793 target:1293 attributes:[
	<RBSDomainAttribute| domain:"com.apple.launchservicesd" name:"RoleUserInteractiveNonFocal" sourceEnvironment:"(null)">
	]>
default	02:17:53.931461-0700	runningboardd	Assertion 166-129-349793 (target:[app<application.com.biglybt.43656735.43656739(501)>:1293]) will be created as active
default	02:17:53.931889-0700	CommCenter	#I handleLSNotitifcation_sync: Application launched: <private>
error	02:17:53.931987-0700	appleeventsd	Attempted to hint an app for which we already have an app, with the same pid, but with a different ASN. pid=1293 asn=0x0-0x4b9ab96 vs 0x0-0x4d35d31
default	02:17:53.932264-0700	runningboardd	Calculated state for app<application.com.biglybt.43656735.43656739(501)>: running-active (role: UserInteractive)
default	02:17:53.932281-0700	runningboardd	[app<application.com.biglybt.43656735.43656739(501)>:1293] Ignoring jetsam update because this process is not memory-managed
default	02:17:53.932823-0700	loginwindow	-[PersistentAppsSupport applicationLaunched:] | enter. clearing logout in progress and last logout time
default	02:17:53.932878-0700	loginwindow	-[PersistentAppsSupport applicationReady:] | App: BiglyBT, ready, updating active tracking timer
default	02:17:53.932887-0700	runningboardd	[app<application.com.biglybt.43656735.43656739(501)>:1293] Ignoring suspend because this process is not lifecycle managed
default	02:17:53.932899-0700	loginwindow	-[PersistentAppsSupport(Internal) updateActiveTrackingTimer] | Creating timer
default	02:17:53.932940-0700	loginwindow	-[ApplicationManager checkInAppContext:eventData:] | ApplicationManager: Checked in app : BiglyBT
default	02:17:53.933095-0700	runningboardd	[app<application.com.biglybt.43656735.43656739(501)>:1293] Ignoring GPU update because this process is not GPU managed
default	02:17:53.933494-0700	runningboardd	[app<application.com.biglybt.43656735.43656739(501)>:1293] Ignoring memory limit update because this process is not memory-managed
default	02:17:53.934884-0700	Dock	LAUNCH: 0x0-0x4d35d31 com.biglybt starting stopped process.
default	02:17:53.935524-0700	runningboardd	Invalidating assertion 166-495-349792 (target:app<application.com.biglybt.43656735.43656739(501)>) from originator [osservice<com.apple.Dock.agent(501)>:495]
default	02:17:53.939368-0700	Dock	-[SFLGenericList _insertItem:atIndex:error:]_block_invoke item: 64521C8B-5DC5-4C22-A53D-41E3FA47050D at index: 0 list: com.apple.LSSharedFileList.RecentApplications
default	02:17:53.940221-0700	Dock	received: com.apple.LSSharedFileList.RecentApplications
default	02:17:53.942800-0700	mds	directQueryFetchResultsReply 36926 1795162176 35 at qos 0x15
default	02:17:53.942970-0700	mds	directQueryFetchResultsReply 1426489345 1795162176 35 at qos 0x15
default	02:17:53.943051-0700	mds	directQueryFetchResultsReply 69689 1795162176 35 at qos 0x15
default	02:17:53.944397-0700	Spotlight	[Apps query] changed items (
    "<CSSearchableItem:0x600003066c00; uid=43656735-1795162176, contentType=com.apple.application-bundle>"
)
default	02:17:54.041625-0700	runningboardd	[app<application.com.biglybt.43656735.43656739(501)>:1293] Ignoring jetsam update because this process is not memory-managed
default	02:17:54.041666-0700	runningboardd	Calculated state for app<application.com.biglybt.43656735.43656739(501)>: running-active (role: UserInteractiveNonFocal)
default	02:17:54.041718-0700	runningboardd	[app<application.com.biglybt.43656735.43656739(501)>:1293] Ignoring suspend because this process is not lifecycle managed
default	02:17:54.041788-0700	runningboardd	[app<application.com.biglybt.43656735.43656739(501)>:1293] Ignoring GPU update because this process is not GPU managed
default	02:17:54.041899-0700	runningboardd	[app<application.com.biglybt.43656735.43656739(501)>:1293] Ignoring memory limit update because this process is not memory-managed

```

**Comment by parg** [comment]
No idea what all that means, sorry :(

**Comment by plkx** [comment]
If you go to BiglyBT.app (in applications folder/BiglyBT folder) and "Show Package Contents," (right-click menu) it will open the application with a terminal window. The terminal window provides a verbose account of what's happening. Whether or not it will help, I don't know. Also, I've not had the problem you describe, but BiglyBT would essentially freeze every time it ran (transfers continued but no response from any commands except Quit, to which it replied that there were pending operations. Eventually, I found that there were "stranded" disk operations (BiglyBT top menu → View → Disk Operations. If I selected and deleted those, Bigly was immediately unfrozen. In my case, uninstalling the AzCatDest plugin resolved the issue. I'm on a Mac Studio M1 Ultra, Ventura 13.4.1, and BiglyBT beta (version at the time of the problem ~ 3.4.0.1_B15.

**Comment by exekutive** [comment]
Thanks @plkx 
Output from JavaApplicationStub:

```
/Applications/BiglyBT/BiglyBT.app/Contents/MacOS/JavaApplicationStub ; exit;
There appears to be another process already listening on socket [127.0.0.1:6880].

Locate and terminate the other program or change the control port

See the wiki for details, https://wiki.biglybt.com/w/Commandline_options#Changing_the_Control_Port
Warning: the fonts "Times" and "Lucida Bright" are not available for the Java logical font "Serif", which may have unexpected appearance or behavior. Re-enable the "Times" font to remove this warning.
```

That's it.

**Comment by exekutive** [comment]
any ideas how to fix this, or at least gather more information and troubleshoot further?

**Comment by exekutive** [comment]
is there anybody using bigly on an M2 Mac who can confirm that it DOES work normally?

**Comment by exekutive** [comment]
Please keep this issue open. It is not resolved.

**Comment by parg** [comment]
Nobody's going to look into it.

**Comment by twistedpixel** [comment]
> Nobody's going to look into it.

Why not? I found this bug report after experiencing exactly the same issue.

**Comment by parg** [comment]
feel free you look into it yourself, it is open source after all

**Comment by twistedpixel** [comment]
Managed to get it to launch by invoking the JavaApplicationStub executable. BiglyBT launches but insists that there's another instance running. I'm not sure why this works but launching from the icon results in several hundred bounces of the app in the dock and then gives up.

Anyway, on aborting the "wait for other instances to close" dialog in the BiglyBT instance launched from the JavaApplicationStub executable (since I know there are no instances running), an error appears telling me it can't set the lock file `.azlock`

I manually removed this file and the app loaded immediately, not requiring a reboot of the Mac.

`ls -lah | grep lock` now shows there are two invisible lock files: `.lock` and `.azlock`

I'm guessing one of these issues is the cause: 
• multiple lock files due to naming inconsistency
• poor implementation and reliance on lock file to determine if an instance is already running
• permissions problem (the error seemed to be suggesting it wasn't able to deal with the `.azlock` file but wasn't entirely clear)

I don't know exactly how BiglyBT uses the lock file(s) but if it simply checks for the existence of the file, perhaps it should be periodically writing to the lock file and the check should not be based purely on existence but on date modified.

If date modified > 120 seconds, assume failure, remove lock file and launch new instance.

**Comment by parg** [comment]
read https://www.reddit.com/r/BiglyBT/comments/19dldgq/biglybt_does_not_relaunch/

The only thing I can do is update you to the latest SWT to see if that magically fixes it

**Comment by parg** [comment]
Join the beta program (see the Help menu) and wait for BiglyBT to update to 3501_B26 and SWT 4964r7

**Comment by exekutive** [comment]
and please report back

**Comment by exekutive** [comment]
> Join the beta program (see the Help menu) and wait for BiglyBT to update to 3501_B26 and SWT 4964r7

I tried the Beta, but after the SWT update, BiglyBT does not launch at all.


```
/Users/joe>/Applications/BiglyBT/BiglyBT.app/Contents/MacOS/JavaApplicationStub
DEBUG::Mon Mar 18 22:14:34 PDT 2024::com.biglybt.core.config.COConfigurationManager::addAndFireParameterListener::621:
  java.lang.UnsupportedClassVersionError: org/eclipse/swt/SWT has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at com.biglybt.ui.swt.UI.canUseSystemTheme(UI.java:67)
	at com.biglybt.ui.swt.UI.lambda$0(UI.java:79)
	at com.biglybt.core.config.COConfigurationManager.addAndFireParameterListener(COConfigurationManager.java:617)
	at com.biglybt.ui.swt.UI.<clinit>(UI.java:73)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.biglybt.ui.common.UserInterfaceFactory.getUI(UserInterfaceFactory.java:33)
	at com.biglybt.ui.Main.buildUIList(Main.java:323)
	at com.biglybt.ui.Main.main(Main.java:115)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.biglybt.launcher.Launcher$1.run(Launcher.java:48)
	at com.biglybt.launcher.Launcher.launch(Launcher.java:65)
	at com.biglybt.launcher.Launcher.checkAndLaunch(Launcher.java:83)
	at com.biglybt.ui.Main.main(Main.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.install4j.runtime.launcher.MacLauncher.main(MacLauncher.java:52)

changeLocale: *Default Language* != English (United States). Searching without country..
changeLocale: Searching for language English in *any* country..
changeLocale: no message properties for Locale 'English (United States)' (en_US), using 'English (default)'
Enabling broken select detection: diablo=false, freebsd 7+=false, osx 10.6+=true
Launch failed
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.biglybt.launcher.Launcher$1.run(Launcher.java:48)
	at com.biglybt.launcher.Launcher.launch(Launcher.java:65)
	at com.biglybt.launcher.Launcher.checkAndLaunch(Launcher.java:83)
	at com.biglybt.ui.Main.main(Main.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.install4j.runtime.launcher.MacLauncher.main(MacLauncher.java:52)
Caused by: java.lang.UnsupportedClassVersionError: org/eclipse/swt/widgets/Composite has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at com.biglybt.ui.swt.Initializer.<init>(Initializer.java:180)
	at com.biglybt.ui.swt.UI.takeMainThread(UI.java:162)
	at com.biglybt.ui.Main.main(Main.java:247)
	... 14 more
java.lang.SecurityException: VM exit operation prohibited
	at com.biglybt.core.security.impl.ClientSecurityManager.checkExit(ClientSecurityManager.java:118)
	at java.lang.Runtime.exit(Runtime.java:102)
	at java.lang.System.exit(System.java:987)
	at com.biglybt.launcher.Launcher$1.run(Launcher.java:56)
	at com.biglybt.launcher.Launcher.launch(Launcher.java:65)
	at com.biglybt.launcher.Launcher.checkAndLaunch(Launcher.java:83)
	at com.biglybt.ui.Main.main(Main.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.install4j.runtime.launcher.MacLauncher.main(MacLauncher.java:52)
2024-03-18 22:14:34.860 JavaApplicationStub[8526:116953] *** Assertion failure in -[NSMenu itemAtIndex:], NSMenu.m:1464
java.lang.SecurityException: VM exit operation prohibited
	at com.biglybt.core.security.impl.ClientSecurityManager.checkExit(ClientSecurityManager.java:118)
	at java.lang.Runtime.exit(Runtime.java:102)
	at java.lang.System.exit(System.java:987)
	at com.exe4j.runtime.LauncherEngine.handleFailure(LauncherEngine.java:163)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:87)
	at com.install4j.runtime.launcher.MacLauncher.main(MacLauncher.java:52)
error2: java.lang.SecurityException: VM exit operation prohibited
com.biglybt.core.security.impl.ClientSecurityManager.checkExit(ClientSecurityManager.java:118)
java.lang.Runtime.exit(Runtime.java:102)
java.lang.System.exit(System.java:987)
com.exe4j.runtime.LauncherEngine.handleFailure(LauncherEngine.java:163)
com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:93)
com.install4j.runtime.launcher.MacLauncher.main(MacLauncher.java:52)

Exception in thread "BiglyBT" java.lang.SecurityException: VM exit operation prohibited
	at com.biglybt.core.security.impl.ClientSecurityManager.checkExit(ClientSecurityManager.java:118)
	at java.lang.Runtime.exit(Runtime.java:102)
	at java.lang.System.exit(System.java:987)
	at com.install4j.runtime.launcher.MacLauncher.main(MacLauncher.java:59)

```

**Comment by parg** [comment]
Ah, that's unfortunate - that SWT is only for Java 11+, you appear to be running Java 8. That SWT update shouldn't have been allowed, I'll fix that.

**Comment by exekutive** [comment]
> feel free you look into it yourself, it is open source after all

I thought the reason for using source control like Github was to be able to identify and track issues, so people can submit PR's to fix them. Even though you or I are unable to, maybe somebody with a Mac and the skills will be interested. By closing everything, doesn't that kind of defeat the purpose of being open source?

**Comment by parg** [comment]
I've been here for many years, nobody goes around perusing repositories looking for problems they can fix. The only people that (very rarely) contribute are those that are directly affected by an issue and put in the effort to solve it, and they can do that becuase the source code is available for them to work with.

**Comment by exekutive** [comment]
That's true. Maybe I'm overestimating the userbase.
