### ISSUE TITLE
Don't open popup windows if batch moving a LOT of torrents

### ISSUE THREAD

**Issue by exuvo** [BiglySoftware/BiglyBT#3065]
When batch moving 2749 torrents it bugs out on what i think is creating popup windows for each ones progress. Maybe don't do that if more than 20 torrents as they are already visible in the disk tab. Smaller batches of 100 work fine.

A few thousand of each of these in my log after an attempted batch move:
```
DEBUG::Sun Oct 01 15:35:44 CEST 2023::com.biglybt.core.util.LinkFileMap::get::65:
  unexpected index
    DownloadManagerStateImpl::setFileLinks::2398, DownloadManagerImpl::updateFileLinks::1959, DownloadManagerImpl::setTorrentSaveDir::3485, DownloadManagerImpl::moveDataFilesSupport0::5640, DownloadManagerImpl::lambda$0::5375, DiskMana
gerUtil$6::run::2429, ProgressWindow$4::run::392, AEThread2$threadWrapper::run::334
```
```
DEBUG::Sun Oct 01 15:39:54 CEST 2023::com.biglybt.core.util.DebugLight::printStackTrace::35:
  org.eclipse.swt.SWTException: Widget is disposed
        at org.eclipse.swt.SWT.error(SWT.java:4889)
        at org.eclipse.swt.SWT.error(SWT.java:4804)
        at org.eclipse.swt.SWT.error(SWT.java:4775)
        at org.eclipse.swt.widgets.Widget.error(Widget.java:555)
        at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:470)
        at org.eclipse.swt.widgets.Widget.getData(Widget.java:609)
        at com.biglybt.ui.swt.components.shell.ShellFactory$AEShell.open(ShellFactory.java:300)
        at com.biglybt.ui.swt.components.shell.ShellFactory$AEShell$1$1.runSupport(ShellFactory.java:322)
        at com.biglybt.core.util.AERunnable.run(AERunnable.java:36)
        at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
        at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
        at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:5067)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4573)
        at com.biglybt.ui.swt.mainwindow.SWTThread.<init>(SWTThread.java:526)
        at com.biglybt.ui.swt.mainwindow.SWTThread.createInstance(SWTThread.java:58)
        at com.biglybt.ui.swt.Initializer.<init>(Initializer.java:183)
        at com.biglybt.ui.swt.UI.takeMainThread(UI.java:162)
        at com.biglybt.ui.Main.main(Main.java:247)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.biglybt.launcher.Launcher$1.run(Launcher.java:48)
        at java.lang.Thread.run(Thread.java:750)
```
stdout log https://exuvo.se/f/bigly-logs-stdout.tar.gz
logdir https://exuvo.se/f/bigly-logs.tar.gz

Related https://github.com/BiglySoftware/BiglyBT/issues/3064

* OS and version
Arch linux 6.1.50-1-lts
* BiglyBT Version Number
 3.4.0
 Java 1.8
* For *nix: Desktop Environment
Plain Openbox / None

**Comment by parg** [comment]
There is "Options->Interface->Display [Various]: Suppress File Move progress popup dialog", that might help.

I'll take a look at your suggesting when I get a chance, thanks.
