### ISSUE TITLE
BiglyBT trying to use IPv6 even when disabled in Options->Connection->Advanced Network Settings: Enable IPv6 support

### ISSUE THREAD

**Issue by 2peer** [BiglySoftware/BiglyBT#3221]
It looks like BiglyBT is trying to use IPv6 (at least in some parts) even if disabled in:
Options->Connection->Advanced Network Settings: Enable IPv6 support

I noticed the following attempts to contact some trackers over IPv6 in the stderr+stdout redirect/log:
```
[net] PRUDPPacketHandler: sendAndReceive to <REDACTED IPv6 tracker address> failed: Network unavailable
```
This one is probably mostly fine (it only makes the log pretty spamy), but from time to time it also results in an exception like the following:
```
[nwman] ConnectDisconnectManager::address exception: full=/[<redacted_ipv6_addr>]:<redacted_port>, hostname=<redacted_ipv6_addr>, port=<redacted_port>, unresolved=false, ......
DEBUG::<date>::com.biglybt.core.networkmanager.impl.tcp.TCPConnectionManager::addNewRequest::623:
  java.net.SocketException: Network unavailable
        at java.base/sun.nio.ch.Net.connect0(Native Method)
        at java.base/sun.nio.ch.Net.connect(Net.java:579)
        at java.base/sun.nio.ch.Net.connect(Net.java:586)
        at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:853)
        at com.biglybt.core.networkmanager.impl.tcp.TCPConnectionManager.addNewRequest(TCPConnectionManager.java:501)
        at com.biglybt.core.networkmanager.impl.tcp.TCPConnectionManager.addNewOutboundRequests(TCPConnectionManager.java:339)
        at com.biglybt.core.networkmanager.impl.tcp.TCPConnectionManager$7.run(TCPConnectionManager.java:298)
        at com.biglybt.core.util.AEThread2$threadWrapper.run(AEThread2.java:334)
```
which might be a little bit more serious? Not sure.

System:

* OS and version: Fedora release 38 (Thirty Eight)
* BiglyBT Version Number: 3.5.0.0
* For *nix: Desktop Environment: KDE Plasma

**Comment by parg** [comment]
It isn't a security feature, it just disables some things. Just ignore the errors. Thanks

**Comment by 2peer** [comment]
Wasn't thinking security, but more like efficiency/optimization (power/CPU cycles).

Would be nice if  the first message was suppressed. I like to keep a log for when something goes wrong and it grows it by about 10-20MB/day. Will filter it out in the startup script for now.

**Comment by parg** [comment]
Try beta B46 (see the Help menu to join the Beta Program) - the first message shouldn't occur.
