### ISSUE TITLE
BiglyBT still prefers IPv6 tracker addresses when both "Enable IPv6 support" & "Prefer IPv6 addresses when both IPv6 and IPv4 are available" are turned off

### ISSUE THREAD

**Issue by 2peer** [BiglySoftware/BiglyBT#3311]
Options->Connection->Advanced Network Settings: Enable IPv6 support - set to OFF
Options->Connection->Advanced Network Settings: Prefer IPv6 addresses when both IPv6 and IPv4 are available - greyed out, but set to OFF too

Yet for example for torrent.fedoraproject.org, I get nslookup:
```
Name:	torrent01.fedoraproject.org
Address: 152.19.134.141
Name:	torrent01.fedoraproject.org
Address: 2600:2701:4000:5211:dead:beef:fe:fed5
```

and the following in the log:
```
net] PRUDPPacketHandler: sendAndReceive to torrent.fedoraproject.org/[2600:2701:4000:5211:dead:beef:fe:fed5]:6969 failed: Network unavailable
```
and a similar message in the "Tracker Status"

**System/version info:**
* OS and version : Linux - Fedora 40
* BiglyBT Version Number: 3601_B22
* For *nix: Desktop Environment : KDE Plasma

**Comment by 2peer** [comment]
OK. The reported issue seem to be fixed in  3601_B24 (no longer getting those PRUDPPacketHandler messages).

It still sometimes tries to contact IPv6 peers (a different issue). While we are at it here is a stack trace (if you want to give it a go):
```
[nwman] ConnectDisconnectManager::address exception: full=/[<redacted_ipv6_peer_ip>]:6881, hostname=<redacted_ipv6_peer_ip>, port=6881, unresolved=false, full_sub=<redacted_ipv6_peer_ip>/<redacted_ipv6_peer_ip>, host_address=<redacted_ipv6_peer_ip>
 channel=java.nio.channels.SocketChannel[closed], socket=Socket[unconnected], local_address=0.0.0.0/0.0.0.0, local_port=33095, remote_address=<redacted_ipv6_peer_ip>/[<redacted_ipv6_peer_ip>]:6881, remote_port=6881
DEBUG::Tue Jun 25 18:22:10 CEST 2024::com.biglybt.core.networkmanager.impl.tcp.TCPConnectionManager::addNewRequest::623:
  java.net.SocketException: Network unavailable
        at java.base/sun.nio.ch.Net.connect0(Native Method)
        at java.base/sun.nio.ch.Net.connect(Net.java:589)
        at java.base/sun.nio.ch.Net.connect(Net.java:596)
        at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:880)
        at com.biglybt.core.networkmanager.impl.tcp.TCPConnectionManager.addNewRequest(TCPConnectionManager.java:501)
        at com.biglybt.core.networkmanager.impl.tcp.TCPConnectionManager.addNewOutboundRequests(TCPConnectionManager.java:339)
        at com.biglybt.core.networkmanager.impl.tcp.TCPConnectionManager$7.run(TCPConnectionManager.java:298)
        at com.biglybt.core.util.AEThread2$threadWrapper.run(AEThread2.java:334)
```

But otherwise I would consider this one fixed.
