### ISSUE TITLE
ClassCastException when getting statistics of Web Seed's peers via PIF

### ISSUE THREAD

**Issue by Ghost-chu** [BiglySoftware/BiglyBT#3382]
[17:12:24.819] {stderr} [JettyServerThreadPool-208] WARN com.ghostchu.peerbanhelper.downloaderplug.biglybt.JavalinWebContainer - 500 Internal Server Error
[17:12:24.820] {stderr} java.lang.ClassCastException: class com.biglybt.plugin.extseed.ExternalSeedPeer$ESConnection cannot be cast to class com.biglybt.pifimpl.local.network.ConnectionImpl (com.biglybt.plugin.extseed.ExternalSeedPeer$ESConnection and com.biglybt.pifimpl.local.network.ConnectionImpl are in unnamed module of loader 'app')
[17:12:24.821] {stderr} 	at com.biglybt.core.peer.impl.PEPeerStatsImpl.getPermittedBytesToReceive(PEPeerStatsImpl.java:272)
[17:12:24.821] {stderr} 	at com.biglybt.pifimpl.local.peers.PeerStatsImpl.getPermittedBytesToReceive(PeerStatsImpl.java:112)
[17:12:24.821] {stderr} 	at com.ghostchu.peerbanhelper.downloaderplug.biglybt.Plugin.getPeerStatsRecord(Plugin.java:573)
[17:12:24.822] {stderr} 	at com.ghostchu.peerbanhelper.downloaderplug.biglybt.Plugin.getPeerRecord(Plugin.java:552)
[17:12:24.822] {stderr} 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[17:12:24.823] {stderr} 	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
[17:12:24.823] {stderr} 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[17:12:24.824] {stderr} 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[17:12:24.824] {stderr} 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
[17:12:24.825] {stderr} 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[17:12:24.825] {stderr} 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
[17:12:24.825] {stderr} 	at com.ghostchu.peerbanhelper.downloaderplug.biglybt.Plugin.getPeerManagerRecord(Plugin.java:490)
[17:12:24.826] {stderr} 	at com.ghostchu.peerbanhelper.downloaderplug.biglybt.Plugin.handlePeers(Plugin.java:387)
[17:12:24.826] {stderr} 	at io.javalin.router.Endpoint.handle(Endpoint.kt:52)
[17:12:24.827] {stderr} 	at io.javalin.router.ParsedEndpoint.handle(ParsedEndpoint.kt:15)
[17:12:24.827] {stderr} 	at io.javalin.http.servlet.DefaultTasks.HTTP$lambda$9$lambda$7$lambda$6(DefaultTasks.kt:52)
[17:12:24.828] {stderr} 	at io.javalin.http.servlet.JavalinServlet.handleTask(JavalinServlet.kt:99)
[17:12:24.828] {stderr} 	at io.javalin.http.servlet.JavalinServlet.handleSync(JavalinServlet.kt:64)
[17:12:24.828] {stderr} 	at io.javalin.http.servlet.JavalinServlet.handle(JavalinServlet.kt:50)
[17:12:24.829] {stderr} 	at io.javalin.http.servlet.JavalinServlet.service(JavalinServlet.kt:30)
[17:12:24.829] {stderr} 	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
[17:12:24.830] {stderr} 	at io.javalin.jetty.JavalinJettyServlet.service(JavalinJettyServlet.kt:52)
[17:12:24.830] {stderr} 	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
[17:12:24.831] {stderr} 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
[17:12:24.831] {stderr} 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:529)
[17:12:24.832] {stderr} 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
[17:12:24.832] {stderr} 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1580)
[17:12:24.833] {stderr} 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
[17:12:24.833] {stderr} 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1381)
[17:12:24.833] {stderr} 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
[17:12:24.833] {stderr} 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
[17:12:24.835] {stderr} 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1553)
[17:12:24.835] {stderr} 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
[17:12:24.835] {stderr} 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1303)
[17:12:24.836] {stderr} 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
[17:12:24.836] {stderr} 	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
[17:12:24.837] {stderr} 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
[17:12:24.837] {stderr} 	at org.eclipse.jetty.server.Server.handle(Server.java:563)
[17:12:24.837] {stderr} 	at org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598)
[17:12:24.838] {stderr} 	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753)
[17:12:24.838] {stderr} 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501)
[17:12:24.839] {stderr} 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:287)
[17:12:24.839] {stderr} 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
[17:12:24.839] {stderr} 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
[17:12:24.840] {stderr} 	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
[17:12:24.840] {stderr} 	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421)
[17:12:24.841] {stderr} 	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390)
[17:12:24.841] {stderr} 	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277)
[17:12:24.841] {stderr} 	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:199)
[17:12:24.842] {stderr} 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
[17:12:24.842] {stderr} 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
[17:12:24.842] {stderr} 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
[17:12:24.843] {stderr} 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
[17:12:24.843] {stderr} 	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by parg** [comment]
Fixed next beta
