### ISSUE TITLE
java.lang.NullPointerException: Cannot read the array length because "core_msgs" is null

### ISSUE THREAD

**Issue by Ghost-chu** [BiglySoftware/BiglyBT#3407]
* Windows 11 24H2
* BiglyBT 3.7.0.0
```
Java 23 (64 bit)
  Eclipse Adoptium
c:\program files\eclipse adoptium\jdk-23.0.0.37-hotspot

SWT v4964r8, win32, zoom=100, dpi=144
Windows 11 v10.0, amd64 (64 bit)
B3.7.0.0/4 az3 zh_CN
```

```
[01:25:36.175] {stderr} java.lang.NullPointerException: Cannot read the array length because "core_msgs" is null
[01:25:36.175] {stderr} 	at com.biglybt.pifimpl.local.peers.PeerImpl.getSupportedMessages(PeerImpl.java:112)
[01:25:36.176] {stderr} 	at com.ghostchu.peerbanhelper.downloaderplug.biglybt.Plugin.getPeerRecord(Plugin.java:540)
[01:25:36.176] {stderr} 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:215)
[01:25:36.176] {stderr} 	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
[01:25:36.177] {stderr} 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:570)
[01:25:36.177] {stderr} 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560)
[01:25:36.177] {stderr} 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
[01:25:36.178] {stderr} 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
[01:25:36.178] {stderr} 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:727)
[01:25:36.178] {stderr} 	at com.ghostchu.peerbanhelper.downloaderplug.biglybt.Plugin.getPeerManagerRecord(Plugin.java:470)
[01:25:36.179] {stderr} 	at com.ghostchu.peerbanhelper.downloaderplug.biglybt.Plugin.handlePeers(Plugin.java:367)
[01:25:36.179] {stderr} 	at io.javalin.router.Endpoint.handle(Endpoint.kt:52)
[01:25:36.179] {stderr} 	at io.javalin.router.ParsedEndpoint.handle(ParsedEndpoint.kt:15)
[01:25:36.179] {stderr} 	at io.javalin.http.servlet.DefaultTasks.HTTP$lambda$9$lambda$7$lambda$6(DefaultTasks.kt:52)
[01:25:36.181] {stderr} 	at io.javalin.http.servlet.JavalinServlet.handleTask(JavalinServlet.kt:99)
[01:25:36.181] {stderr} 	at io.javalin.http.servlet.JavalinServlet.handleSync(JavalinServlet.kt:64)
[01:25:36.181] {stderr} 	at io.javalin.http.servlet.JavalinServlet.handle(JavalinServlet.kt:50)
[01:25:36.181] {stderr} 	at io.javalin.http.servlet.JavalinServlet.service(JavalinServlet.kt:30)
[01:25:36.181] {stderr} 	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
[01:25:36.182] {stderr} 	at io.javalin.jetty.JavalinJettyServlet.service(JavalinJettyServlet.kt:52)
[01:25:36.182] {stderr} 	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
[01:25:36.182] {stderr} 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
[01:25:36.182] {stderr} 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:529)
[01:25:36.183] {stderr} 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
[01:25:36.183] {stderr} 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1580)
[01:25:36.183] {stderr} 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
[01:25:36.184] {stderr} 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1381)
[01:25:36.184] {stderr} 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
[01:25:36.184] {stderr} 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
[01:25:36.184] {stderr} 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1553)
[01:25:36.185] {stderr} 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
[01:25:36.185] {stderr} 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1303)
[01:25:36.185] {stderr} 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
[01:25:36.185] {stderr} 	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
[01:25:36.185] {stderr} 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
[01:25:36.187] {stderr} 	at org.eclipse.jetty.server.Server.handle(Server.java:563)
[01:25:36.187] {stderr} 	at org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598)
[01:25:36.187] {stderr} 	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753)
[01:25:36.188] {stderr} 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501)
[01:25:36.188] {stderr} 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:287)
[01:25:36.188] {stderr} 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
[01:25:36.188] {stderr} 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
[01:25:36.189] {stderr} 	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
[01:25:36.189] {stderr} 	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421)
[01:25:36.189] {stderr} 	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390)
[01:25:36.189] {stderr} 	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277)
[01:25:36.190] {stderr} 	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:199)
[01:25:36.190] {stderr} 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
[01:25:36.190] {stderr} 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
[01:25:36.191] {stderr} 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
[01:25:36.191] {stderr} 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
[01:25:36.191] {stderr} 	at java.base/java.lang.Thread.run(Thread.java:1575)
```

**Comment by parg** [comment]
Don't know the context...

Assuming the remote peer is a BiglyBT peer then you should probably use

```
if ( peer.supportsMessaging()){
   ...
   peer.getSupportedMessages();
}
```

**Comment by parg** [comment]
Or the peer isn't fully connected yet, wait until

```
if ( peer.getState() == PEPeer.TRANSFERING ){
...
}
```
