### ISSUE TITLE
com.biglybt.core.diskmanager.file.FMFileManagerException: read failed: accessor is null

### ISSUE THREAD

**Issue by Ghost-chu** [BiglySoftware/BiglyBT#3419]
* Windows 11 24H2
* 3.7.0.0

```
Java 23 (64 bit)
  Eclipse Adoptium
c:\program files\eclipse adoptium\jdk-23.0.0.37-hotspot

SWT v4964r8, win32, zoom=100, dpi=144
Windows 11 v10.0, amd64 (64 bit)
B3.7.0.0/4 az3 zh_CN
```

Error while downloading a torrent: 

```
[18:49:05] [stderr] 
[18:49:05] DEBUG::Thu Nov 14 18:49:05 CST 2024  Recovered connection to E:\Download\[FILE_NAME_HERE]
[18:49:05] [stderr] DEBUG::Thu Nov 14 18:49:05 CST 2024::com.biglybt.core.diskmanager.file.impl.FMFileImpl::readSupport::826:
[18:49:05] [stderr]   com.biglybt.core.diskmanager.file.FMFileManagerException: read failed: accessor is null
	at com.biglybt.core.diskmanager.file.impl.FMFileAccessLinear.read(FMFileAccessLinear.java:239)
	at com.biglybt.core.diskmanager.file.impl.FMFileAccessController.read(FMFileAccessController.java:509)
	at com.biglybt.core.diskmanager.file.impl.FMFileImpl.readSupport(FMFileImpl.java:822)
	at com.biglybt.core.diskmanager.file.impl.FMFileImpl.readSupport(FMFileImpl.java:810)
	at com.biglybt.core.diskmanager.file.impl.FMFileLimited.read(FMFileLimited.java:291)
	at com.biglybt.core.diskmanager.cache.impl.CacheFileWithCache.readCache(CacheFileWithCache.java:562)
	at com.biglybt.core.diskmanager.cache.impl.CacheFileWithCache.read(CacheFileWithCache.java:1804)
	at com.biglybt.core.diskmanager.access.impl.DiskAccessRequestImpl.runRequest(DiskAccessRequestImpl.java:102)
	at com.biglybt.core.diskmanager.access.impl.DiskAccessControllerInstance$requestDispatcher$1.run(DiskAccessControllerInstance.java:694)
	at com.biglybt.core.util.AEThread2$threadWrapper.run(AEThread2.j
ava:334)
```

[logs.zip](https://github.com/user-attachments/files/17747463/logs.zip)

This error occurs during a torrent download when a significant portion of the content has already been downloaded.

At the time of the error, all peers were disconnected from BiglyBT.

**Comment by parg** [comment]
Did your download continue to run successfully or go into an error state? The logging implies that the file connection was recovered.

**Comment by Ghost-chu** [comment]
I tried to continue the task after the it go into error state, and it returned to normal.

**Comment by parg** [comment]
dunno, closing
