### ISSUE TITLE
[config request] Limit Too many trackers - 1025

### ISSUE THREAD

**Issue by JBitte** [BiglySoftware/BiglyBT#3432]
I've been struggling with "Too many trackers - 1025" errors for a couple years.
When I search in Tools -> 1024, there are no relevant hits.
I'm thinking there is a hardcoded 1024 somewhere.
Would configuring above 1024 help me?
Is there a decent article on reducing the amount of trackers?
I frequently go into Sources tab, select, and hit the delete button on erroneous line items, but organically they re-appear

![bt-too-many-trackers1025](https://github.com/user-attachments/assets/b566cd4e-9cfc-4270-9388-2aae9eab454d)

* OS and version Win11 24H2
* BiglyBT Version Number BiglyBT3701-B23-signed.jar
* For Java Environment  jre1.8.0_431

some more logging below, from a prior beta jar:
DEBUG::Sun Nov 24 10:13:06 CET 2024::com.biglybt.core.tracker.alltrackers.AllTrackersManagerImpl::saveConfig::624:
  Too many trackers - 1025
    access$13 (AllTrackersManagerImpl.java:569), perform (AllTrackersManagerImpl.java:235), perform (TimerEventPeriodic.java:104), runSupport (TimerEvent.java:135), runSupport (TimerEvent.java:252), AERunnable.run, ThreadPool.runIt
DEBUG::Sun Nov 24 10:13:25 CET 2024::org.parg.azureus.plugins.networks.i2p.router.I2PSMHolder::<init>::96:
  Failed to create socket manager
    <init> (I2PHelperRouterDHT.java:218), initialiseDHT (I2PHelperRouterDHT.java:218), initialiseDHT (I2PHelperRouter.java:916), initialiseDHTs (I2PHelperRouter.java:894), run (I2PHelperPlugin.java:1720), run (AEThread2.java:336)
net.i2p.client.I2PSessionException: [BiglyBT: DHT Mixed #22059(GOTDATE)]: Failed to build tunnels - No tunnels built after waiting 5 minutes. Your network connection may be down, or there is severe network congestion.
        at net.i2p.client.impl.I2PSessionImpl.connect(I2PSessionImpl.java:850)
        at org.parg.azureus.plugins.networks.i2p.router.I2PHelperRouterDHT$1.createSocketManager(I2PHelperRouterDHT.java:260)
        at org.parg.azureus.plugins.networks.i2p.router.I2PSMHolder.<init>(I2PSMHolder.java:96)
        at org.parg.azureus.plugins.networks.i2p.router.I2PHelperRouterDHT$1.<init>(I2PHelperRouterDHT.java:218)
        at org.parg.azureus.plugins.networks.i2p.router.I2PHelperRouterDHT.initialiseDHT(I2PHelperRouterDHT.java:218)
        at org.parg.azureus.plugins.networks.i2p.router.I2PHelperRouter.initialiseDHT(I2PHelperRouter.java:916)
        at org.parg.azureus.plugins.networks.i2p.router.I2PHelperRouter.initialiseDHTs(I2PHelperRouter.java:894)
        at org.parg.azureus.plugins.networks.i2p.I2PHelperPlugin$15.run(I2PHelperPlugin.java:1720)
        at com.biglybt.core.util.AEThread2$threadWrapper.run(AEThread2.java:336)
Caused by: java.io.IOException: No tunnels built after waiting 5 minutes. Your network connection may be down, or there is severe network congestion.
        at net.i2p.client.impl.I2PSessionImpl.connect(I2PSessionImpl.java:794)
        ... 8 more

**Comment by parg** [comment]
As you surmise it is a hardcoded limit, I'll increase it a bit. Obviously when I wrote the code I thought nobody would ever have that many!

As for reducing the number, you could try disabling "Options->Tracker->Client [Protocol]: Enable handling of DNS tracker records used to ameliorate accidental DDOS" although it is hard to know if this would cause issues.
