### ISSUE TITLE
getting "Memory is running low" after updated from 3.6.0.0 to 3.7.0.0

### ISSUE THREAD

**Issue by SUCM** [BiglySoftware/BiglyBT#3435]
I let BiglyBT restarted after itself update and got below notification some hours later. I haven't add/remove any torrent since the update. it's just running the same torrents like 3.6.0.0 (ran without problem continuously for few weeks). Process util says BiglyBT Virtual Size = 7.42GB and Private Bytes = 1.46GB at the moment. not sure what to look for. is there any default log to look for?

link in the msg goes to a broken page saying "BiglyBT does not have a wiki page for this topic yet"

> Memory is running low, you have 2 MiB remaining out of 1 GiB.
> Performance will be degraded and ultimately BiglyBT will stop working
> See <a href="https://wiki.biglybt.com/w/Java_VM_memory_usage">the Wiki</a> for details on how to increase the available memory.

```
Java 23.0.1 (64 bit)
  Oracle Corporation
c:\program files\java\jdk-23

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B3.7.0.0/4 az3 en_US_classic
```

**Comment by parg** [comment]
Check out https://github.com/BiglySoftware/BiglyBT/wiki/Performance-Tweaks

**Comment by SUCM** [comment]
this only happened once and BiglyBT eventually crashed silently on its own. subsequent launch of 3.7.0.0 hasn't thrown that msg after more than 24 hours

I searched through the giant logs but only found 1 instance of error msg related to memory (see below) almost at the end of debug_2.log which means it's quite recent
```
[stderr] 
[stderr] DEBUG::Sat Dec 14 06:47:35 CST 2024::com.biglybt.core.util.jman.AEMemoryMonitor$1::handleNotification::144:
[stderr]   MemMon: notify triggered: pool=G1 Old Gen, used=1071775304, max=1073741824: runtime free=1554352, tot=1073741824, max=1073741824
[stderr]     NotificationEmitterSupport::sendNotification::155, MemoryImpl::createNotification::162, MemoryPoolImpl$CollectionSensor::triggerAction::325, Sensor::trigger::134
```
below error msg has the same timestamp and was immediately above the memory error msg. not sure if it's related
```
 [stderr]   java.lang.NullPointerException: Cannot invoke "org.eclipse.swt.widgets.Control.isDisposed()" because "c" is null
	at com.biglybt.ui.swt.config.BaseSwtParameter.lambda$4(BaseSwtParameter.java:295)
	at com.biglybt.ui.swt.Utils.execSWTThread(Utils.java:1993)
	at com.biglybt.ui.swt.Utils.execSWTThread(Utils.java:2159)
	at com.biglybt.ui.swt.config.BaseSwtParameter.setEnabled(BaseSwtParameter.java:292)
	at com.biglybt.ui.swt.views.ConfigView.buildScreen(ConfigView.java:1883)
	at com.biglybt.ui.swt.views.ConfigView.ensureSectionBuilt(ConfigView.java:1103)
	at com.biglybt.ui.swt.views.ConfigView.filterTree(ConfigView.java:690)
	at com.biglybt.ui.swt.views.ConfigView.filterTree(ConfigView.java:706)
	at com.biglybt.ui.swt.views.ConfigView.lambda$14(ConfigView.java:666)
	at com.biglybt.ui.swt.Utils$17.runSupport(Utils.java:2139)
	at com.biglybt.core.util.AERunnable.run(AERunnable.java:42)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4001)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3629)
	at com.biglybt.ui.swt.mainwindow.SWTThread.<init>(SWTThread.java:526)
	at com.biglybt.ui.swt.mainwindow.SWTThread.createInstance(SWTThread.java:58)
	at com.biglybt.ui.swt.Initializer.<init>(Initializer.java:183)
	at com.biglybt.ui.swt.UI.takeMainThread(UI.java:162)
	at com.biglybt.ui.Main.main(Main.java:247)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.biglybt.launcher.Launcher$1.run(Launcher.java:48)
	at java.base/java.lang.Thread.run(Thread.java:1575)
```

**Comment by parg** [comment]
That error is unrelated to any memory issues.

Try running the latest betas.

Keep your eye on View->Log Views->JVM Info as it has details on memory usage. With the beta versions you have a Debug menu in BIglyBT that has a "Run GC" option to force garbage collection. This will cause the JVM to release all unused memory - normally if you give the JVM a lot of memory it will be lazy about releasing it and seem to be using a lot more than it actually needs.

**Comment by SUCM** [comment]
issue hasn't came back for more than 2 days. looking at JVM log, it seems to be cycling a lot with large delta when all torrents in Library are idling in seeding or downloading state without any active peer transfer

```
cpu: PRUDPPacketReciever:{PORT}:/0:0:0:0:0:0:0:0=0%, mem: max=1.00 GiB, alloc=1.00 GiB, free=403.73 MiB
cpu: Global Status Checker=10%, mem: max=1.00 GiB, alloc=1.00 GiB, free=384.94 MiB
cpu: SWT Thread=0%, mem: max=1.00 GiB, alloc=1.00 GiB, free=338.11 MiB
cpu: PRUDPPacketReciever:{PORT}:/0:0:0:0:0:0:0:0=1%, mem: max=1.00 GiB, alloc=1.00 GiB, free=268.13 MiB
cpu: SWT Thread=1%, mem: max=1.00 GiB, alloc=1.00 GiB, free=216.87 MiB
cpu: SWT Thread=1%, mem: max=1.00 GiB, alloc=1.00 GiB, free=184.93 MiB
cpu: SWT Thread=1%, mem: max=1.00 GiB, alloc=1.00 GiB, free=133.01 MiB
cpu: SWT Thread=0%, mem: max=1.00 GiB, alloc=1.00 GiB, free=64.35 MiB
cpu: SWT Thread=0%, mem: max=1.00 GiB, alloc=1.00 GiB, free=502.95 MiB
cpu: SWT Thread=1%, mem: max=1.00 GiB, alloc=1.00 GiB, free=449.71 MiB
cpu: SWT Thread=1%, mem: max=1.00 GiB, alloc=1.00 GiB, free=382.81 MiB
cpu: SWT Thread=1%, mem: max=1.00 GiB, alloc=1.00 GiB, free=326.80 MiB
cpu: EDH Precalc=1%, mem: max=1.00 GiB, alloc=1.00 GiB, free=264.35 MiB
cpu: mldht plugin=0%, mem: max=1.00 GiB, alloc=1.00 GiB, free=208.21 MiB
cpu: SWT Thread=0%, mem: max=1.00 GiB, alloc=1.00 GiB, free=164.84 MiB
cpu: SWT Thread=1%, mem: max=1.00 GiB, alloc=1.00 GiB, free=70.02 MiB
cpu: SWT Thread=0%, mem: max=1.00 GiB, alloc=1.00 GiB, free=481.24 MiB
cpu: SWT Thread=1%, mem: max=1.00 GiB, alloc=1.00 GiB, free=405.69 MiB
cpu: UDP Packet handler 1/1=0%, mem: max=1.00 GiB, alloc=1.00 GiB, free=341.15 MiB
cpu: SWT Thread=0%, mem: max=1.00 GiB, alloc=1.00 GiB, free=291.56 MiB
cpu: SWT Thread=0%, mem: max=1.00 GiB, alloc=1.00 GiB, free=237.46 MiB
cpu: SWT Thread=1%, mem: max=1.00 GiB, alloc=1.00 GiB, free=164.46 MiB
cpu: I2CP Internal Reader 1=1%, mem: max=1.00 GiB, alloc=1.00 GiB, free=99.65 MiB
cpu: SWT Thread=1%, mem: max=1.00 GiB, alloc=1.00 GiB, free=530.28 MiB
cpu: EDH Precalc=1%, mem: max=1.00 GiB, alloc=1.00 GiB, free=468.04 MiB
cpu: SWT Thread=1%, mem: max=1.00 GiB, alloc=1.00 GiB, free=422.57 MiB
cpu: SWT Thread=1%, mem: max=1.00 GiB, alloc=1.00 GiB, free=378.88 MiB
cpu: SWT Thread=0%, mem: max=1.00 GiB, alloc=1.00 GiB, free=328.38 MiB
cpu: SWT Thread=1%, mem: max=1.00 GiB, alloc=1.00 GiB, free=262.53 MiB
cpu: PRUDPPacketHandler:receiver: /0:0:0:0:0:0:0:0:{PORT}=1%, mem: max=1.00 GiB, alloc=1.00 GiB, free=172.37 MiB
cpu: PRUDPPacketReciever:{PORT}:/0:0:0:0:0:0:0:0=1%, mem: max=1.00 GiB, alloc=1.00 GiB, free=80.29 MiB
cpu: Global Status Checker=9%, mem: max=1.00 GiB, alloc=1.00 GiB, free=454.40 MiB
cpu: PRUDPPacketHandler:receiver: /0:0:0:0:0:0:0:0:{PORT}=1%, mem: max=1.00 GiB, alloc=1.00 GiB, free=413.75 MiB
cpu: SWT Thread=1%, mem: max=1.00 GiB, alloc=1.00 GiB, free=342.86 MiB
cpu: SWT Thread=1%, mem: max=1.00 GiB, alloc=1.00 GiB, free=286.89 MiB
cpu: SWT Thread=0%, mem: max=1.00 GiB, alloc=1.00 GiB, free=242.43 MiB
cpu: EDH Precalc=1%, mem: max=1.00 GiB, alloc=1.00 GiB, free=193.77 MiB
cpu: UDP Packet handler 1/1=0%, mem: max=1.00 GiB, alloc=1.00 GiB, free=134.23 MiB
cpu: UDP Packet handler 1/1=2%, mem: max=1.00 GiB, alloc=1.00 GiB, free=481.95 MiB
cpu: SWT Thread=1%, mem: max=1.00 GiB, alloc=1.00 GiB, free=428.60 MiB
cpu: I2CP Internal Reader 1=0%, mem: max=1.00 GiB, alloc=1.00 GiB, free=380.86 MiB
cpu: SWT Thread=1%, mem: max=1.00 GiB, alloc=1.00 GiB, free=322.04 MiB
cpu: I2CP Internal Reader 1=0%, mem: max=1.00 GiB, alloc=1.00 GiB, free=262.14 MiB
cpu: SWT Thread=1%, mem: max=1.00 GiB, alloc=1.00 GiB, free=185.97 MiB
cpu: SWT Thread=1%, mem: max=1.00 GiB, alloc=1.00 GiB, free=132.67 MiB
cpu: I2CP Internal Reader 1=1%, mem: max=1.00 GiB, alloc=1.00 GiB, free=455.79 MiB
cpu: SWT Thread=0%, mem: max=1.00 GiB, alloc=1.00 GiB, free=406.46 MiB
cpu: EDH Precalc=1%, mem: max=1.00 GiB, alloc=1.00 GiB, free=337.16 MiB
cpu: YK Precalc=2%, mem: max=1.00 GiB, alloc=1.00 GiB, free=272.67 MiB
cpu: YK Precalc=3%, mem: max=1.00 GiB, alloc=1.00 GiB, free=185.82 MiB
cpu: YK Precalc=3%, mem: max=1.00 GiB, alloc=1.00 GiB, free=127.63 MiB
cpu: YK Precalc=2%, mem: max=1.00 GiB, alloc=1.00 GiB, free=508.67 MiB
cpu: YK Precalc=3%, mem: max=1.00 GiB, alloc=1.00 GiB, free=453.07 MiB
cpu: SWT Thread=5%, mem: max=1.00 GiB, alloc=1.00 GiB, free=394.03 MiB
cpu: SWT Thread=2%, mem: max=1.00 GiB, alloc=1.00 GiB, free=316.11 MiB
cpu: SWT Thread=1%, mem: max=1.00 GiB, alloc=1.00 GiB, free=268.49 MiB
cpu: SWT Thread=1%, mem: max=1.00 GiB, alloc=1.00 GiB, free=202.11 MiB
cpu: SWT Thread=5%, mem: max=1.00 GiB, alloc=1.00 GiB, free=133.28 MiB
cpu: SWT Thread=5%, mem: max=1.00 GiB, alloc=1.00 GiB, free=466.79 MiB
```
