### ISSUE TITLE
Net / Firewall test mixed up IPv4 and IPv6 address?

### ISSUE THREAD

**Issue by SUCM** [BiglySoftware/BiglyBT#3436]
test seemed to be somewhat unreliable? the IPv4 and IPv6 got mixed up. UDP test prints looked fine, but UDP test passed, so not sure if the addr mixed up only happens when test failed

test 1
```
Testing port TCP {PORT} ... 
NAT Error - Connect attempt to {IPv4_Addr}:{PORT} (your computer) timed out after 20 seconds. This means your port is probably closed.

Testing port TCP {PORT} IPv6 ... 
NAT Error - Connect attempt to {IPv4_Addr}:{PORT} (your computer) timed out after 20 seconds. This means your port is probably closed.
```
test 2
```
Testing port TCP {PORT} ... 
OK ! ({IPv4_Addr})
Congratulations, you fixed it!
Testing port TCP {PORT} IPv6 ... 
NAT Error - Connect attempt to {IPv4_Addr}:{PORT} (your computer) timed out after 20 seconds. This means your port is probably closed.
```

```
Java 23.0.1 (64 bit)
  Oracle Corporation
c:\program files\java\jdk-23

SWT v4942r22, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B3.7.0.0/4 az3 en_US_classic
```

**Comment by parg** [comment]
Works fine and reliably for me.

Check your Debug logs when you run the test, see if there's an issue resolving the IPv6 test server address

**Comment by SUCM** [comment]
1. feature request? the test panel is resizable, but I'm not able to resize the msg/log text area and it doesn't auto resize either

2. debug log checking
- nothing written into debug_1.log from the test
- below error msg written into debug_2.log some time before the NAT test failure msg. **ping nettest.biglybt.com** in windows cmd works, so not sure why BiglyBT is unable to resolve host
`java.net.UnknownHostException: nettest.biglybt.com`
- debug_2.log also got below error immediately after the ping test failure msg, not sure if it's related
```
 [stderr] DEBUG::Sun Dec 15 18:53:37 CST 2024::com.biglybt.core.util.DebugLight::printStackTrace::35:
 [stderr]   java.lang.NullPointerException: Cannot invoke "org.eclipse.swt.widgets.Control.isDisposed()" because "c" is null
	at com.biglybt.ui.swt.config.BaseSwtParameter.lambda$4(BaseSwtParameter.java:295)
	at com.biglybt.ui.swt.Utils.execSWTThread(Utils.java:1993)
	at com.biglybt.ui.swt.Utils.execSWTThread(Utils.java:2159)
	at com.biglybt.ui.swt.config.BaseSwtParameter.setEnabled(BaseSwtParameter.java:292)
	at com.biglybt.ui.swt.views.ConfigView.buildScreen(ConfigView.java:1883)
	at com.biglybt.ui.swt.views.ConfigView.ensureSectionBuilt(ConfigView.java:1103)
	at com.biglybt.ui.swt.views.ConfigView.filterTree(ConfigView.java:690)
	at com.biglybt.ui.swt.views.ConfigView.filterTree(ConfigView.java:706)
	at com.biglybt.ui.swt.views.ConfigView.lambda$14(ConfigView.java:666)
	at com.biglybt.ui.swt.Utils$17.runSupport(Utils.java:2139)
	at com.biglybt.core.util.AERunnable.run(AERunnable.java:42)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4001)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3629)
	at com.biglybt.ui.swt.mainwindow.SWTThread.<init>(SWTThread.java:526)
	at com.biglybt.ui.swt.mainwindow.SWTThread.createInstance(SWTThread.java:58)
	at com.biglybt.ui.swt.Initializer.<init>(Initializer.java:183)
	at com.biglybt.ui.swt.UI.takeMainThread(UI.java:162)
	at com.biglybt.ui.Main.main(Main.java:247)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.biglybt.launcher.Launcher$1.run(Launcher.java:48)
	at java.base/java.lang.Thread.run(Thread.java:1575)
 [stderr] 
```
- debug_2.log is also filled with below error, but not sure where yun.v6speed.org came from. searched in the All Trackers but nothing showed up for "v6speed"
`java.net.UnknownHostException: yun.v6speed.org`

the confusing thing is that BiglyBT reports IPv4 addrs when it says it's doing the IPv6 test. hence the mixed up

**Comment by parg** [comment]
It tries to explicitly resolve the IPv6 address and that is failing for you for some reason:

https://www.nslookup.io/domains/nettest.biglybt.com/dns-records/

Obviously it is confusing in that the resolution failure causes it to revert to running an IPv4 checkl

**Comment by parg** [comment]
That SWT error has already been fixed in 3701 betas

**Comment by SUCM** [comment]
ping nettest.biglybt.com in windows cmd automatically resolved to IPv6 addr. I tried ping -6 and ping -4, both work fine without any packet loss when repeated for more than 60 pings, but BiglyBT is passing/failing randomly. is there any logging to check what's going on?

the NAT OK icon in status bar is green all the time, so the port seemed to be ok in reality?

**Comment by parg** [comment]
I'll tidy things up a bit. 

Not sure why you are getting the IPv6 address resolution issue but I wouldn't worry, if it passes at least once then you're probably good.
