### ISSUE TITLE
error com.biglybt.core.backup.impl.BackupManagerImpl::copyFilesSupport

### ISSUE THREAD

**Issue by SUCM** [BiglySoftware/BiglyBT#3437]
is this a bug? on the backup mechanism or the plugin?

```
2024::com.biglybt.core.backup.impl.BackupManagerImpl::copyFilesSupport::683:
 [stderr]   Copy failed for D:\Prof\BiglyBT\plugins\aznettor\data\lock
 [stderr]     BackupManagerImpl::copyFilesSupport::666, BackupManagerImpl::copyFilesSupport::666, BackupManagerImpl::copyFilesSupport::666, BackupManagerImpl::copyFiles::606, BackupManagerImpl::backupSupport::928, BackupManagerImpl$7::runSupport::575, AsyncDispatcher$1::run::168, AEThread2$threadWrapper::run::334
 [stderr] java.io.IOException: The process cannot access the file because another process has locked a portion of the file 
 [stderr] 	at java.base/java.io.FileInputStream.readBytes(Native Method)
 [stderr] 	at java.base/java.io.FileInputStream.read(FileInputStream.java:328)
 [stderr] 	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:345)
 [stderr] 	at java.base/java.io.BufferedInputStream.implRead(BufferedInputStream.java:420)
 [stderr] 	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:399)
 [stderr] 	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:95)
 [stderr] 	at com.biglybt.core.util.FileUtil.copyFile(FileUtil.java:1660)
 [stderr] 	at com.biglybt.core.util.FileUtil.copyFile(FileUtil.java:1627)
 [stderr] 	at com.biglybt.core.util.FileUtil.copyFileWithDates(FileUtil.java:1457)
 [stderr] 	at com.biglybt.core.backup.impl.BackupManagerImpl.copyFilesSupport(BackupManagerImpl.java:683)
 [stderr] 	at com.biglybt.core.backup.impl.BackupManagerImpl.copyFilesSupport(BackupManagerImpl.java:666)
 [stderr] 	at com.biglybt.core.backup.impl.BackupManagerImpl.copyFilesSupport(BackupManagerImpl.java:666)
 [stderr] 	at com.biglybt.core.backup.impl.BackupManagerImpl.copyFilesSupport(BackupManagerImpl.java:666)
 [stderr] 	at com.biglybt.core.backup.impl.BackupManagerImpl.copyFiles(BackupManagerImpl.java:606)
 [stderr] 	at com.biglybt.core.backup.impl.BackupManagerImpl.backupSupport(BackupManagerImpl.java:928)
 [stderr] 	at com.biglybt.core.backup.impl.BackupManagerImpl$7.runSupport(BackupManagerImpl.java:575)
 [stderr] 	at com.biglybt.core.util.AsyncDispatcher$1.run(AsyncDispatcher.java:168)
 [stderr] 	at com.biglybt.core.util.AEThread2$threadWrapper.run(AEThread2.java:334)
```

**Comment by parg** [comment]
Did the backup complete? It isn't really a bug if it did.

**Comment by parg** [comment]
I'll add something to only backup the most recent versions. If you're bothered you can manually delete the old versions from the installation.

**Comment by SUCM** [comment]
are the **plugin.properties_{VERSION}** and **{BLAH}.bak** safe to delete as well?

**Comment by parg** [comment]
all .bak files are safe to delete

**Comment by parg** [comment]
as are the _version ones
