### ISSUE TITLE
XML over HTTP Plugin Installation Fails

### ISSUE THREAD

**Issue by srsgores** [BiglySoftware/BiglyBT#46]
Trying to install [XML over HTTP plugin](http://plugins.vuze.com/details/xml_http_if) on debian 9.0.2, I get:

> Error loading plugin 'XML over HTTP' from /usr/local/biglybt/plugins/xml_http_if: java.lang.NoClassDefFoundError: org/gudy/azureus2/ui/webplugin/WebPlugin
[alert] Alert:3:Error loading plugin 'XML over HTTP' from /usr/local/biglybt/plugins/xml_http_if
DEBUG::Wed Aug 30 04:19:55 UTC 2017::com.biglybt.pifimpl.local.PluginInitializer::loadPluginFromDir::1294:
  java.lang.NoClassDefFoundError: org/gudy/azureus2/ui/webplugin/WebPlugin
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at com.biglybt.platform.unix.PlatformManagerImpl.loadClass(PlatformManagerImpl.java:530)
        at com.biglybt.pifimpl.local.PluginInitializer.loadPluginFromDir(PluginInitializer.java:1149)
        at com.biglybt.pifimpl.local.PluginInitializer.reloadPlugin(PluginInitializer.java:1909)
        at com.biglybt.pifimpl.local.PluginManagerImpl.refreshPluginList(PluginManagerImpl.java:434)
        at com.biglybt.ui.swt.views.configsections.ConfigSectionPlugins$7.widgetSelected(ConfigSectionPlugins.java:582)
        at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
        at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5252)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1348)
        at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4522)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4107)
        at com.biglybt.ui.swt.mainwindow.SWTThread.<init>(SWTThread.java:284)
        at com.biglybt.ui.swt.mainwindow.SWTThread.createInstance(SWTThread.java:64)
        at com.biglybt.ui.swt.Initializer.<init>(Initializer.java:178)
        at com.biglybt.ui.swt.UI.takeMainThread(UI.java:108)
        at com.biglybt.ui.Main.main(Main.java:231)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.biglybt.launcher.MainExecutor$1.run(MainExecutor.java:37)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.gudy.azureus2.ui.webplugin.WebPlugin
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 33 more

The same error does **not** occur in latest vuze.

**Comment by parg** [comment]
The plugin needs to be rebuilt for BiglyBT - I'll look into it later today

**Comment by parg** [comment]
Version 2.0 is available on https://plugins.biglybt.com/ - untested
