### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by Havokdan** [BiglySoftware/BiglyBT#522]
> org.eclipse.swt.SWTException: Graphic is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4533)
	at org.eclipse.swt.SWT.error(SWT.java:4448)
	at org.eclipse.swt.SWT.error(SWT.java:4419)
	at org.eclipse.swt.graphics.Image.getBoundsInPixels(Image.java:1427)
	at org.eclipse.swt.widgets.Button.computeSizeInPixels(Button.java:447)
	at org.eclipse.swt.widgets.Control.computeSize(Control.java:663)
	at org.eclipse.swt.layout.GridData.computeSize(GridData.java:491)
	at org.eclipse.swt.layout.GridLayout.layout(GridLayout.java:221)
	at org.eclipse.swt.layout.GridLayout.computeSize(GridLayout.java:164)
	at org.eclipse.swt.widgets.Composite.computeSizeInPixels(Composite.java:215)
	at org.eclipse.swt.widgets.Control.computeSize(Control.java:663)
	at org.eclipse.swt.layout.RowLayout.computeSize(RowLayout.java:221)
	at org.eclipse.swt.layout.RowLayout.layoutHorizontal(RowLayout.java:263)
	at org.eclipse.swt.layout.RowLayout.computeSize(RowLayout.java:205)
	at org.eclipse.swt.widgets.Composite.computeSizeInPixels(Composite.java:215)
	at org.eclipse.swt.widgets.Control.computeSize(Control.java:663)
	at org.eclipse.swt.layout.GridData.computeSize(GridData.java:491)
	at org.eclipse.swt.layout.GridLayout.layout(GridLayout.java:221)
	at org.eclipse.swt.layout.GridLayout.computeSize(GridLayout.java:164)
	at org.eclipse.swt.widgets.Composite.computeSizeInPixels(Composite.java:215)
	at org.eclipse.swt.widgets.Control.computeSize(Control.java:663)
	at org.eclipse.swt.layout.FormData.computeSize(FormData.java:128)
	at org.eclipse.swt.layout.FormLayout.layout(FormLayout.java:323)
	at org.eclipse.swt.layout.FormLayout.layout(FormLayout.java:289)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1363)
	at org.eclipse.swt.widgets.Composite.WM_SIZE(Composite.java:1774)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4918)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5178)
	at org.eclipse.swt.internal.win32.OS.DefWindowProcW(Native Method)
	at org.eclipse.swt.internal.win32.OS.DefWindowProc(OS.java:2555)
	at org.eclipse.swt.widgets.Scrollable.callWindowProc(Scrollable.java:88)
	at org.eclipse.swt.widgets.Control.WM_WINDOWPOSCHANGED(Control.java:5743)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4931)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5191)
	at org.eclipse.swt.internal.win32.OS.EndDeferWindowPos(Native Method)
	at org.eclipse.swt.widgets.Composite.resizeChildren(Composite.java:1007)
	at org.eclipse.swt.widgets.Composite.resizeChildren(Composite.java:973)
	at org.eclipse.swt.widgets.Composite.setResizeChildren(Composite.java:1187)
	at org.eclipse.swt.widgets.Composite.WM_SIZE(Composite.java:1778)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4918)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5178)
	at org.eclipse.swt.internal.win32.OS.DefWindowProcW(Native Method)
	at org.eclipse.swt.internal.win32.OS.DefWindowProc(OS.java:2555)
	at org.eclipse.swt.widgets.Scrollable.callWindowProc(Scrollable.java:88)
	at org.eclipse.swt.widgets.Control.WM_WINDOWPOSCHANGED(Control.java:5743)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4931)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5191)
	at org.eclipse.swt.internal.win32.OS.EndDeferWindowPos(Native Method)
	at org.eclipse.swt.widgets.Composite.resizeChildren(Composite.java:1007)
	at org.eclipse.swt.widgets.Composite.resizeChildren(Composite.java:973)
	at org.eclipse.swt.widgets.Composite.setResizeChildren(Composite.java:1187)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1364)
	at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1348)
	at org.eclipse.swt.widgets.Composite.setLayoutDeferred(Composite.java:1147)
	at org.eclipse.swt.widgets.Display.runDeferredLayouts(Display.java:4262)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3810)
	at com.biglybt.ui.swt.mainwindow.SWTThread.<init>(SWTThread.java:284)
	at com.biglybt.ui.swt.mainwindow.SWTThread.createInstance(SWTThread.java:64)
	at com.biglybt.ui.swt.Initializer.<init>(Initializer.java:179)
	at com.biglybt.ui.swt.UI.takeMainThread(UI.java:108)
	at com.biglybt.ui.Main.main(Main.java:236)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.biglybt.launcher.MainExecutor$1.run(MainExecutor.java:37)
	at java.lang.Thread.run(Thread.java:748)

Java 1.8.0_171 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4757, win32
Windows 10 v10.0, amd64 (64 bit)
B1.5.0.1_B18/4 az3

**Comment by TuxPaper** [comment]
*stabs SWT*

Have you seen this bug since then?

**Comment by Havokdan** [comment]
This problem has stopped happening.
