### ISSUE TITLE
Unhandled error in the GUI -- Null Pointer Exception

### ISSUE THREAD

**Issue by ackerthehacker2** [BiglySoftware/BiglyBT#592]
![screen shot 2018-09-03 at 11 04 43 pm](https://user-images.githubusercontent.com/38703791/45009446-cac71000-afcd-11e8-8560-fb0181afa7d1.jpg)
java.lang.NullPointerException
	at org.eclipse.swt.widgets.Control.internal_new_GC(Control.java:2124)
	at org.eclipse.swt.graphics.GC.cocoa_new(GC.java:210)
	at org.eclipse.swt.widgets.Tree.sendMeasureItem(Tree.java:2596)
	at org.eclipse.swt.widgets.Tree.cellSize(Tree.java:288)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5590)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper_stret(Native Method)
	at org.eclipse.swt.widgets.Widget.expansionFrameWithFrame_inView(Widget.java:814)
	at org.eclipse.swt.widgets.Tree.expansionFrameWithFrame_inView(Tree.java:1274)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5969)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend_bool(Native Method)
	at org.eclipse.swt.internal.cocoa.NSRunLoop.runMode(NSRunLoop.java:42)
	at org.eclipse.swt.widgets.Display.sleep(Display.java:4740)
	at com.biglybt.ui.swt.mainwindow.SWTThread.<init>(SWTThread.java:285)
	at com.biglybt.ui.swt.mainwindow.SWTThread.createInstance(SWTThread.java:64)
	at com.biglybt.ui.swt.Initializer.<init>(Initializer.java:179)
	at com.biglybt.ui.swt.UI.takeMainThread(UI.java:110)
	at com.biglybt.ui.Main.main(Main.java:236)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:65)

**Comment by ackerthehacker2** [comment]
[debug_1.log](https://github.com/BiglySoftware/BiglyBT/files/2347135/debug_1.log)

**Comment by parg** [comment]
Thanks for the report - that is being generated somewhere within the GUI library we use (SWT) and isn't something we can fix ourselves - as long as you're not seeing any issues with BiglyBT at the time it occurs please ignore it :)
