### ISSUE TITLE
Javascript tag constrains cannot contain brackets

### ISSUE THREAD

**Issue by jaymzjulian** [BiglySoftware/BiglyBT#601]
Tag _actions_ work, but not _constraints_ with javascript - for the simple case, the documented example of: ```javascript("download.getTorrent().getSize() > 10*1024*1024")```

throws the exception: ```Invalid constraint: Unsupported construct: "download.getTorrent().getSize() > 10*1024*1024"```  (Full exception pasted at the end). 

Looking at the function that it's throwing exception in, compileBasic, it shouldn't be getting there in the first place as near as I can tell - it looks like it's coming through a call to _params.getValues(), which sees the ()s in the above and goes "this needs evaluation" - ignoring the fact that it's a literal string (which wouldn't affect any other type of constraint.  I can confirm this by changing the constraint to:
```javascript("download.getTorrent.getSize>10*1024*1024")```

Which, of course, throws exceptions on the javascript side, but that's okay becuase we're getting into the javascript side!  However, obviously you can't do much with it.  It seems like getValues() should check for a literal string before checking for brackets, maybe?

Full exception:
```[09:55:30] java.lang.RuntimeException: Unsupported construct: "download.getTorrent().getSize() > 10*1024*1024"
        at com.biglybt.core.tag.impl.TagPropertyConstraintHandler$TagConstraint.compileBasic(TagPropertyConstraintHandler.java:933)
        at com.biglybt.core.tag.impl.TagPropertyConstraintHandler$TagConstraint.compileStart(TagPropertyConstraintHandler.java:883)
        at com.biglybt.core.tag.impl.TagPropertyConstraintHandler$TagConstraint.access$0(TagPropertyConstraintHandler.java:788)
        at com.biglybt.core.tag.impl.TagPropertyConstraintHandler$TagConstraint$ConstraintExprParams.getValues(TagPropertyConstraintHandler.java:1226)
        at com.biglybt.core.tag.impl.TagPropertyConstraintHandler$TagConstraint$ConstraintExprFunction.<init>(TagPropertyConstraintHandler.java:1594)
        at com.biglybt.core.tag.impl.TagPropertyConstraintHandler$TagConstraint$ConstraintExprFunction.<init>(TagPropertyConstraintHandler.java:1587)
        at com.biglybt.core.tag.impl.TagPropertyConstraintHandler$TagConstraint.compileBasic(TagPropertyConstraintHandler.java:929)
        at com.biglybt.core.tag.impl.TagPropertyConstraintHandler$TagConstraint.compileStart(TagPropertyConstraintHandler.java:883)
        at com.biglybt.core.tag.impl.TagPropertyConstraintHandler$TagConstraint.access$0(TagPropertyConstraintHandler.java:788)
        at com.biglybt.core.tag.impl.TagPropertyConstraintHandler$TagConstraint$ConstraintExprParams.getValues(TagPropertyConstraintHandler.java:1226)
        at com.biglybt.core.tag.impl.TagPropertyConstraintHandler$TagConstraint$ConstraintExprFunction.<init>(TagPropertyConstraintHandler.java:1594)
        at com.biglybt.core.tag.impl.TagPropertyConstraintHandler$TagConstraint$ConstraintExprFunction.<init>(TagPropertyConstraintHandler.java:1587)
        at com.biglybt.core.tag.impl.TagPropertyConstraintHandler$TagConstraint.compileBasic(TagPropertyConstraintHandler.java:929)
        at com.biglybt.core.tag.impl.TagPropertyConstraintHandler$TagConstraint.compileStart(TagPropertyConstraintHandler.java:883)
        at com.biglybt.core.tag.impl.TagPropertyConstraintHandler$TagConstraint.<init>(TagPropertyConstraintHandler.java:753)
        at com.biglybt.core.tag.impl.TagPropertyConstraintHandler$TagConstraint.<init>(TagPropertyConstraintHandler.java:724)
        at com.biglybt.core.tag.impl.TagPropertyConstraintHandler.handleProperty(TagPropertyConstraintHandler.java:528)
        at com.biglybt.core.tag.impl.TagPropertyConstraintHandler.access$10(TagPropertyConstraintHandler.java:484)
        at com.biglybt.core.tag.impl.TagPropertyConstraintHandler$4.propertyChanged(TagPropertyConstraintHandler.java:283)
        at com.biglybt.core.tag.impl.TagBase$TagPropertyImpl.setStringList(TagBase.java:2259)```

**Comment by parg** [comment]
Borkage indeed! Fixed next beta, thanks

**Comment by parg** [comment]
B11 is out!

**Comment by jaymzjulian** [comment]
Confirming fix is good for me - thanks heaps!
