### ISSUE TITLE
Beta crashs

### ISSUE THREAD

**Issue by ackerthehacker2** [BiglySoftware/BiglyBT#892]
Mac OS 10.14.4 Beta (18E194e)

Bigly BT 1.8.0.1_b20

Unexpected shutdown/crash
java.lang.NullPointerException
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3735)
	at com.biglybt.ui.swt.mainwindow.SWTThread.<init>(SWTThread.java:257)
	at com.biglybt.ui.swt.mainwindow.SWTThread.createInstance(SWTThread.java:64)
	at com.biglybt.ui.swt.Initializer.<init>(Initializer.java:179)
	at com.biglybt.ui.swt.UI.takeMainThread(UI.java:110)
	at com.biglybt.ui.Main.main(Main.java:236)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:85)
	at com.install4j.runtime.launcher.MacLauncher.main(MacLauncher.java:53)

The debug file is too big to upload ..

https://www.dropbox.com/s/owkzkonlkn80hwm/debug.zip?dl=0

**Comment by BreakfeastAnarchy** [comment]
Okay, my first post.       Last login: Thu May 23 05:01:01 on ttys000
You have mail.
/Applications/BiglyBT/BiglyBT.app/Contents/MacOS/JavaApplicationStub ; exit;
Suspense66:~ Suspense66$ /Applications/BiglyBT/BiglyBT.app/Contents/MacOS/JavaApplicationStub ; exit;
Enabling broken select detection: diablo=false, freebsd 7+=false, osx 10.6+=true
UIFunctions/ImageLoad took 26ms
new shell took 68ms
new shell setup took 146ms
skin init took 144ms
MainMenu init took 58ms
pre skin widgets init took 58ms
skin widgets (1/2) init took 139ms
skin widgets (2/2) init took 140ms
pre SWTInstance init took 0ms
Init Core Columns took 107ms
SWTInstance init took 0ms
shell.layout took 80ms
---------SHOWN AT 1558581179805;1919ms
---------DONE DISPATCH AT 1558581180306;2420ms
---------READY AT 1558581180365;2479ms
shell.open took 560ms
processStartupDMS took 0ms
postPluginSetup init took 0ms
Locale Initializing took 0ms
Core Initializing took 1801ms
Starting idle sleep preventer: /usr/bin/caffeinate
Warning - No client config file /Users/suspense66/Library/Application Support/BiglyBT/plugins/azneti2phelper/clients.config
Warning - No client apps or router console configured - we are just a router
Loaded /Users/suspense66/Library/Application Support/BiglyBT/plugins/azlocprov/GeoLite2-Country_0.4.0.mmdb
Stopping idle sleep preventer
Starting idle sleep preventer: /usr/bin/caffeinate
[µTorrent Mac 1.8.7]decodePiece(): Peer has sent piece #234:425984->442367, but expired piece block discarded as never requested.
[µTorrent Mac 1.8.7]decodePiece(): Peer has sent piece #234:442368->458751, but expired piece block discarded as never requested.
[µTorrent Mac 1.8.7]decodePiece(): Peer has sent piece #907:1196032->1212415, but expired piece block discarded as never requested.
[µTorrent Mac 1.8.7]decodePiece(): Peer has sent piece #907:1212416->1228799, but expired piece block discarded as never requested.
2019-05-23 05:49:40.603 JavaApplicationStub[3062:54776] [QL] Launch Services Database change notification (com.apple.LaunchServices.DatabaseChange). Resetting Generator caches.
2019-05-23 05:50:05.883 JavaApplicationStub[3062:55087] [QL] Launch Services Database change notification (com.apple.LaunchServices.DatabaseChange). Resetting Generator caches.
2019-05-23 05:53:35.513 JavaApplicationStub[3062:56784] [QL] Launch Services Database change notification (com.apple.LaunchServices.DatabaseChange). Resetting Generator caches.
2019-05-23 05:54:25.525 JavaApplicationStub[3062:58281] [QL] Launch Services Database change notification (com.apple.LaunchServices.DatabaseChange). Resetting Generator caches.
2019-05-23 05:55:03.849 JavaApplicationStub[3062:58281] [QL] Launch Services Database change notification (com.apple.LaunchServices.DatabaseChange). Resetting Generator caches.
DEBUG::Thu May 23 05:58:42 CEST 2019::com.biglybt.core.util.AEThread2$threadWrapper::run::304:
  writeSelectorLoop() EXCEPTION: 
    
java.nio.channels.CancelledKeyException
	at sun.nio.ch.SelectionKeyImpl.ensureValid(SelectionKeyImpl.java:73)
	at sun.nio.ch.SelectionKeyImpl.readyOps(SelectionKeyImpl.java:87)
	at com.biglybt.core.networkmanager.impl.tcp.VirtualChannelSelectorImpl.select(VirtualChannelSelectorImpl.java:928)
	at com.biglybt.core.networkmanager.VirtualChannelSelector.select(VirtualChannelSelector.java:399)
	at com.biglybt.core.networkmanager.impl.tcp.TCPNetworkManager$5.run(TCPNetworkManager.java:260)
	at com.biglybt.core.util.AEThread2$threadWrapper.run(AEThread2.java:304)
Sorry, later more. I'm trying to fix Photoshop, which also crashed....       2019-05-23 06:15:11.684 JavaApplicationStub[3062:60669] [QL] Launch Services Database change notification (com.apple.LaunchServices.DatabaseChange). Resetting Generator caches.
2019-05-23 06:15:26.414 JavaApplicationStub[3062:60851] [QL] Launch Services Database change notification (com.apple.LaunchServices.DatabaseChange). Resetting Generator caches.
