### ISSUE TITLE
Crash after download completion.

### ISSUE THREAD

**Issue by Achaean** [BiglySoftware/BiglyBT#895]
Bigly keeps crashing after downloading a torrent.

Java 1.8.0_181 (64 bit)
  Oracle Corporation
/usr/lib/jvm/java-8-openjdk-amd64/jre

SWT v4922, gtk/3.22.11, zoom=100, dpi=96
Linux v4.9.0-8-amd64, amd64 (64 bit)
B1.8.0.0/4 az3

On Devuan ASCII (stable) x64 KDE (based on Debian stable).

I'm also uploading the save directory (as Bigly prompted me).
[save.zip](https://github.com/BiglySoftware/BiglyBT/files/2892008/save.zip)

**Comment by parg** [comment]
May be something to do with

[13:46:59] [stderr] SWT Webkit.java Error: Could not find webkit extension. BrowserFunction functionality will not be available. 
(swt version: 4922r32) SWT Glue code version: 54.0 info: +BrowserFunction/GDBus, +WebkitExtension Folder versioning, +WebKitExtension OSGI support, +setUrl(..postData..), -setCookie(), -getCookie +mouseDown/Focus

[13:46:59] [stderr] WebKit2Gtk version 2.18.6

[13:46:59] [stderr] Please report this issue *with steps to reproduce* via:
 https://bugs.eclipse.org/bugs/enter_bug.cgi?alias=&assigned_to=platform-swt-inbox%40eclipse.org&attach_text=&blocked=&bug_file_loc=http%3A%2F%2F&bug_severity=normal&bug_status=NEW&comment=&component=SWT&contenttypeentry=&contenttypemethod=autodetect&contenttypeselection=text%2Fplain&data=&defined_groups=1&dependson=&description=&flag_type-1=X&flag_type-11=X&flag_type-12=X&flag_type-13=X&flag_type-14=X&flag_type-15=X&flag_type-16=X&flag_type-2=X&flag_type-4=X&flag_type-6=X&flag_type-7=X&flag_type-8=X&form_name=enter_bug&keywords=&maketemplate=Remember%20values%20as%20bookmarkable%20template&op_sys=Linux&product=Platform&qa_contact=&rep_platform=PC&requestee_type-1=&requestee_type-2=&short_desc=webkit2_BrowserProblem
For bug report, please atatch this stack trace:
java.lang.Throwable: 
	at org.eclipse.swt.browser.WebKit.getStackTrace(WebKit.java:489)
	at org.eclipse.swt.browser.WebKit.getInternalErrorMsg(WebKit.java:482)
	at org.eclipse.swt.browser.WebKit.access$200(WebKit.java:124)
	at org.eclipse.swt.browser.WebKit$Webkit2Extension.initializeWebExtensions_callback(WebKit.java:594)
	at org.eclipse.swt.internal.webkit.WebKitGTK._webkit_web_view_new(Native Method)
	at org.eclipse.swt.internal.webkit.WebKitGTK.webkit_web_view_new(WebKitGTK.java:1928)
	at org.eclipse.swt.browser.WebKit.create(WebKit.java:1142)
	at org.eclipse.swt.browser.Browser.<init>(Browser.java:102)
	at com.biglybt.ui.swt.BrowserWrapperSWT.<init>(BrowserWrapperSWT.java:52)
	at com.biglybt.ui.swt.BrowserWrapperSWTFactory.create(BrowserWrapperSWTFactory.java:63)
	at com.biglybt.ui.swt.BrowserWrapper.createBrowser(BrowserWrapper.java:57)
	at com.biglybt.ui.swt.skin.SWTSkinObjectBrowser.init(SWTSkinObjectBrowser.java:266)
	at com.biglybt.ui.swt.skin.SWTSkinObjectBrowser$3.eventOccured(SWTSkinObjectBrowser.java:252)
	at com.biglybt.ui.swt.skin.SWTSkinObjectBasic.triggerListenersRaw(SWTSkinObjectBasic.java:943)
	at com.biglybt.ui.swt.skin.SWTSkinObjectBasic.triggerListeners(SWTSkinObjectBasic.java:899)
	at com.biglybt.ui.swt.skin.SWTSkinObjectBasic.triggerListeners(SWTSkinObjectBasic.java:861)
	at com.biglybt.ui.swt.skin.SWTSkinObjectBasic.setIsVisible(SWTSkinObjectBasic.java:332)
	at com.biglybt.ui.swt.skin.SWTSkinObjectBrowser.setIsVisible(SWTSkinObjectBrowser.java:496)
	at com.biglybt.ui.swt.skin.SWTSkinObjectContainer$4.runSupport(SWTSkinObjectContainer.java:312)
	at com.biglybt.core.util.AERunnable.run(AERunnable.java:36)
	at com.biglybt.ui.swt.Utils$1.run(Utils.java:972)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4906)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4475)
	at com.biglybt.ui.swt.mainwindow.SWTThread.<init>(SWTThread.java:284)
	at com.biglybt.ui.swt.mainwindow.SWTThread.createInstance(SWTThread.java:64)
	at com.biglybt.ui.swt.Initializer.<init>(Initializer.java:179)
	at com.biglybt.ui.swt.UI.takeMainThread(UI.java:110)
	at com.biglybt.ui.Main.main(Main.java:236)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.biglybt.launcher.MainExecutor$1.run(MainExecutor.java:37)
	at java.lang.Thread.run(Thread.java:748)


Try disabling use of the internal browser - Tools->Options->Interface->Display: Internal Browser

**Comment by Achaean** [comment]
**THANKS** Parg! :-)

Disabling the internal browser, didn't help.
I'm going to report this error.

Meanwhile, since this bug isn't related to Bigly, I'm closing this report.
If this isn't the case, feel free to reopen it.

**Comment by parg** [comment]
Thanks for reporting it. My assumption was that the crash was related to a web-browser based donation popup caused by download completion - if disabling the internal browser didn't remove the crash then perhaps I was wrong. Not sure what else would be triggered unless it was a system tray notification. You could try disabling

Tools->Options->Interface->Alerts: Native Notifications

although I'm not actually sure if they are used on your OS

**Comment by Achaean** [comment]
Indeed! :-)

Disabling native notifications did the trick!
