### ISSUE TITLE
Repeated Untidy Shutdowns - Stable and Beta versions

### ISSUE THREAD

**Issue by darkeyce** [BiglySoftware/BiglyBT#981]
**Issue**: BiglyBT will randomly shutdown. the Untidy shutdown warning points to the log files (but doesn't suggest what to look for) and the Wiki article referenced doesn't exist (although a VUZE article does).

This happens with all beta versions I've tested, let me know which log files you want to see and I'll provide them.

Java 1.8.0_152 (64 bit)
  Oracle Corporation
c:\program files\biglybt\jre

SWT v4922, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B1.9.0.1_B03/4 az3

Most recent text from  Alerts log...

`[4/2/19 6:50 AM] Log File Opened for BiglyBT 1.9.0.1_B02
[06:50:41] Alert:1:BiglyBT did not shutdown tidily. Check for any <A HREF="C:\Users\Darkeyce\AppData\Roaming\BiglyBT\logs\save">diagnostic log files</A>. Also read the wiki article <A HREF="https://wiki.biglybt.com/w/Vuze_disappears">BiglyBT Disappears</A> for more information.
[06:56:02] Alert:3:Backup failed at Tue Apr 02 06:56:02 PDT 2019 (Failed to copy file 'C:\Users\Darkeyce\AppData\Roaming\BiglyBT\active\BD715C0EB366798E6F0C15409C25B0FA744A9ED4.dat._az', java.lang.Exception: Failed to copy file 'C:\Users\Darkeyce\AppData\Roaming\BiglyBT\active\BD715C0EB366798E6F0C15409C25B0FA744A9ED4.dat._az'; copyFilesSupport (BackupManagerImpl.java:680), copyFilesSupport (BackupManagerImpl.java:640), copyFiles (BackupManagerImpl.java:606), backupSupport (BackupManagerImpl.java:891), runSupport (BackupManagerImpl.java:575), run (AsyncDispatcher.java:161), run (AEThread2.java:304))
[09:12:24] Alert:3:An unhandled error occurred in the GUI, further errors may be reported. (NullPointerException, java.lang.NullPointerException; filterMessage (Display.java:1207), readAndDispatch (Display.java:3544), <init> (SWTThread.java:257), createInstance (SWTThread.java:64), Initializer)

[4/2/19 9:14 AM] Log File Opened for BiglyBT 1.9.0.1_B02
[09:14:49] Alert:1:BiglyBT did not shutdown tidily. Check for any <A HREF="C:\Users\Darkeyce\AppData\Roaming\BiglyBT\logs\save">diagnostic log files</A>. Also read the wiki article <A HREF="https://wiki.biglybt.com/w/Vuze_disappears">BiglyBT Disappears</A> for more information.

[4/2/19 11:50 AM] Log File Opened for BiglyBT 1.9.0.1_B02
[11:50:08] Alert:1:BiglyBT did not shutdown tidily. Check for any <A HREF="C:\Users\Darkeyce\AppData\Roaming\BiglyBT\logs\save">diagnostic log files</A>. Also read the wiki article <A HREF="https://wiki.biglybt.com/w/Vuze_disappears">BiglyBT Disappears</A> for more information.

[4/2/19 1:23 PM] Log File Opened for BiglyBT 1.9.0.1_B02
[13:23:04] Alert:1:BiglyBT did not shutdown tidily. Check for any <A HREF="C:\Users\Darkeyce\AppData\Roaming\BiglyBT\logs\save">diagnostic log files</A>. Also read the wiki article <A HREF="https://wiki.biglybt.com/w/Vuze_disappears">BiglyBT Disappears</A> for more information.

[4/2/19 3:24 PM] Log File Opened for BiglyBT 1.9.0.1_B03
[15:24:12] Alert:1:BiglyBT did not shutdown tidily. Check for any <A HREF="C:\Users\Darkeyce\AppData\Roaming\BiglyBT\logs\save">diagnostic log files</A>. Also read the wiki article <A HREF="https://wiki.biglybt.com/w/Vuze_disappears">BiglyBT Disappears</A> for more information.

[4/2/19 8:04 PM] Log File Opened for BiglyBT 1.9.0.1_B03
[20:04:13] Alert:1:BiglyBT did not shutdown tidily. Check for any <A HREF="C:\Users\Darkeyce\AppData\Roaming\BiglyBT\logs\save">diagnostic log files</A>. Also read the wiki article <A HREF="https://wiki.biglybt.com/w/Vuze_disappears">BiglyBT Disappears</A> for more information.
[01:35:58] Alert:3:An unhandled error occurred in the GUI, further errors may be reported. (No more handles, org.eclipse.swt.SWTError: No more handles; error (SWT.java:4621), error (SWT.java:4510), error (SWT.java:4481), createGdipImage (Image.java:994), drawImage (GC.java:959), drawImageInPixels (GC.java:886), drawImage (GC.java:879), paintControl (MainStatusBar.java:1908), handleEvent (TypedListener.java:234), sendEvent (EventTable.java:89), sendEvent (Display.java:4132), sendEvent (Widget.java:1055), sendEvent (Widget.java:1079), sendEvent (Widget.java:1064), WM_PAINT (Composite.java:1564), windowProc (Control.java:4825), windowProc (Canvas.java:348), windowProc (Display.java:4779), DispatchMessageW (OS.java:-2), DispatchMessage (OS.java:2309), readAndDispatch (Display.java:3546), <init> (SWTThread.java:257), createInstance (SWTThread.java:64), Initializer)
`

**Comment by parg** [comment]
Can you check the debug_1/2.log and thread_1/2.log files as well?

**Comment by darkeyce** [comment]
Debug 2 seems to have some relevant detail, not so with debug 1

[1554292352578_debug_2.log](https://github.com/BiglySoftware/BiglyBT/files/3039178/1554292352578_debug_2.log)
[1554292352578_debug_1.log](https://github.com/BiglySoftware/BiglyBT/files/3039181/1554292352578_debug_1.log)

**Comment by darkeyce** [comment]
NO idea what i'm looking at in in the Thread Logs...
[1554292352578_thread_1.log](https://github.com/BiglySoftware/BiglyBT/files/3039187/1554292352578_thread_1.log)
[1554292352578_thread_2.log](https://github.com/BiglySoftware/BiglyBT/files/3039188/1554292352578_thread_2.log)

**Comment by parg** [comment]
Hmm, you seem to be getting outofmemory errors within the I2P plugin:

[01:53:23] java.lang.OutOfMemoryError
	at java.util.zip.Deflater.init(Native Method)
	at java.util.zip.Deflater.<init>(Unknown Source)
	at net.i2p.util.ResettableGZIPOutputStream.<init>(ResettableGZIPOutputStream.java:27)
	at net.i2p.util.ReusableGZIPOutputStream.<init>(ReusableGZIPOutputStream.java:61)
	at net.i2p.util.ReusableGZIPOutputStream.acquire(ReusableGZIPOutputStream.java:43)
	at net.i2p.data.DataHelper.compress(DataHelper.java:1714)
	at net.i2p.data.DataHelper.compress(DataHelper.java:1693)
	at net.i2p.client.impl.I2PSessionMuxedImpl.prepPayload(I2PSessionMuxedImpl.java:295)
	at net.i2p.client.impl.I2PSessionMuxedImpl.sendMessage(I2PSessionMuxedImpl.java:245)
	at org.parg.azureus.plugins.networks.i2p.vuzedht.DHTTransportI2PRealImpl.sendMessage(DHTTransportI2PRealImpl.java:2232)
	at org.parg.azureus.plugins.networks.i2p.vuzedht.DHTTransportI2PRealImpl.sendResponse(DHTTransportI2PRealImpl.java:2163)
	at org.parg.azureus.plugins.networks.i2p.vuzedht.DHTTransportI2PRealImpl.receiveFindValue(DHTTransportI2PRealImpl.java:1310)
	at org.parg.azureus.plugins.networks.i2p.vuzedht.DHTTransportI2PRealImpl.receiveQuery(DHTTransportI2PRealImpl.java:2500)
	at org.parg.azureus.plugins.networks.i2p.vuzedht.DHTTransportI2PRealImpl.receiveMessage(DHTTransportI2PRealImpl.java:2360)
	at org.parg.azureus.plugins.networks.i2p.vuzedht.DHTTransportI2PRealImpl.messageAvailable(DHTTransportI2PRealImpl.java:2288)
	at net.i2p.client.impl.I2PSessionDemultiplexer.messageAvailable(I2PSessionDemultiplexer.java:43)
	at net.i2p.client.impl.I2PSessionMuxedImpl$MuxedAvailabilityNotifier.run(I2PSessionMuxedImpl.java:408)
	at java.lang.Thread.run(Unknown Source)
	at net.i2p.util.I2PThread.run(I2PThread.java:103)

which ultimately cause BiglyBT to crash - you have plenty of memory available within the Java runtime, so it must be some internal bug.

Might be https://github.com/jwtk/jjwt/issues/392

Let me check what version of Java 8 we are shipping - you could try deleting 

c:\program files\biglybt\jre

and reinstalling BiglyBT if you have time to spare to see if it pulls in a more recent one

**Comment by parg** [comment]
hmm, hang on, that isn't a Java error, its a use-of-it :) let me look into things further.

**Comment by darkeyce** [comment]
Well, I deleted the JRE and reinstalled and it pulled the current java version (_202). And then i saw your "hang on post", so..oops.

**Comment by parg** [comment]
good to be on a higher java version anyway :)

**Comment by darkeyce** [comment]
Still happening on the higher java version....
[1554337888275_debug_1.log](https://github.com/BiglySoftware/BiglyBT/files/3041424/1554337888275_debug_1.log)

**Comment by darkeyce** [comment]
[debug.zip](https://github.com/BiglySoftware/BiglyBT/files/3043273/debug.zip)

**Comment by parg** [comment]
I raised an issue with I2P to see if they had any ideas. In the meantime perhaps you could grab an attempted fix 

[azi2pcore_0.9.39.2.jar.zip](https://github.com/BiglySoftware/BiglyBT/files/3047781/azi2pcore_0.9.39.2.jar.zip)

Unzip this to get azi2pcore_0.9.39.2.jar and place this in the 'azneti2phelper' plugin folder in the BiglyBT user-config folder's 'plugins' folder? (there should be an existing azi2pcore_0.9.39.1.jar in there amongst other things)

Then restart BiglyBT and see if that helps

**Comment by darkeyce** [comment]
I've installed this .jar file and since it's installation I haven't had any unexpected shutdowns. So as far as testing goes, id call that a win :).

**Comment by parg** [comment]
excellent, please report if it recurs and close this issue if you're happy it has gone away!
